package gov.nih.nci.coppa.services.outcomes.patient.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class PatientImpl extends PatientImplBase {

	
	public PatientImpl() throws RemoteException {
		super();
	}
	
  public gov.nih.nci.coppa.services.outcomes.Patient get(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.Patient create(gov.nih.nci.coppa.services.outcomes.Patient patient) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.Patient update(gov.nih.nci.coppa.services.outcomes.Patient patient) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

