function  WWHBookData_Files(P)
{
P.fA("NCI Clinical Trials Reporting Program Trial Registration Site Online Help","Welcome.1.1.html");
P.fA("Using the Online Help","Welcome.1.2.html");
P.fA("Using Navigation Tools","Welcome.1.3.html");
P.fA("Getting Started","GettingStarted.2.1.html");
P.fA("About the CTRP Registration Site","GettingStarted.2.2.html");
P.fA("What\u2019s New in This Release","GettingStarted.2.3.html");
P.fA("Creating an Account","GettingStarted.2.4.html");
P.fA("Logging In to the CTRP Registration Site","GettingStarted.2.5.html");
P.fA("Using CTRP Trial Registration Templates and Resources","GettingStarted.2.6.html");
P.fA("Downloading Trial Registration Templates","GettingStarted.2.7.html");
P.fA("Using the Proprietary Trial Template","GettingStarted.2.8.html");
P.fA("Using the Participating Sites Template","GettingStarted.2.9.html");
P.fA("Using the Batch Upload Template","GettingStarted.2.10.html");
P.fA("Searching For Trials","searchTrials.3.1.html");
P.fA("About Clinical Trial Metadata","searchTrials.3.2.html");
P.fA("Searching For Trials","searchTrials.3.3.html");
P.fA("Working with Search Results","searchTrials.3.4.html");
P.fA("Navigating Through the Search Results List","searchTrials.3.5.html");
P.fA("Viewing Trial Details","searchTrials.3.6.html");
P.fA("Viewing Trial-Related Documents","searchTrials.3.7.html");
P.fA("Registering New Trials","register.4.1.html");
P.fA("Registering Non-Proprietary Trials in the CTRP Registration Site","register.4.2.html");
P.fA("Editing Trial Details","register.4.3.html");
P.fA("Printing Trial Information","register.4.4.html");
P.fA("Completing the Trial Details Section","register.4.5.html");
P.fA("Completing the Lead Organization/Principal Investigator Section","register.4.6.html");
P.fA("Completing the Sponsor/Responsible Party Section","register.4.7.html");
P.fA("Completing the Summary 4 Information Section","register.4.8.html");
P.fA("Completing the NIH Grant Information Section","register.4.9.html");
P.fA("Completing the Trial Status/Dates Section","register.4.10.html");
P.fA("Completing the IND/IDE Information Section","register.4.11.html");
P.fA("Registering IND Trials","register.4.12.html");
P.fA("Registering IDE Trials","register.4.13.html");
P.fA("Completing the Trial Related Documents Section","register.4.14.html");
P.fA("Registering Proprietary Trials in the CTRP Registration Site","register.4.15.html");
P.fA("Completing the Trial Identification Section for Proprietary Trials","register.4.16.html");
P.fA("Completing the Trial Details Section for Proprietary Trials","register.4.17.html");
P.fA("Completing Summary 4 Information for Proprietary Trials","register.4.18.html");
P.fA("Completing the Trial Status/Dates Section for Proprietary Trials","register.4.19.html");
P.fA("Completing the Trial Related Documents Section for Proprietary Trials","register.4.20.html");
P.fA("Registering Organizations","register.4.21.html");
P.fA("Searching for Registered Organizations","register.4.22.html");
P.fA("Adding Organizations","register.4.23.html");
P.fA("Registering Persons","register.4.24.html");
P.fA("Searching for Principal Investigators","register.4.25.html");
P.fA("Adding Principal Investigators","register.4.26.html");
P.fA("Registering Multiple Trials in a Batch","register.4.27.html");
P.fA("Data Requirements for Batch Uploads","register.4.28.html");
P.fA("Updating and Amending Registered Trials","amendTrial.5.1.html");
P.fA("About Trial Updates","amendTrial.5.2.html");
P.fA("Updating Accepted Trials","amendTrial.5.3.html");
P.fA("About Trial Amendments","amendTrial.5.4.html");
P.fA("Amendment Process Life Cycle","amendTrial.5.5.html");
P.fA("Amending Verified Trials","amendTrial.5.6.html");
P.fA("Amending Trial Details","amendTrial.5.7.html");
P.fA("Amending Lead Organization and Principal Investigator Details","amendTrial.5.8.html");
P.fA("Amending Sponsor and Summary 4 Details","amendTrial.5.9.html");
P.fA("Amending NIH Grant Details","amendTrial.5.10.html");
P.fA("Amending Trial Status Dates","amendTrial.5.11.html");
P.fA("Amending IND/IDE Details","amendTrial.5.12.html");
P.fA("Uploading Amendment-Specific Documents","amendTrial.5.13.html");
P.fA("Reviewing and Submitting Trial Amendments and Updates","amendTrial.5.14.html");
P.fA("Editing Amended and Updated Details","amendTrial.5.15.html");
P.fA("Printing Amended and Updated Trial Information","amendTrial.5.16.html");
P.fA("Managing Your Account","userAccount.6.1.html");
P.fA("Managing Your User Account Profile","userAccount.6.2.html");
P.fA("Managing Your Password","userAccount.6.3.html");
P.fA("Changing Your Password","userAccount.6.4.html");
P.fA("Resetting Your Password","userAccount.6.5.html");
P.fA("Transferring Trial Ownership","userAccount.6.6.html");
P.fA("Batch Upload Data Specifications","batchUpload.7.1.html");
P.fA("Preparing the Trial Data File for Non-Proprietary Trials","batchUpload.7.2.html");
P.fA("Preparing Trial-Related Documents","batchUpload.7.3.html");
P.fA("Trial Data Element Specifications For Non-Proprietary Trials","batchUpload.7.4.html");
P.fA("Preparing the Trial Data File for Proprietary Trials","batchUpload.7.5.html");
P.fA("Trial Specification Rules For Proprietary Trials","batchUpload.7.6.html");
P.fA("Participating Sites Document\u00a0Specifications","participatingSites.8.1.html");
P.fA("Participating Sites Document Rules","participatingSites.8.2.html");
P.fA("Participating Site Data Element Specifications","participatingSites.8.3.html");
P.fA("Metadata Definitions","metadata.9.1.html");
P.fA("Allocation","metadata.9.2.html");
P.fA("Amendment Number","metadata.9.3.html");
P.fA("Current Trial Status Date","metadata.9.4.html");
P.fA("Funding Mechanism","metadata.9.5.html");
P.fA("Identifier Type","metadata.9.6.html");
P.fA("Institute Code (NIH Grant Code)","metadata.9.7.html");
P.fA("Intervention Model","metadata.9.8.html");
P.fA("Lead Organization","metadata.9.9.html");
P.fA("Lead Organization Trial Identifier (ID)","metadata.9.10.html");
P.fA("Masking","metadata.9.11.html");
P.fA("Milestones","metadata.9.12.html");
P.fA("NCI Division/Program Code","metadata.9.13.html");
P.fA("NCI Trial Identifier","metadata.9.14.html");
P.fA("NIH Grant Information","metadata.9.15.html");
P.fA("Non-proprietary Trial","metadata.9.16.html");
P.fA("Primary Purpose","metadata.9.17.html");
P.fA("Principal Investigator","metadata.9.18.html");
P.fA("Processing Status","metadata.9.19.html");
P.fA("Proprietary Trial","metadata.9.20.html");
P.fA("Responsible Party","metadata.9.21.html");
P.fA("Sponsor","metadata.9.22.html");
P.fA("Study Classification","metadata.9.23.html");
P.fA("Summary 4 Funding Category","metadata.9.24.html");
P.fA("Summary 4 Sponsor/Source","metadata.9.25.html");
P.fA("Title","metadata.9.26.html");
P.fA("Trial Phase","metadata.9.27.html");
P.fA("Trial Status","metadata.9.28.html");
P.fA("Trial Type","metadata.9.29.html");
P.fA("Glossary","Glossary.10.1.html");
P.fA("Application Support","appSupport.11.1.html");
}
