function  WWHBookData_Files(P)
{
P.fA("NCI Clinical Trials Reporting Program Online Help","Welcome.1.1.html");
P.fA("Using the Online Help","Welcome.1.2.html");
P.fA("Using Navigation Tools","Welcome.1.3.html");
P.fA("Getting Started","GettingStarted.2.1.html");
P.fA("About the NCI Clinical Trials Reporting Program","GettingStarted.2.2.html");
P.fA("Registering as a New User","GettingStarted.2.3.html");
P.fA("Logging In to the NCI Clinical Trials Reporting Program","GettingStarted.2.4.html");
P.fA("Searching For Trials","trials.3.1.html");
P.fA("About Clinical Trial Metadata","trials.3.2.html");
P.fA("Searching For Trials","trials.3.3.html");
P.fA("Working with Search Results","trials.3.4.html");
P.fA("Navigating Through the Search Results List","trials.3.5.html");
P.fA("Viewing Trial Details","trials.3.6.html");
P.fA("Viewing Trial-Related Documents","trials.3.7.html");
P.fA("Registering New Trials","register.4.1.html");
P.fA("Registering Trials in the NCI Clinical Trials Reporting Program","register.4.2.html");
P.fA("Completing the Trial Details Section","register.4.3.html");
P.fA("Completing the Lead Organization/Principal Investigator Section","register.4.4.html");
P.fA("Completing the Sponsor/Responsible Party Section","register.4.5.html");
P.fA("Completing the Summary 4 Information Section","register.4.6.html");
P.fA("Completing the NIH Grant Information Section","register.4.7.html");
P.fA("Completing the Status/Dates Section","register.4.8.html");
P.fA("Completing the IND/IDE Information Section","register.4.9.html");
P.fA("Completing the Trial Related Documents Section","register.4.10.html");
P.fA("Registering Organizations","register.4.11.html");
P.fA("Searching for Registered Organizations","register.4.12.html");
P.fA("Adding Organizations","register.4.13.html");
P.fA("Registering Persons","register.4.14.html");
P.fA("Searching for Principal Investigators","register.4.15.html");
P.fA("Adding Principal Investigators","register.4.16.html");
P.fA("Managing Your Account","userAccount.5.1.html");
P.fA("Editing User Information","userAccount.5.2.html");
P.fA("Managing Your Password","userAccount.5.3.html");
P.fA("Changing Your Password","userAccount.5.4.html");
P.fA("Resetting Your Password","userAccount.5.5.html");
P.fA("Metadata Definitions","metadata.6.1.html");
P.fA("Glossary","Glossary.7.1.html");
P.fA("Application Support","appSupport.8.1.html");
}
