package gov.nih.nci.coppa.services.pa.interventionservice.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface InterventionServiceConstantsBase {
	public static final String SERVICE_NS = "http://enterpriseservices.nci.nih.gov/PAServices/InterventionService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "InterventionServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "InterventionServiceResourceProperties");
	
}
