package gov.nih.nci.coppa.po.grid.service.globus;

import gov.nih.nci.coppa.po.grid.service.CoppaPOImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the CoppaPOImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class CoppaPOProviderImpl{
	
	CoppaPOImpl impl;
	
	public CoppaPOProviderImpl() throws RemoteException {
		impl = new CoppaPOImpl();
	}
	

    public gov.nih.nci.coppa.po.grid.stubs.GetPersonResponse getPerson(gov.nih.nci.coppa.po.grid.stubs.GetPersonRequest params) throws RemoteException, gov.nih.nci.coppa.po.grid.stubs.types.NullifiedEntityFault {
    gov.nih.nci.coppa.po.grid.stubs.GetPersonResponse boxedResult = new gov.nih.nci.coppa.po.grid.stubs.GetPersonResponse();
    boxedResult.setPerson(impl.getPerson(params.getIdentifier().getII()));
    return boxedResult;
  }

    public gov.nih.nci.coppa.po.grid.stubs.GetOrganizationResponse getOrganization(gov.nih.nci.coppa.po.grid.stubs.GetOrganizationRequest params) throws RemoteException, gov.nih.nci.coppa.po.grid.stubs.types.NullifiedEntityFault {
    gov.nih.nci.coppa.po.grid.stubs.GetOrganizationResponse boxedResult = new gov.nih.nci.coppa.po.grid.stubs.GetOrganizationResponse();
    boxedResult.setOrganization(impl.getOrganization(params.getIdentifier().getII()));
    return boxedResult;
  }

    public gov.nih.nci.coppa.po.grid.stubs.SearchOrganizationsResponse searchOrganizations(gov.nih.nci.coppa.po.grid.stubs.SearchOrganizationsRequest params) throws RemoteException, gov.nih.nci.coppa.po.grid.stubs.types.NullifiedEntityFault {
    gov.nih.nci.coppa.po.grid.stubs.SearchOrganizationsResponse boxedResult = new gov.nih.nci.coppa.po.grid.stubs.SearchOrganizationsResponse();
    boxedResult.setOrganization(impl.searchOrganizations(params.getOrganization().getOrganization()));
    return boxedResult;
  }

    public gov.nih.nci.coppa.po.grid.stubs.SearchPersonsResponse searchPersons(gov.nih.nci.coppa.po.grid.stubs.SearchPersonsRequest params) throws RemoteException, gov.nih.nci.coppa.po.grid.stubs.types.NullifiedEntityFault {
    gov.nih.nci.coppa.po.grid.stubs.SearchPersonsResponse boxedResult = new gov.nih.nci.coppa.po.grid.stubs.SearchPersonsResponse();
    boxedResult.setPerson(impl.searchPersons(params.getPerson().getPerson()));
    return boxedResult;
  }

    public gov.nih.nci.coppa.po.grid.stubs.EchoPersonResponse echoPerson(gov.nih.nci.coppa.po.grid.stubs.EchoPersonRequest params) throws RemoteException {
    gov.nih.nci.coppa.po.grid.stubs.EchoPersonResponse boxedResult = new gov.nih.nci.coppa.po.grid.stubs.EchoPersonResponse();
    boxedResult.setPerson(impl.echoPerson(params.getPerson().getPerson()));
    return boxedResult;
  }

    public gov.nih.nci.coppa.po.grid.stubs.EchoOrganizationResponse echoOrganization(gov.nih.nci.coppa.po.grid.stubs.EchoOrganizationRequest params) throws RemoteException {
    gov.nih.nci.coppa.po.grid.stubs.EchoOrganizationResponse boxedResult = new gov.nih.nci.coppa.po.grid.stubs.EchoOrganizationResponse();
    boxedResult.setOrganization(impl.echoOrganization(params.getOrganization().getOrganization()));
    return boxedResult;
  }

}
