insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('140','Malignant neoplasm of lip',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('141','Malignant neoplasm of tongue',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('142','Malignant neoplasm of major salivary glands',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('143','Malignant neoplasm of gum',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('144','Malignant neoplasm of floor of mouth',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('145','Malignant neoplasm of other and unspecified parts of mouth',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('146','Malignant neoplasm of oropharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('147','Malignant neoplasm of nasopharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('148','Malignant neoplasm of hypopharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('149','Malignant neoplasm of other and ill-defined sites within the lip, oral cavity, and pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('150','Malignant neoplasm of esophagus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('151','Malignant neoplasm of stomach',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('152','Malignant neoplasm of small intestine, including duodenum',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('153','Malignant neoplasm of colon',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('154','Malignant neoplasm of rectum, rectosigmoid junction, and anus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('155','Malignant neoplasm of liver and intrahepatic bile ducts',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('156','Malignant neoplasm of gallbladder and extrahepatic bile ducts',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('157','Malignant neoplasm of pancreas',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('158','Malignant neoplasm of retroperitoneum and peritoneum',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('159','Malignant neoplasm of other and ill-defined sites within the digestive organs and peritoneum',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('160','Malignant neoplasm of nasal cavities, middle ear, and accessory sinuses',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('161','Malignant neoplasm of larynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('162','Malignant neoplasm of trachea, bronchus, and lung',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('163','Malignant neoplasm of pleura',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('164','Malignant neoplasm of thymus, heart, and mediastinum',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('165','Malignant neoplasm of other and ill-defined sites within the respiratory system and intrathoracic organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('170','Malignant neoplasm of bone and articular cartilage',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('171','Malignant neoplasm of connective and other soft tissue',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('172','Malignant melanoma of skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173','Other and unspecified malignant neoplasm of skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.0','Other malignant neoplasm of skin of lip',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.1','Other and unspecified malignant neoplasm of skin of eyelid, including canthus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.2','Other and unspecified malignant neoplasm of skin of ear and external auditory canal',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.3','Other and unspecified malignant neoplasm of skin of other and unspecified parts of face',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.4','Other and unspecified malignant neoplasm of scalp and skin of neck',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.5','Other and unspecified malignant neoplasm of skin of trunk, except scrotum',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.6','Other and unspecified malignant neoplasm of skin of upper limb, including shoulder',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.7','Other and unspecified malignant neoplasm of skin of lower limb, including hip',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.8','Other and unspecified malignant neoplasm of other specified sites of skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('173.9','Other and unspecified malignant neoplasm of skin, site unspecified',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('174','Malignant neoplasm of female breast',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('175','Malignant neoplasm of male breast',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('176','Kaposi\'s sarcoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('180','Malignant neoplasm of cervix uteri',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('182','Malignant neoplasm of body of uterus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('183','Malignant neoplasm of ovary and other uterine adnexa',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('184','Malignant neoplasm of other and unspecified female genital organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('186','Malignant neoplasm of testis',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('187','Malignant neoplasm of penis and other male genital organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('188','Malignant neoplasm of bladder',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('189','Malignant neoplasm of kidney and other and unspecified urinary organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('190','Malignant neoplasm of eye',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('191','Malignant neoplasm of brain',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('192','Malignant neoplasm of other and unspecified parts of nervous system',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('194','Malignant neoplasm of other endocrine glands and related structures',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('195','Malignant neoplasm of other and ill-defined sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('196','Secondary and unspecified malignant neoplasm of lymph nodes',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('197','Secondary malignant neoplasm of respiratory and digestive systems',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('198','Secondary malignant neoplasm of other specified sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('198.8','Secondary malignant neoplasm of other specified sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('199','Malignant neoplasm without specification of site',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('200','Lymphosarcoma and reticulosarcoma and other specified malignant tumors of lymphatic tissue',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('200.0','Reticulosarcoma',   now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('200.1','Lymphosarcoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('200.2','Burkitt\'s tumor or lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('200.3','Marginal zone lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('200.4','Mantle cell lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('200.5','Primary central nervous system lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('200.6','Anaplastic large cell lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('200.7','Large cell lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('200.8','Other named variants of lymphosarcoma and reticulosarcoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201','Hodgkin\'s disease',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.0','Hodgkin\'s paragranuloma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.1','Hodgkin\'s granuloma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.2','Hodgkin\'s sarcoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.4','Hodgkin\'s disease, lymphocytic-histiocytic predominance',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.5','Hodgkin\'s disease, nodular sclerosis',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.6','Hodgkin\'s disease, mixed cellularity',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.7','Hodgkin\'s disease, lymphocytic depletion',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('201.9','Hodgkin\'s disease, unspecified type',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202','Other malignant neoplasms of lymphoid and histiocytic tissue',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.0','Nodular lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.1','Mycosis fungoides',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.2','Sezary\'s disease',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.3','Malignant histiocytosis',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.4','Leukemic reticuloendotheliosis',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.5','Letterer-Siwe disease',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.6','Malignant mast cell tumors',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.7','Peripheral T-cell lymphoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.8','Other malignant lymphomas',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('202.9','Other and unspecified malignant neoplasms of lymphoid and histiocytic tissue',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('203','Multiple myeloma and immunoproliferative neoplasms',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('203.0','Multiple myeloma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('203.1','Plasma cell leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('203.8','Other immunoproliferative neoplasms',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('204','Lymphoid leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('204.0','Lymphoid leukemia, acute',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('204.1','Lymphoid leukemia, chronic',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('204.2','Lymphoid leukemia, subacute',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('204.8','Other lymphoid leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('204.9','Unspecified lymphoid leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('205','Myeloid leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('205.0','Myeloid leukemia, acute',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('205.1','Myeloid leukemia, chronic',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('205.2','Myeloid leukemia, subacute',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('205.3','Myeloid sarcoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('205.8','Other myeloid leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('205.9','Unspecified myeloid leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('206','Monocytic leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('206.0','Monocytic leukemia, acute',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('206.1','Monocytic leukemia, chronic',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('206.2','Monocytic leukemia, subacute',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('206.8','Other monocytic leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('206.9','Unspecified monocytic leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('207','Other specified leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('207.0','Acute erythremia and erythroleukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('207.1','Chronic erythremia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('207.2','Megakaryocytic leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('207.8','Other specified leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('208','Leukemia of unspecified cell type',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('208.0','Leukemia of unspecified cell type, acute',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('208.1','Leukemia of unspecified cell type, chronic',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('208.2','Leukemia of unspecified cell type, subacute',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('208.8','Other leukemia of unspecified cell type',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('208.9','Unspecified leukemia',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('209','Neuroendocrine tumors',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('209.0','Malignant carcinoid tumors of the small intestine',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('209.1','Malignant carcinoid tumors of the appendix, large intestine, and rectum',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('209.2','Malignant carcinoid tumors of other and unspecified sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('209.3','Malignant poorly differentiated neuroendocrine tumors',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('209.4','Benign carcinoid tumors of the small intestine',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('209.5','Benign carcinoid tumors of the appendix, large intestine, and rectum',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('209.6','Benign carcinoid tumors of other and unspecified sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('209.7','Secondary neuroendocrine tumors',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('210','Benign neoplasm of lip, oral cavity, and pharynx',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('211','Benign neoplasm of other parts of digestive system',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('212','Benign neoplasm of respiratory and intrathoracic organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('213','Benign neoplasm of bone and articular cartilage',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('214','Lipoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('215','Other benign neoplasm of connective and other soft tissue',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('216','Benign neoplasm of skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('218','Uterine leiomyoma',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('219','Other benign neoplasm of uterus',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('221','Benign neoplasm of other female genital organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('222','Benign neoplasm of male genital organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('223','Benign neoplasm of kidney and other urinary organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('223.8','Benign neoplasm of other specified sites of urinary organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('224','Benign neoplasm of eye',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('225','Benign neoplasm of brain and other parts of nervous system',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('227','Benign neoplasm of other endocrine glands and related structures',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('228','Hemangioma and lymphangioma, any site',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('228.0','Hemangioma, any site',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('229','Benign neoplasm of other and unspecified sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('230','Carcinoma in situ of digestive organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('231','Carcinoma in situ of respiratory system',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('232','Carcinoma in situ of skin',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('233','Carcinoma in situ of breast and genitourinary system',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('233.3','Carcinoma in situ of other and unspecified female genital organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('234','Carcinoma in situ of other and unspecified sites',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('235','Neoplasm of uncertain behavior of digestive and respiratory systems',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('236','Neoplasm of uncertain behavior of genitourinary organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('236.9','Neoplasm of uncertain behavior of other and unspecified urinary organs',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('237','Neoplasm of uncertain behavior of endocrine glands and nervous system',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('237.7','Neurofibromatosis',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('238','Neoplasm of uncertain behavior of other and unspecified sites and tissues',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('238.7','Neoplasm of uncertain behavior of other lymphatic and hematopoietic tissues',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('239','Neoplasms of unspecified nature',  now());
insert into ICD9_DISEASE (DISEASE_CODE, NAME, DATE_LAST_CREATED) values('239.8','Neoplasm of unspecified nature of other specified sites',  now());