package gov.nih.nci.coppa.services.structuralroles.clinicalresearchstaff.service;

import gov.nih.nci.coppa.iso.Ii;
import gov.nih.nci.coppa.po.ClinicalResearchStaff;
import gov.nih.nci.coppa.po.grid.dto.transform.IITransformer;
import gov.nih.nci.coppa.po.grid.dto.transform.po.ClinicalResearchStaffTransformer;
import gov.nih.nci.coppa.po.grid.dto.transform.po.faults.FaultUtil;
import gov.nih.nci.coppa.po.grid.remote.InvokeClinicalResearchStaffEjb;
import gov.nih.nci.services.correlation.ClinicalResearchStaffDTO;

import java.rmi.RemoteException;
import java.util.List;

import org.apache.log4j.LogManager;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class ClinicalResearchStaffImpl extends ClinicalResearchStaffImplBase {
    
    private static org.apache.log4j.Logger logger = LogManager.getLogger(ClinicalResearchStaffImpl.class);
    
    private InvokeClinicalResearchStaffEjb clinicalResearchStaffService = new InvokeClinicalResearchStaffEjb();
    
	public ClinicalResearchStaffImpl() throws RemoteException {
		super();
	}
	
  public gov.nih.nci.coppa.po.Id create(gov.nih.nci.coppa.po.ClinicalResearchStaff clinicalResearchStaff) throws RemoteException, gov.nih.nci.coppa.po.faults.EntityValidationFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.po.ClinicalResearchStaff getById(gov.nih.nci.coppa.po.Id id) throws RemoteException, gov.nih.nci.coppa.po.faults.NullifiedRoleFault {
      try {
          Ii ii_iso = IITransformer.INSTANCE.toDto(id);
          ClinicalResearchStaffDTO crs_dto = clinicalResearchStaffService.getClinicalResearchStaff(ii_iso);
          ClinicalResearchStaff clinicalResearchStaff = ClinicalResearchStaffTransformer.INSTANCE.toXml(crs_dto);
          return clinicalResearchStaff;
      } catch (Exception e) {
          logger.error("Error in getting ClinicalResearchStaff.", e);
          throw FaultUtil.reThrowRemote(e);
      }
  }

  public gov.nih.nci.coppa.po.ClinicalResearchStaff[] getByIds(gov.nih.nci.coppa.po.Id[] id) throws RemoteException, gov.nih.nci.coppa.po.faults.NullifiedRoleFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.po.ClinicalResearchStaff[] search(gov.nih.nci.coppa.po.ClinicalResearchStaff clinicalResearchStaff) throws RemoteException {
      try {
          ClinicalResearchStaffDTO crs_iso = ClinicalResearchStaffTransformer.INSTANCE.toDto(clinicalResearchStaff);
          List<ClinicalResearchStaffDTO> results = clinicalResearchStaffService.search(crs_iso);
          if (results == null) {
              return null;
          }
          logger.debug("ClinicalResearchStaff searched from COPPA:" + results.size());
          gov.nih.nci.coppa.po.ClinicalResearchStaff [] returnResults = new gov.nih.nci.coppa.po.ClinicalResearchStaff[results.size()];
          int i = 0;
          for (ClinicalResearchStaffDTO crs_res : results) {
              gov.nih.nci.coppa.po.ClinicalResearchStaff crs_res_tr = ClinicalResearchStaffTransformer.INSTANCE.toXml(crs_res);
              returnResults[i++] = crs_res_tr;
          }
          return returnResults;
      } catch (Exception e) {
          logger.error("Error in searching ClinicalResearchStaff.", e);
          throw FaultUtil.reThrowRemote(e);
      }
  }

  public void update(gov.nih.nci.coppa.po.ClinicalResearchStaff clinicalResearchStaff) throws RemoteException, gov.nih.nci.coppa.po.faults.EntityValidationFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void updateStatus(gov.nih.nci.coppa.po.Id targetId,gov.nih.nci.coppa.po.Cd statusCode) throws RemoteException, gov.nih.nci.coppa.po.faults.EntityValidationFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.po.StringMap validate(gov.nih.nci.coppa.po.ClinicalResearchStaff clinicalResearchStaff) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }
}

