package gov.nih.nci.coppa.services.pa.documentworkflowstatusservice.service;

import gov.nih.nci.coppa.services.pa.DocumentWorkflowStatus;
import gov.nih.nci.coppa.services.pa.grid.GenericStudyCurrentPaGridServiceImpl;
import gov.nih.nci.pa.iso.dto.DocumentWorkflowStatusDTO;

import java.rmi.RemoteException;

/**
 * Implementation of the DocumentWorkflowStatusService. Dispatches to the remote EJBs and the Transformers.
 *
 * @author Hugh Reinhart
 */
public class DocumentWorkflowStatusServiceImpl extends DocumentWorkflowStatusServiceImplBase {

    public DocumentWorkflowStatusServiceImpl() throws RemoteException {
        super();
    }

    private final GenericStudyCurrentPaGridServiceImpl<DocumentWorkflowStatusDTO, DocumentWorkflowStatus> impl
            = new GenericStudyCurrentPaGridServiceImpl<DocumentWorkflowStatusDTO,
                DocumentWorkflowStatus>(DocumentWorkflowStatus.class, DocumentWorkflowStatusDTO.class);

  public gov.nih.nci.coppa.services.pa.DocumentWorkflowStatus get(gov.nih.nci.coppa.services.pa.Id id) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
        return impl.get(id);
    }

  public gov.nih.nci.coppa.services.pa.DocumentWorkflowStatus getCurrentByStudyProtocol(gov.nih.nci.coppa.services.pa.Id id) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
        return impl.getCurrentByStudyProtocol(id);
    }

  public gov.nih.nci.coppa.services.pa.DocumentWorkflowStatus[] getByStudyProtocol(gov.nih.nci.coppa.services.pa.Id id) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
        return impl.getByStudyProtocol(id);
    }

  public void copy(gov.nih.nci.coppa.services.pa.Id fromStudyProtocolId,gov.nih.nci.coppa.services.pa.Id toStudyProtocolId) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.pa.DocumentWorkflowStatus create(gov.nih.nci.coppa.services.pa.DocumentWorkflowStatus documentWorkflowStatus) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.pa.DocumentWorkflowStatus update(gov.nih.nci.coppa.services.pa.DocumentWorkflowStatus documentWorkflowStatus) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void delete(gov.nih.nci.coppa.services.pa.Id id) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

