function FileData_Pairs(x)
{
x.t("managing","user");
x.t("managing","account");
x.t("instructions","modifying");
x.t("user","account");
x.t("resetting","account");
x.t("includes","following");
x.t("account","managing");
x.t("account","profile");
x.t("account","section");
x.t("provides","instructions");
x.t("profile","changing");
x.t("modifying","ctrp");
x.t("viewer","account");
x.t("section","includes");
x.t("section","provides");
x.t("changing","password");
x.t("ctrp","viewer");
x.t("topics","managing");
x.t("following","topics");
x.t("password","resetting");
}
