function FileData_Pairs(x)
{
x.t("open","save");
x.t("want","export");
x.t("enables","export");
x.t("excel","file");
x.t("excel","spreadsheets");
x.t("excel","prompted");
x.t("next","export");
x.t("options","click");
x.t("reporting","exporting");
x.t("viewer","enables");
x.t("spreadsheets","export");
x.t("report","next");
x.t("report","data");
x.t("report","contains");
x.t("reports","excel");
x.t("click","excel");
x.t("prompted","open");
x.t("exporting","report");
x.t("data","reports");
x.t("data","exporting");
x.t("data","ctro");
x.t("data","ctrp");
x.t("data","run");
x.t("save","excel");
x.t("ctro","reporting");
x.t("ctrp","viewer");
x.t("export","options");
x.t("export","report");
x.t("export","data");
x.t("export","bottom");
x.t("run","report");
x.t("bottom","report");
x.t("statistics","want");
x.t("contains","statistics");
}
