function FileData_Pairs(x)
{
x.t("summary","funding");
x.t("categories","summary");
x.t("includes","following");
x.t("trial","categories");
x.t("trial","statuses");
x.t("trial","identifier");
x.t("trial","phase");
x.t("hoc","report");
x.t("provides","valid");
x.t("search","criteria");
x.t("statuses","trial");
x.t("statuses","intervention");
x.t("funding","category");
x.t("processing","statuses");
x.t("report","search");
x.t("report","criteria");
x.t("section","includes");
x.t("section","provides");
x.t("types","trial");
x.t("types","processing");
x.t("identifier","types");
x.t("valid","values");
x.t("intervention","types");
x.t("values","trial");
x.t("values","hoc");
x.t("values","section");
x.t("values","definitions");
x.t("phase","values");
x.t("topics","trial");
x.t("following","topics");
x.t("criteria","section");
x.t("criteria","values");
x.t("definitions","hoc");
x.t("category","milestones");
}
