function FileData_Pairs(x)
{
x.t("example","vitamins");
x.t("example","psychotherapy");
x.t("recombinant","dna");
x.t("drug","device");
x.t("dietary","supplement");
x.t("biological/vaccine","procedure/surgery");
x.t("genetic","including");
x.t("dna","dietary");
x.t("behavioral","example");
x.t("gene","transfer");
x.t("hoc","report");
x.t("follows","intervention");
x.t("lifestyle","counseling");
x.t("counseling","genetic");
x.t("device","including");
x.t("cell","recombinant");
x.t("sham","biological/vaccine");
x.t("stem","cell");
x.t("report","criteria");
x.t("types","drug");
x.t("types","hoc");
x.t("types","follows");
x.t("types","valid");
x.t("types","intervention");
x.t("procedure/surgery","radiation");
x.t("radiation","behavioral");
x.t("valid","values");
x.t("intervention","types");
x.t("transfer","stem");
x.t("values","intervention");
x.t("supplement","example");
x.t("vitamins","minerals");
x.t("criteria","values");
x.t("including","gene");
x.t("including","sham");
x.t("psychotherapy","lifestyle");
}
