function FileData_Pairs(x)
{
x.t("version","ctrp");
x.t("trials","ctrp");
x.t("create","reports");
x.t("summary","type");
x.t("type","report");
x.t("what\u2019s","new");
x.t("new","features");
x.t("new","release");
x.t("getting","started");
x.t("organization","search");
x.t("organization","family");
x.t("features","hoc");
x.t("name","organization");
x.t("hoc","reports");
x.t("search","family");
x.t("search","criteria");
x.t("started","what\u2019s");
x.t("family","summary");
x.t("family","belongs");
x.t("select","name");
x.t("viewer","following");
x.t("report","select");
x.t("release","version");
x.t("release","what\u2019s");
x.t("release","getting");
x.t("reports","create");
x.t("reports","interventional");
x.t("pre-defined","search");
x.t("ctrp","viewer");
x.t("ctrp","system");
x.t("following","new");
x.t("system","pre-defined");
x.t("interventional","trials");
x.t("criteria","organization");
}
