function FileData_Pairs(x)
{
x.t("trials","reporting");
x.t("instructions","registering");
x.t("program","trial");
x.t("getting","started");
x.t("includes","following");
x.t("trial","viewer");
x.t("registering","account");
x.t("account","logging");
x.t("creating","account");
x.t("logging","ctrp");
x.t("logging","system");
x.t("introduces","nci");
x.t("provides","instructions");
x.t("started","getting");
x.t("started","section");
x.t("reporting","program");
x.t("viewer","creating");
x.t("viewer","provides");
x.t("viewer","ctrp");
x.t("section","includes");
x.t("section","introduces");
x.t("ctrp","viewer");
x.t("nci","clinical");
x.t("topics","ctrp");
x.t("system","section");
x.t("following","topics");
x.t("clinical","trials");
}
