function FileData_Pairs(x)
{
x.t("abstraction","process");
x.t("describes","run");
x.t("instructions","exporting");
x.t("includes","following");
x.t("performance","protocol");
x.t("provides","instructions");
x.t("excel","spreadsheets");
x.t("queries","generate");
x.t("reporting","section");
x.t("reporting","running");
x.t("reporting","ctro");
x.t("spreadsheets","section");
x.t("report","data");
x.t("section","describes");
x.t("section","includes");
x.t("reports","enable");
x.t("reports","exporting");
x.t("enable","monitor");
x.t("pre-defined","queries");
x.t("exporting","report");
x.t("running","ctro");
x.t("assess","performance");
x.t("generate","reports");
x.t("process","provides");
x.t("data","excel");
x.t("ctro","reporting");
x.t("ctro","reports");
x.t("monitor","assess");
x.t("protocol","abstraction");
x.t("topics","ctro");
x.t("run","pre-defined");
x.t("following","topics");
}
