function FileData_Pairs(x)
{
x.t("describes","run");
x.t("submission","processing");
x.t("instructions","exporting");
x.t("includes","following");
x.t("trial","submission");
x.t("provides","instructions");
x.t("excel","spreadsheets");
x.t("queries","generate");
x.t("processing","provides");
x.t("reporting","section");
x.t("reporting","running");
x.t("reporting","ctro");
x.t("spreadsheets","section");
x.t("report","data");
x.t("section","describes");
x.t("section","includes");
x.t("reports","enable");
x.t("reports","exporting");
x.t("enable","monitor");
x.t("pre-defined","queries");
x.t("exporting","report");
x.t("running","ctro");
x.t("generate","reports");
x.t("data","excel");
x.t("ctro","reporting");
x.t("ctro","reports");
x.t("monitor","trial");
x.t("topics","ctro");
x.t("run","pre-defined");
x.t("following","topics");
}
