DROP TABLE IF EXISTS STUDY_RELATIONSHIP;

CREATE TABLE STUDY_RELATIONSHIP (
    IDENTIFIER SERIAL NOT NULL,
    TYPE_CODE VARCHAR(200) NOT NULL,
    DESCRIPTION_TEXT VARCHAR(1000), 
    COMMENT_TEXT VARCHAR(200),
    SEQUENCE_NUMBER INTEGER , 
    SOURCE_STUDY_PROTOCOL_IDENTIFIER BIGINT NOT NULL,   -- NEW ONE
    TARGET_STUDY_PROTOCOL_IDENTFIER BIGINT NOT NULL,  -- parent , from 
    DATE_LAST_CREATED TIMESTAMP,
    USER_LAST_CREATED VARCHAR(200) ,
    DATE_LAST_UPDATED TIMESTAMP,
    USER_LAST_UPDATED VARCHAR(200) ,
    PRIMARY KEY (IDENTIFIER)
) ;
