ALTER TABLE STUDY_PROTOCOL ADD COLUMN PRIMARY_OBJECTIVE VARCHAR(2400),
  	ADD COLUMN SECONDARY_OBJECTIVE VARCHAR(2400),
  	ADD COLUMN TERNARY_OBJECTIVE VARCHAR(2400),
  	ADD COLUMN OUTLINE VARCHAR(2400),
  	ADD COLUMN PROJECTED_ACCURAL VARCHAR(2400),
	ADD COLUMN STATUS_CODE VARCHAR(50),
	ADD COLUMN STATUS_DATE TIMESTAMP,
	ADD COLUMN AMENDMENT_NUMBER VARCHAR(200),
	ADD COLUMN AMENDMENT_DATE TIMESTAMP,
	ADD COLUMN AMENDMENT_REASON_CODE VARCHAR(50),
	ADD COLUMN SUBMISSION_NUMBER INTEGER,
	ADD COLUMN PARENT_PROTOCOL_IDENTIFIER VARCHAR(200);
  	
	