function FileData_Pairs(x)
{
x.t("deleting","existing");
x.t("deleting","patient");
x.t("treatment","plan");
x.t("instructions","working");
x.t("working","treatment");
x.t("working","patient");
x.t("working","outcomes");
x.t("overview","instructions");
x.t("provides","overview");
x.t("updating","deleting");
x.t("updating","patient");
x.t("records","deleting");
x.t("submitting","updating");
x.t("outcome","information");
x.t("outcome","data");
x.t("existing","patient");
x.t("chaptersection","provides");
x.t("chaptersection","include");
x.t("include","baseline");
x.t("baseline","data");
x.t("plan","data");
x.t("information","including");
x.t("data","working");
x.t("data","topics");
x.t("patient","records");
x.t("patient","outcome");
x.t("patient","outcomes");
x.t("topics","chaptersection");
x.t("outcomes","working");
x.t("outcomes","updating");
x.t("outcomes","chaptersection");
x.t("including","submitting");
}
