function FileData_Pairs(x)
{
x.t("right","corner");
x.t("getting","started");
x.t("upper","right");
x.t("corner","page");
x.t("logged","outcomes");
x.t("logging","nci");
x.t("session","log");
x.t("welcome","page");
x.t("started","logging");
x.t("portal","getting");
x.t("portal","logging");
x.t("portal","finished");
x.t("portal","following");
x.t("portal","log");
x.t("returned","welcome");
x.t("finished","session");
x.t("click","log");
x.t("page","click");
x.t("pane","click");
x.t("nci","outcomes");
x.t("navigation","pane");
x.t("following","navigation");
x.t("outcomes","portal");
x.t("outcomes","returned");
x.t("log","upper");
x.t("log","logged");
x.t("log","nci");
}
