function FileData_Pairs(x)
{
x.t("treatment","regimen");
x.t("treatment","data");
x.t("create","select");
x.t("refer","adding");
x.t("instructions","drug/biologics");
x.t("dosing","details");
x.t("working","treatment");
x.t("details","refer");
x.t("includes","intervention");
x.t("regimen","cycle");
x.t("regimen","records");
x.t("cycle","records");
x.t("cycle","order");
x.t("name","dosing");
x.t("records","instructions");
x.t("records","adding");
x.t("select","treatment");
x.t("submitting","drug/biologics");
x.t("drug/biologics","data");
x.t("intervention","details");
x.t("intervention","name");
x.t("data","create");
x.t("data","working");
x.t("data","includes");
x.t("data","submitting");
x.t("submit","intervention");
x.t("order","submit");
x.t("adding","treatment");
x.t("adding","cycle");
}
