function FileData_Pairs(x)
{
x.t("instructions","registering");
x.t("user","account");
x.t("getting","started");
x.t("overview","instructions");
x.t("overview","nci");
x.t("registering","user");
x.t("account","logging");
x.t("creating","account");
x.t("logging","portal");
x.t("logging","nci");
x.t("provides","overview");
x.t("started","getting");
x.t("started","chaptersection");
x.t("portal","creating");
x.t("portal","topics");
x.t("chaptersection","provides");
x.t("chaptersection","include");
x.t("include","overview");
x.t("topics","chaptersection");
x.t("nci","outcomes");
x.t("outcomes","portal");
}
