function FileData_Pairs(x)
{
x.t("treatment","click");
x.t("treatment","data");
x.t("working","treatment");
x.t("icon","follow");
x.t("edit","icon");
x.t("edit","column");
x.t("updating","surgery");
x.t("record","click");
x.t("appears","edit");
x.t("submitting","surgery");
x.t("follow","steps");
x.t("steps","submitting");
x.t("click","edit");
x.t("click","surgery");
x.t("surgery","appears");
x.t("surgery","surgery");
x.t("surgery","data");
x.t("data","working");
x.t("data","updating");
x.t("data","submitting");
x.t("data","navigation");
x.t("data","update");
x.t("appropriate","record");
x.t("pane","treatment");
x.t("column","appropriate");
x.t("navigation","pane");
x.t("update","surgery");
}
