function FileData_Pairs(x)
{
x.t("right","corner");
x.t("\u03b7\u03bf\u03c9","log");
x.t("related","topics");
x.t("getting","started");
x.t("upper","right");
x.t("corner","page");
x.t("logged","returned");
x.t("overview","nci");
x.t("logging","getting");
x.t("logging","logging");
x.t("logging","nci");
x.t("logging","log");
x.t("session","\u03b7\u03bf\u03c9");
x.t("welcome","page");
x.t("started","logging");
x.t("portal","logging");
x.t("returned","welcome");
x.t("finished","session");
x.t("click","log");
x.t("page","related");
x.t("page","click");
x.t("pane","click");
x.t("topics","overview");
x.t("nci","outcomes");
x.t("navigation","pane");
x.t("following","navigation");
x.t("outcomes","portal");
x.t("log","upper");
x.t("log","logged");
x.t("log","finished");
x.t("log","following");
}
