function FileData_Pairs(x)
{
x.t("searching","adding");
x.t("available","query");
x.t("deleting","patient");
x.t("icon","patient");
x.t("delete","icon");
x.t("delete","delete");
x.t("delete","patient");
x.t("delete","column");
x.t("want","delete");
x.t("list","patients");
x.t("navigate","patient");
x.t("records","searching");
x.t("records","deleting");
x.t("records","delete");
x.t("record","want");
x.t("record","list");
x.t("record","longer");
x.t("record","deleted");
x.t("patients","deleting");
x.t("patients","navigate");
x.t("outcome","data");
x.t("click","delete");
x.t("longer","available");
x.t("data","record");
x.t("query","update");
x.t("patient","records");
x.t("patient","record");
x.t("patient","outcome");
x.t("column","click");
x.t("adding","patients");
x.t("deleted","permanently");
x.t("update","delete");
}
