function FileData_Pairs(x)
{
x.t("treatment","regimen");
x.t("treatment","data");
x.t("create","select");
x.t("refer","adding");
x.t("instructions","radiation");
x.t("dosing","details");
x.t("working","treatment");
x.t("type","dosing");
x.t("details","refer");
x.t("includes","radiation");
x.t("regimen","cycle");
x.t("regimen","records");
x.t("cycle","records");
x.t("cycle","record");
x.t("records","instructions");
x.t("records","adding");
x.t("record","order");
x.t("select","treatment");
x.t("submitting","radiation");
x.t("radiation","type");
x.t("radiation","data");
x.t("intervention","details");
x.t("data","create");
x.t("data","working");
x.t("data","includes");
x.t("data","submitting");
x.t("submit","intervention");
x.t("order","submit");
x.t("adding","treatment");
x.t("adding","cycle");
}
