function FileData_Pairs(x)
{
x.t("searching","patients");
x.t("searching","adding");
x.t("describes","search");
x.t("deleting","patient");
x.t("working","search");
x.t("includes","following");
x.t("results","viewing");
x.t("updating","patient");
x.t("search","results");
x.t("search","existing");
x.t("records","deleting");
x.t("patients","searching");
x.t("patients","working");
x.t("patients","chaptersection");
x.t("viewing","existing");
x.t("existing","patient");
x.t("existing","outcomes");
x.t("chaptersection","describes");
x.t("chaptersection","includes");
x.t("information","chaptersection");
x.t("data","searching");
x.t("data","updating");
x.t("patient","records");
x.t("patient","data");
x.t("topics","patient");
x.t("following","topics");
x.t("adding","patients");
x.t("outcomes","information");
}
