function FileData_Pairs(x)
{
x.t("persons","registered");
x.t("trials","reporting");
x.t("describes","look");
x.t("topic","looking");
x.t("program","(ctrp)");
x.t("working","organization");
x.t("look","select");
x.t("includes","following");
x.t("organization","records");
x.t("looking","registered");
x.t("records","working");
x.t("records","chaptersection");
x.t("(ctrp)","section");
x.t("registered","organizations");
x.t("registered","clinical");
x.t("select","organizations");
x.t("reporting","program");
x.t("section","includes");
x.t("organizations","persons");
x.t("organizations","page");
x.t("chaptersection","describes");
x.t("following","topic");
x.t("clinical","trials");
}
