function FileData_Pairs(x)
{
x.t("searching","adding");
x.t("treatment","outcome");
x.t("create","patient");
x.t("access","via");
x.t("holder","search");
x.t("via","nci");
x.t("account","holder");
x.t("records","access");
x.t("search","review");
x.t("patients","patient");
x.t("contain","demographic");
x.t("portal","contain");
x.t("review","create");
x.t("demographic","baseline");
x.t("outcome","data");
x.t("baseline","treatment");
x.t("data","searching");
x.t("data","patient");
x.t("data","outcomes");
x.t("patient","records");
x.t("patient","data");
x.t("nci","outcomes");
x.t("adding","patients");
x.t("outcomes","account");
x.t("outcomes","portal");
}
