function FileData_Pairs(x)
{
x.t("treatment","regimen");
x.t("treatment","records");
x.t("treatment","plan");
x.t("treatment","data");
x.t("deleting","existing");
x.t("instructions","working");
x.t("off-treatment","data");
x.t("working","treatment");
x.t("regimen","information");
x.t("regimen","data");
x.t("cycle","data");
x.t("provides","instructions");
x.t("updating","deleting");
x.t("records","topics");
x.t("section","provides");
x.t("section","include");
x.t("submitting","treatment");
x.t("submitting","off-treatment");
x.t("submitting","cycle");
x.t("submitting","updating");
x.t("submitting","drug/biologics");
x.t("submitting","radiation");
x.t("submitting","surgery");
x.t("drug/biologics","data");
x.t("existing","patient");
x.t("include","submitting");
x.t("plan","data");
x.t("radiation","data");
x.t("surgery","data");
x.t("data","working");
x.t("data","section");
x.t("data","submitting");
x.t("information","including");
x.t("patient","treatment");
x.t("topics","section");
x.t("including","submitting");
}
