function FileData_Pairs(x)
{
x.t("instructions","registering");
x.t("user","account");
x.t("getting","started");
x.t("overview","nci");
x.t("registering","user");
x.t("account","logging");
x.t("creating","account");
x.t("logging","portal");
x.t("logging","nci");
x.t("provides","overview");
x.t("started","getting");
x.t("started","section");
x.t("portal","creating");
x.t("portal","topics");
x.t("portal","(outcomes)");
x.t("section","provides");
x.t("section","include");
x.t("include","overview");
x.t("nci","outcomes");
x.t("topics","section");
x.t("(outcomes)","instructions");
x.t("outcomes","portal");
}
