function FileData_Pairs(x)
{
x.t("treatment","regimen");
x.t("treatment","data");
x.t("treatment","regimens");
x.t("create","treatment");
x.t("refer","adding");
x.t("instructions","drug/biologics");
x.t("dosing","details");
x.t("working","treatment");
x.t("details","refer");
x.t("includes","intervention");
x.t("regimen","submit");
x.t("cycle","information");
x.t("cycle","data");
x.t("name","dosing");
x.t("submitting","cycle");
x.t("submitting","drug/biologics");
x.t("drug/biologics","data");
x.t("intervention","details");
x.t("intervention","name");
x.t("data","create");
x.t("data","instructions");
x.t("data","working");
x.t("data","includes");
x.t("data","submitting");
x.t("information","order");
x.t("regimens","submitting");
x.t("submit","cycle");
x.t("submit","intervention");
x.t("order","submit");
x.t("adding","treatment");
}
