function FileData_Pairs(x)
{
x.t("deleting","lesion");
x.t("permanently","deleted");
x.t("working","outcome");
x.t("icon","record");
x.t("delete","icon");
x.t("delete","record");
x.t("assement","records");
x.t("records","deleting");
x.t("records","working");
x.t("records","delete");
x.t("record","permanently");
x.t("record","click");
x.t("assessment","data");
x.t("submitting","lesion");
x.t("outcome","data");
x.t("click","delete");
x.t("lesion","assement");
x.t("lesion","assessment");
x.t("lesion","assesment");
x.t("data","submitting");
x.t("data","adding");
x.t("adding","lesion");
x.t("assesment","records");
}
