function FileData_Pairs(x)
{
x.t("treatment","regimen");
x.t("treatment","data");
x.t("treatment","regimens");
x.t("create","treatment");
x.t("refer","adding");
x.t("instructions","surgery");
x.t("surgical","procedure");
x.t("working","treatment");
x.t("details","refer");
x.t("includes","surgical");
x.t("regimen","submit");
x.t("cycle","information");
x.t("cycle","data");
x.t("name","date");
x.t("submitting","cycle");
x.t("submitting","surgery");
x.t("surgery","data");
x.t("surgery","information");
x.t("intervention","details");
x.t("data","create");
x.t("data","instructions");
x.t("data","working");
x.t("data","submitting");
x.t("information","includes");
x.t("information","order");
x.t("regimens","submitting");
x.t("submit","cycle");
x.t("submit","intervention");
x.t("procedure","name");
x.t("date","surgery");
x.t("order","submit");
x.t("adding","treatment");
}
