function FileData_Pairs(x)
{
x.t("treatment","regimen");
x.t("treatment","data");
x.t("create","select");
x.t("refer","adding");
x.t("instructions","surgery");
x.t("surgical","procedure");
x.t("working","treatment");
x.t("details","refer");
x.t("includes","surgical");
x.t("regimen","cycle");
x.t("regimen","records");
x.t("cycle","records");
x.t("cycle","record");
x.t("name","date");
x.t("records","instructions");
x.t("records","adding");
x.t("record","order");
x.t("select","treatment");
x.t("submitting","surgery");
x.t("surgery","data");
x.t("surgery","information");
x.t("intervention","details");
x.t("data","create");
x.t("data","working");
x.t("data","submitting");
x.t("information","includes");
x.t("submit","intervention");
x.t("procedure","name");
x.t("date","surgery");
x.t("order","submit");
x.t("adding","treatment");
x.t("adding","cycle");
}
