function FileData_Pairs(x)
{
x.t("treatment","regimen");
x.t("treatment","click");
x.t("treatment","plan");
x.t("treatment","data");
x.t("working","treatment");
x.t("icon","follow");
x.t("regimen","treatment");
x.t("regimen","records");
x.t("regimen","data");
x.t("edit","icon");
x.t("edit","column");
x.t("updating","treatment");
x.t("records","working");
x.t("records","updating");
x.t("records","navigation");
x.t("records","update");
x.t("record","click");
x.t("appears","edit");
x.t("submitting","treatment");
x.t("follow","steps");
x.t("steps","submitting");
x.t("click","treatment");
x.t("click","edit");
x.t("plan","page");
x.t("page","appears");
x.t("data","updating");
x.t("data","submitting");
x.t("appropriate","record");
x.t("pane","treatment");
x.t("column","appropriate");
x.t("navigation","pane");
x.t("update","treatment");
}
