function FileData_Pairs(x)
{
x.t("searching","patients");
x.t("searching","adding");
x.t("treatment","outcome");
x.t("create","patient");
x.t("related","topics");
x.t("access","via");
x.t("holder","search");
x.t("via","contain");
x.t("account","holder");
x.t("account","viewing");
x.t("creating","account");
x.t("records","related");
x.t("records","access");
x.t("search","review");
x.t("patients","creating");
x.t("patients","patient");
x.t("contain","demographic");
x.t("review","create");
x.t("demographic","baseline");
x.t("viewing","existing");
x.t("outcome","data");
x.t("existing","patient");
x.t("baseline","treatment");
x.t("data","searching");
x.t("data","account");
x.t("data","patient");
x.t("patient","records");
x.t("patient","data");
x.t("topics","searching");
x.t("adding","patients");
}
