function FileData_Pairs(x)
{
x.t("searching","patients");
x.t("searching","existing");
x.t("searching","adding");
x.t("deleting","patient");
x.t("instructions","searching");
x.t("working","search");
x.t("new","patient");
x.t("details","updating");
x.t("includes","following");
x.t("results","viewing");
x.t("provides","instructions");
x.t("updating","patient");
x.t("records","deleting");
x.t("records","nci");
x.t("search","results");
x.t("patients","searching");
x.t("patients","working");
x.t("patients","section");
x.t("portal","section");
x.t("viewing","existing");
x.t("section","includes");
x.t("section","provides");
x.t("existing","patient");
x.t("information","adding");
x.t("data","searching");
x.t("patient","details");
x.t("patient","records");
x.t("patient","information");
x.t("patient","data");
x.t("nci","outcomes");
x.t("topics","patient");
x.t("following","topics");
x.t("adding","new");
x.t("adding","patients");
x.t("outcomes","portal");
}
