function FileData_Pairs(x)
{
x.t("available","query");
x.t("deleting","patient");
x.t("once","deleted");
x.t("working","patient");
x.t("icon","patient");
x.t("delete","icon");
x.t("delete","delete");
x.t("delete","patient");
x.t("delete","column");
x.t("want","delete");
x.t("list","patients");
x.t("navigate","patient");
x.t("enables","delete");
x.t("previously","once");
x.t("records","deleting");
x.t("records","working");
x.t("records","list");
x.t("records","submitted");
x.t("records","outcomes");
x.t("record","want");
x.t("record","longer");
x.t("record","deleted");
x.t("patients","navigate");
x.t("click","delete");
x.t("longer","available");
x.t("query","update");
x.t("patient","records");
x.t("patient","record");
x.t("submitted","previously");
x.t("column","click");
x.t("outcomes","enables");
x.t("deleted","permanently");
x.t("deleted","patient");
x.t("update","delete");
}
