function FileData_Pairs(x)
{
x.t("searching","adding");
x.t("deleting","patient");
x.t("once","patient");
x.t("records","searching");
x.t("records","deleting");
x.t("records","enable");
x.t("record","once");
x.t("record","removed");
x.t("patients","deleting");
x.t("logical","deletion");
x.t("accessible","query");
x.t("enable","logical");
x.t("outcome","data");
x.t("longer","accessible");
x.t("deletion","patient");
x.t("data","record");
x.t("query","update");
x.t("patient","records");
x.t("patient","record");
x.t("patient","outcome");
x.t("adding","patients");
x.t("removed","longer");
}
