function FileData_Pairs(x)
{
x.t("treatment","regimen");
x.t("treatment","data");
x.t("treatment","regimens");
x.t("description","regimen");
x.t("create","treatment");
x.t("refer","adding");
x.t("once","submitted");
x.t("working","treatment");
x.t("details","refer");
x.t("includes","treatment");
x.t("top","page");
x.t("regimen","once");
x.t("regimen","name");
x.t("regimen","data");
x.t("regimen","submit");
x.t("cycle","information");
x.t("cycle","data");
x.t("name","description");
x.t("submitting","treatment");
x.t("submitting","cycle");
x.t("displayed","top");
x.t("page","create");
x.t("intervention","details");
x.t("data","treatment");
x.t("data","instructions");
x.t("data","working");
x.t("data","includes");
x.t("data","submitting");
x.t("information","displayed");
x.t("information","order");
x.t("regimens","submitting");
x.t("submit","cycle");
x.t("submit","intervention");
x.t("submitted","information");
x.t("order","submit");
x.t("adding","treatment");
}
