function FileData_Pairs(x)
{
x.t("lists","existing");
x.t("treatment","modified");
x.t("course","treatment");
x.t("current","assessment");
x.t("working","outcome");
x.t("modified","deleted");
x.t("new","lesion");
x.t("creating","new");
x.t("records","applicable");
x.t("record","throughout");
x.t("record","adding");
x.t("record","contains");
x.t("assessment","records");
x.t("assessment","record");
x.t("assessment","page");
x.t("assessment","data");
x.t("may","record");
x.t("submitting","lesion");
x.t("outcome","data");
x.t("throughout","course");
x.t("existing","assessment");
x.t("page","lists");
x.t("applicable","patient");
x.t("lesion","assessment");
x.t("data","working");
x.t("data","submitting");
x.t("data","lesion");
x.t("data","update");
x.t("information","creating");
x.t("patient","may");
x.t("deleted","record");
x.t("adding","lesion");
x.t("contains","current");
x.t("update","information");
}
