function FileData_Pairs(x)
{
x.t("patient's","outcomes");
x.t("treatment","includes");
x.t("treatment","e.g");
x.t("periodically","during");
x.t("working","outcome");
x.t("assessments","require");
x.t("obtained","periodically");
x.t("pre-specified","number");
x.t("multiple","disease");
x.t("require","updating");
x.t("includes","multiple");
x.t("during","treatment");
x.t("disease","assessments");
x.t("updating","existing");
x.t("records","typically");
x.t("number","courses");
x.t("end","pre-specified");
x.t("outcome","records");
x.t("outcome","data");
x.t("e.g","end");
x.t("existing","patient's");
x.t("courses","treatment");
x.t("data","working");
x.t("data","repository");
x.t("data","outcome");
x.t("data","data");
x.t("typically","obtained");
x.t("outcomes","data");
}
