function FileData_Pairs(x)
{
x.t("treatment","click");
x.t("treatment","data");
x.t("working","treatment");
x.t("icon","follow");
x.t("drug/biologic","drug/biologic");
x.t("drug/biologic","page");
x.t("drug/biologic","data");
x.t("edit","icon");
x.t("edit","column");
x.t("updating","drug/biologic");
x.t("record","click");
x.t("appears","edit");
x.t("submitting","drug/biologics");
x.t("follow","steps");
x.t("steps","submitting");
x.t("drug/biologics","data");
x.t("click","drug/biologic");
x.t("click","edit");
x.t("page","appears");
x.t("data","working");
x.t("data","updating");
x.t("data","submitting");
x.t("data","navigation");
x.t("data","update");
x.t("appropriate","record");
x.t("pane","treatment");
x.t("column","appropriate");
x.t("navigation","pane");
x.t("update","drug/biologic");
}
