function FileData_Pairs(x)
{
x.t("abstraction","getting");
x.t("abstraction","logging");
x.t("abstraction","returned");
x.t("abstraction","following");
x.t("abstraction","log");
x.t("right","corner");
x.t("getting","started");
x.t("link","logged");
x.t("upper","right");
x.t("corner","page");
x.t("logged","protocol");
x.t("logging","protocol");
x.t("welcome","page");
x.t("started","logging");
x.t("returned","welcome");
x.t("click","logout");
x.t("page","click");
x.t("pane","click");
x.t("protocol","abstraction");
x.t("navigation","pane");
x.t("following","navigation");
x.t("logout","link");
x.t("logout","upper");
x.t("log","protocol");
}
