function FileData_Pairs(x)
{
x.t("abstraction","abstract");
x.t("trials","trial");
x.t("trials","future");
x.t("observational","trials");
x.t("current","release");
x.t("scientific","data");
x.t("releases","accommodate");
x.t("details","trial");
x.t("details","outcome");
x.t("includes","following");
x.t("trial","design");
x.t("trial","eligibility");
x.t("abstracting","scientific");
x.t("abstracting","interventional");
x.t("design","current");
x.t("design","details");
x.t("design","includes");
x.t("design","abstracting");
x.t("release","protocol");
x.t("abstract","interventional");
x.t("outcome","measures");
x.t("accommodate","observational");
x.t("eligibility","criteria");
x.t("data","abstracting");
x.t("future","releases");
x.t("protocol","abstraction");
x.t("following","details");
x.t("interventional","trials");
x.t("interventional","trial");
x.t("measures","trial");
}
