package gov.nih.nci.coppa.services.outcomes.activityrelationship.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.ActivityRelationshipPortType;
import gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.service.ActivityRelationshipServiceAddressingLocator;
import gov.nih.nci.coppa.services.outcomes.activityrelationship.common.ActivityRelationshipI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE ACCESS METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.3
 */
public class ActivityRelationshipClient extends ActivityRelationshipClientBase implements ActivityRelationshipI {	

	public ActivityRelationshipClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public ActivityRelationshipClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	}
	
	public ActivityRelationshipClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public ActivityRelationshipClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
	}

	public static void usage(){
		System.out.println(ActivityRelationshipClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  ActivityRelationshipClient client = new ActivityRelationshipClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

  public gov.nih.nci.coppa.services.outcomes.ActivityRelationship[] getByTargetPerformedActivity(gov.nih.nci.coppa.services.outcomes.Id id,gov.nih.nci.coppa.services.outcomes.CD typeCode) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getByTargetPerformedActivity");
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetByTargetPerformedActivityRequest params = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetByTargetPerformedActivityRequest();
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetByTargetPerformedActivityRequestId idContainer = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetByTargetPerformedActivityRequestId();
    idContainer.setId(id);
    params.setId(idContainer);
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetByTargetPerformedActivityRequestTypeCode typeCodeContainer = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetByTargetPerformedActivityRequestTypeCode();
    typeCodeContainer.setCD(typeCode);
    params.setTypeCode(typeCodeContainer);
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetByTargetPerformedActivityResponse boxedResult = portType.getByTargetPerformedActivity(params);
    return boxedResult.getActivityRelationship();
    }
  }

  public gov.nih.nci.coppa.services.outcomes.ActivityRelationship[] getBySourcePerformedActivity(gov.nih.nci.coppa.services.outcomes.Id id,gov.nih.nci.coppa.services.outcomes.CD typeCode) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getBySourcePerformedActivity");
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetBySourcePerformedActivityRequest params = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetBySourcePerformedActivityRequest();
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetBySourcePerformedActivityRequestId idContainer = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetBySourcePerformedActivityRequestId();
    idContainer.setId(id);
    params.setId(idContainer);
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetBySourcePerformedActivityRequestTypeCode typeCodeContainer = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetBySourcePerformedActivityRequestTypeCode();
    typeCodeContainer.setCD(typeCode);
    params.setTypeCode(typeCodeContainer);
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetBySourcePerformedActivityResponse boxedResult = portType.getBySourcePerformedActivity(params);
    return boxedResult.getActivityRelationship();
    }
  }

  public gov.nih.nci.coppa.services.outcomes.ActivityRelationship[] getByStudyProtocol(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"getByStudyProtocol");
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetByStudyProtocolRequest params = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetByStudyProtocolRequest();
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetByStudyProtocolRequestId idContainer = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetByStudyProtocolRequestId();
    idContainer.setId(id);
    params.setId(idContainer);
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetByStudyProtocolResponse boxedResult = portType.getByStudyProtocol(params);
    return boxedResult.getActivityRelationship();
    }
  }

  public gov.nih.nci.coppa.services.outcomes.ActivityRelationship get(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"get");
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetRequest params = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetRequest();
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetRequestId idContainer = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetRequestId();
    idContainer.setId(id);
    params.setId(idContainer);
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.GetResponse boxedResult = portType.get(params);
    return boxedResult.getActivityRelationship();
    }
  }

  public gov.nih.nci.coppa.services.outcomes.ActivityRelationship create(gov.nih.nci.coppa.services.outcomes.ActivityRelationship activityRelationship) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"create");
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.CreateRequest params = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.CreateRequest();
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.CreateRequestActivityRelationship activityRelationshipContainer = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.CreateRequestActivityRelationship();
    activityRelationshipContainer.setActivityRelationship(activityRelationship);
    params.setActivityRelationship(activityRelationshipContainer);
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.CreateResponse boxedResult = portType.create(params);
    return boxedResult.getActivityRelationship();
    }
  }

  public gov.nih.nci.coppa.services.outcomes.ActivityRelationship update(gov.nih.nci.coppa.services.outcomes.ActivityRelationship activityRelationship) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"update");
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.UpdateRequest params = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.UpdateRequest();
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.UpdateRequestActivityRelationship activityRelationshipContainer = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.UpdateRequestActivityRelationship();
    activityRelationshipContainer.setActivityRelationship(activityRelationship);
    params.setActivityRelationship(activityRelationshipContainer);
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.UpdateResponse boxedResult = portType.update(params);
    return boxedResult.getActivityRelationship();
    }
  }

  public void delete(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    synchronized(portTypeMutex){
      configureStubSecurity((Stub)portType,"delete");
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.DeleteRequest params = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.DeleteRequest();
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.DeleteRequestId idContainer = new gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.DeleteRequestId();
    idContainer.setId(id);
    params.setId(idContainer);
    gov.nih.nci.coppa.services.outcomes.activityrelationship.stubs.DeleteResponse boxedResult = portType.delete(params);
    }
  }

}
