function FileData_Pairs(x)
{
x.t("searching","trials");
x.t("protocols","abstracting");
x.t("protocols","help");
x.t("managing","protocols");
x.t("managing","protocol");
x.t("abstraction","portal");
x.t("trials","working");
x.t("trials","5.2.1");
x.t("trials","protocol");
x.t("currently","construction");
x.t("describes","abstract");
x.t("working","search");
x.t("editing","trials");
x.t("details","editing");
x.t("includes","following");
x.t("trial","details");
x.t("results","viewing");
x.t("5.2.1","managing");
x.t("abstracting","managing");
x.t("edit","clinical");
x.t("construction","section");
x.t("search","results");
x.t("portal","section");
x.t("viewing","trial");
x.t("section","describes");
x.t("section","includes");
x.t("abstract","edit");
x.t("project","currently");
x.t("help","project");
x.t("protocol","abstraction");
x.t("protocol","abstractions");
x.t("topics","searching");
x.t("following","topics");
x.t("clinical","trials");
}
