function FileData_Pairs(x)
{
x.t("trials","trial");
x.t("scientific","data");
x.t("non-proprietary","trials");
x.t("details","trial");
x.t("details","outcome");
x.t("includes","following");
x.t("trial","design");
x.t("trial","eligibility");
x.t("complete","section");
x.t("abstracting","scientific");
x.t("abstracting","trial");
x.t("design","details");
x.t("design","includes");
x.t("design","complete");
x.t("design","abstracting");
x.t("section","non-proprietary");
x.t("outcome","measures");
x.t("eligibility","criteria");
x.t("data","abstracting");
x.t("following","details");
x.t("measures","trial");
}
