function FileData_Pairs(x)
{
x.t("searching","trials");
x.t("searching","registered");
x.t("trials","searching");
x.t("trials","viewing");
x.t("trials","reporting");
x.t("trials","section");
x.t("trials","clinical");
x.t("describes","search");
x.t("program","(ctrp)");
x.t("includes","following");
x.t("trial","identification");
x.t("search","clinical");
x.t("(ctrp)","section");
x.t("registered","trials");
x.t("viewing","trial");
x.t("reporting","program");
x.t("section","describes");
x.t("section","includes");
x.t("identification","details");
x.t("topics","searching");
x.t("following","topics");
x.t("clinical","trials");
}
