function FileData_Pairs(x)
{
x.t("revoke","ownership");
x.t("managing","trial");
x.t("trials","submitted");
x.t("describes","assign");
x.t("topic","managing");
x.t("includes","following");
x.t("trial","ownership");
x.t("assign","revoke");
x.t("ownership","trials");
x.t("ownership","section");
x.t("ownership","assigning");
x.t("section","describes");
x.t("section","includes");
x.t("submitted","ctrp");
x.t("ctrp","section");
x.t("following","topic");
x.t("assigning","trial");
}
