function FileData_Pairs(x)
{
x.t("institute","codes");
x.t("mechanism","codes");
x.t("ind/ide","nih");
x.t("program","code");
x.t("identify","nih");
x.t("division","program");
x.t("includes","following");
x.t("nih","nci");
x.t("nih","institute/nci");
x.t("codes","institute");
x.t("codes","ind/ide");
x.t("codes","section");
x.t("codes","used");
x.t("provides","values");
x.t("funding","mechanism");
x.t("funding","mechanisms");
x.t("section","includes");
x.t("section","provides");
x.t("code","values");
x.t("mechanisms","section");
x.t("values","codes");
x.t("values","funding");
x.t("nci","codes");
x.t("nci","funding");
x.t("topics","nci");
x.t("used","identify");
x.t("following","topics");
x.t("institute/nci","division");
}
