function FileData_Pairs(x)
{
x.t("searching","trials");
x.t("trials","search");
x.t("trials","reporting");
x.t("trials","inbox");
x.t("trials","ctrp");
x.t("trials","nci");
x.t("trials","clinical");
x.t("lists","trials");
x.t("submitter","require");
x.t("program","processing");
x.t("re-abstraction","list");
x.t("require","re-abstraction");
x.t("trial","submitter");
x.t("trial","identifiers");
x.t("list","updated");
x.t("search","specific");
x.t("processing","updated");
x.t("reporting","program");
x.t("accessing","trials");
x.t("inbox","searching");
x.t("inbox","lists");
x.t("inbox","accessing");
x.t("inbox","inbox");
x.t("specific","trials");
x.t("ctrp","updated");
x.t("nci","trial");
x.t("clinical","trials");
x.t("updated","trials");
x.t("updated","trial");
}
