function FileData_Pairs(x)
{
x.t("protocols","managing");
x.t("managing","protocols");
x.t("managing","protocol");
x.t("business","interface");
x.t("interface","concerned");
x.t("abstracting","managing");
x.t("concerned","management");
x.t("instances","protocol");
x.t("include","following");
x.t("administrative","business");
x.t("protocol","abstractions");
x.t("management","instances");
x.t("following","operations");
x.t("abstractions","managing");
x.t("abstractions","abstracting");
x.t("abstractions","include");
x.t("abstractions","administrative");
}
