function FileData_Pairs(x)
{
x.t("email","address");
x.t("persons","email");
x.t("contact","field");
x.t("contact","details");
x.t("contact","phone");
x.t("instructions","looking");
x.t("field","email");
x.t("field","type");
x.t("field","click");
x.t("central","contact");
x.t("look","search");
x.t("type","contact\u2019s");
x.t("details","central");
x.t("details","abstracting");
x.t("details","abstract");
x.t("trial","details");
x.t("looking","registered");
x.t("abstracting","central");
x.t("abstracting","administrative");
x.t("abstracting","general");
x.t("search","person");
x.t("address","field");
x.t("address","phone");
x.t("phone","number");
x.t("registered","persons");
x.t("number","field");
x.t("person","per");
x.t("abstract","central");
x.t("click","look");
x.t("main","email");
x.t("main","contact");
x.t("administrative","data");
x.t("data","abstracting");
x.t("contact\u2019s","main");
x.t("general","trial");
x.t("per","instructions");
}
