function FileData_Pairs(x)
{
x.t("lead","organization");
x.t("instructions","looking");
x.t("field","click");
x.t("look","search");
x.t("details","lead");
x.t("details","abstracting");
x.t("details","abstract");
x.t("trial","details");
x.t("organization","field");
x.t("organization","principle");
x.t("organization","per");
x.t("looking","registered");
x.t("abstracting","lead");
x.t("abstracting","administrative");
x.t("abstracting","general");
x.t("search","organization");
x.t("search","person");
x.t("registered","persons");
x.t("registered","organizations");
x.t("investigator","field");
x.t("investigator","details");
x.t("person","per");
x.t("abstract","lead");
x.t("organizations","principle");
x.t("click","look");
x.t("administrative","data");
x.t("data","abstracting");
x.t("principle","investigator");
x.t("general","trial");
x.t("per","instructions");
}
