function FileData_Pairs(x)
{
x.t("study","randomized");
x.t("method","physician");
x.t("allocation","allocation");
x.t("allocation","metadata");
x.t("allocation","ssignment");
x.t("allocation","values");
x.t("participants","expressly");
x.t("participants","assigned");
x.t("participants","intervention");
x.t("controlled","trial");
x.t("single","arm");
x.t("trial","participants");
x.t("group","allocation");
x.t("expressly","assigned");
x.t("randomized","controlled");
x.t("metadata","definitions");
x.t("arm","study");
x.t("assigned","intervention");
x.t("groups","chance");
x.t("groups","non-random");
x.t("n/a","single");
x.t("ssignment","participants");
x.t("physician","choice");
x.t("intervention","group");
x.t("intervention","groups");
x.t("values","definitions");
x.t("chance","non-randomized");
x.t("non-randomized","trial");
x.t("definitions","allocation");
x.t("definitions","n/a");
x.t("non-random","method");
}
