function FileData_Pairs(x)
{
x.t("required","complete");
x.t("details","unless");
x.t("details","abstracting");
x.t("details","page");
x.t("trial","details");
x.t("trial","title");
x.t("complete","information");
x.t("unless","otherwise");
x.t("abstracting","trial");
x.t("abstracting","administrative");
x.t("abstracting","general");
x.t("title","details");
x.t("administrative","data");
x.t("page","abstracting");
x.t("data","abstracting");
x.t("noted","required");
x.t("information","general");
x.t("otherwise","noted");
x.t("general","trial");
}
