function FileData_Pairs(x)
{
x.t("abstraction","instructions");
x.t("abstraction","portal");
x.t("instructions","forlogging");
x.t("getting","started");
x.t("overview","protocol");
x.t("overview","nci");
x.t("logging","nci");
x.t("logging","protocol");
x.t("provides","overview");
x.t("started","getting");
x.t("started","section");
x.t("portal","logging");
x.t("portal","topics");
x.t("section","provides");
x.t("section","include");
x.t("include","overview");
x.t("forlogging","nci");
x.t("protocol","abstraction");
x.t("nci","clinical");
x.t("topics","section");
x.t("clinical","protocol");
}
