function FileData_Pairs(x)
{
x.t("abstraction","captures");
x.t("captures","trial");
x.t("submitter","section");
x.t("details","metadata");
x.t("trial","submitter");
x.t("trial","details");
x.t("entered","trial");
x.t("provides","values");
x.t("metadata","entered");
x.t("metadata","definitions");
x.t("metadata","associated");
x.t("section","provides");
x.t("values","definitions");
x.t("protocol","abstraction");
x.t("definitions","metadata");
x.t("definitions","protocol");
x.t("associated","clinical");
x.t("clinical","trials");
}
