function FileData_Pairs(x)
{
x.t("nct","number");
x.t("trials","details");
x.t("sidebar","click");
x.t("field","type");
x.t("type","trial");
x.t("details","abstracting");
x.t("details","abstract");
x.t("details","page");
x.t("details","navigation");
x.t("details","general");
x.t("trial","program");
x.t("trial","details");
x.t("trial","identifier");
x.t("abstracting","administrative");
x.t("abstracting","general");
x.t("appears","optionally");
x.t("number","field");
x.t("assigned","clinical");
x.t("identifier","assigned");
x.t("abstract","general");
x.t("click","general");
x.t("administrative","data");
x.t("page","appears");
x.t("data","abstracting");
x.t("optionally","nct");
x.t("navigation","sidebar");
x.t("general","trials");
x.t("general","trial");
x.t("clinical","trial");
}
