function FileData_Pairs(x)
{
x.t("abstraction","section");
x.t("trials","using");
x.t("describes","abstract");
x.t("includes","following");
x.t("trial","overview");
x.t("trial","milestones");
x.t("trial","history");
x.t("overview","data");
x.t("overview","elements");
x.t("abstracting","trial");
x.t("abstracting","on-hold");
x.t("edit","trial");
x.t("section","describes");
x.t("section","includes");
x.t("abstract","edit");
x.t("on-hold","information");
x.t("data","abstracting");
x.t("data","section");
x.t("information","abstracting");
x.t("milestones","abstracting");
x.t("protocol","abstraction");
x.t("topics","trial");
x.t("history","information");
x.t("elements","clinical");
x.t("following","topics");
x.t("using","protocol");
x.t("clinical","trials");
}
