function FileData_Pairs(x)
{
x.t("dashes","separators");
x.t("extensions","applicable");
x.t("u.s","canadian");
x.t("contacts","type");
x.t("type","phone");
x.t("canadian","contacts");
x.t("entering","phone");
x.t("spaces","dashes");
x.t("common","tasks");
x.t("tasks","entering");
x.t("phone","number");
x.t("phone","fax");
x.t("xxx-xxx-","xxxx");
x.t("xxxx","others");
x.t("others","spaces");
x.t("number","extensions");
x.t("format","xxx-xxx-");
x.t("include","phone");
x.t("separators","include");
x.t("separators","separators");
x.t("fax","numbers");
x.t("numbers","u.s");
x.t("numbers","entering");
x.t("numbers","common");
x.t("numbers","format");
}
