function FileData_Pairs(x)
{
x.t("managing","accrual");
x.t("accrual","access");
x.t("accrual","site");
x.t("accrual","application");
x.t("trials","registered");
x.t("describes","grant");
x.t("access","accrual");
x.t("access","activating");
x.t("access","ctrp");
x.t("access","setting");
x.t("includes","following");
x.t("registered","ctrp");
x.t("section","describes");
x.t("section","includes");
x.t("specific","trials");
x.t("activating","inactivating");
x.t("site","specific");
x.t("inactivating","accrual");
x.t("granting","access");
x.t("application","section");
x.t("application","granting");
x.t("grant","users");
x.t("ctrp","accrual");
x.t("ctrp","section");
x.t("users","access");
x.t("topics","managing");
x.t("following","topics");
x.t("setting","accrual");
}
