function FileData_Pairs(x)
{
x.t("staff","provided");
x.t("descriptions","abstracting");
x.t("descriptions","abstract");
x.t("descriptions","optionally");
x.t("field","type");
x.t("provided","keywords");
x.t("type","word");
x.t("classify","trial");
x.t("keywords","field");
x.t("details","abstracting");
x.t("trial","descriptions");
x.t("trial","details");
x.t("trial","pdq");
x.t("pdq","staff");
x.t("abstracting","trial");
x.t("abstracting","administrative");
x.t("abstracting","general");
x.t("words","help");
x.t("abstract","trial");
x.t("administrative","data");
x.t("word","series");
x.t("help","classify");
x.t("data","abstracting");
x.t("optionally","keywords");
x.t("general","trial");
x.t("series","words");
}
