function FileData_Pairs(x)
{
x.t("trials","section");
x.t("describes","abstract");
x.t("descriptions","abstracting");
x.t("interventions","abstracting");
x.t("scientific","details");
x.t("scientific","data");
x.t("details","clinical");
x.t("diseases/conditions","abstracting");
x.t("includes","following");
x.t("trial","descriptions");
x.t("trial","design");
x.t("abstracting","interventions");
x.t("abstracting","scientific");
x.t("abstracting","sub-groups");
x.t("abstracting","diseases/conditions");
x.t("abstracting","trial");
x.t("abstracting","arm");
x.t("edit","scientific");
x.t("arm","information");
x.t("design","abstracting");
x.t("section","describes");
x.t("section","includes");
x.t("abstract","edit");
x.t("data","abstracting");
x.t("data","section");
x.t("information","abstracting");
x.t("topics","abstracting");
x.t("following","topics");
x.t("clinical","trials");
}
