function FileData_Pairs(x)
{
x.t("abstraction","once");
x.t("abstraction","user");
x.t("abstraction","getting");
x.t("abstraction","navigate");
x.t("abstraction","logging");
x.t("abstraction","portal");
x.t("trials","cabig");
x.t("trials","page");
x.t("once","register");
x.t("user","credentials");
x.t("user","enter");
x.t("register","protocol");
x.t("provided","click");
x.t("type","username");
x.t("repository","log");
x.t("getting","started");
x.t("credentials","manage");
x.t("navigate","protocol");
x.t("cabig","repository");
x.t("logging","protocol");
x.t("search","trials");
x.t("started","logging");
x.t("fields","provided");
x.t("portal","login");
x.t("passwordin","fields");
x.t("appears","type");
x.t("login","page");
x.t("enter","user");
x.t("click","log");
x.t("username","passwordin");
x.t("page","appears");
x.t("protocol","abstraction");
x.t("manage","trials");
x.t("log","search");
x.t("log","protocol");
}
