function FileData_Pairs(x)
{
x.t("field","type");
x.t("field","ensure");
x.t("necessary","changes");
x.t("type","abbreviation");
x.t("details","abstracting");
x.t("document","necessary");
x.t("trial","details");
x.t("trial","titles");
x.t("trial","known");
x.t("trial","title");
x.t("complete","appears");
x.t("acronym","field");
x.t("abstracting","trial");
x.t("abstracting","administrative");
x.t("abstracting","general");
x.t("titles","abstracting");
x.t("titles","optionally");
x.t("official","title");
x.t("abbreviation","initial");
x.t("appears","protocol");
x.t("changes","additions");
x.t("initial","letters");
x.t("abstract","trial");
x.t("known","official");
x.t("ensure","title");
x.t("title","field");
x.t("title","abstract");
x.t("title","accurate");
x.t("administrative","data");
x.t("data","abstracting");
x.t("protocol","document");
x.t("optionally","acronym");
x.t("letters","trial");
x.t("accurate","complete");
x.t("general","trial");
}
