function FileData_Pairs(x)
{
x.t("abstraction","instructions");
x.t("abstraction","trial");
x.t("abstraction","logging");
x.t("instructions","logging");
x.t("categories","logging");
x.t("getting","started");
x.t("trial","categories");
x.t("overview","protocol");
x.t("logging","application");
x.t("logging","protocol");
x.t("provides","overview");
x.t("started","getting");
x.t("started","section");
x.t("section","provides");
x.t("section","include");
x.t("include","overview");
x.t("application","topics");
x.t("protocol","abstraction");
x.t("topics","section");
}
