function FileData_Pairs(x)
{
x.t("abstraction","validation");
x.t("abstraction","reports");
x.t("describes","ensure");
x.t("instructions","correcting");
x.t("current","trial");
x.t("necessary","details");
x.t("errors","may");
x.t("details","provides");
x.t("includes","following");
x.t("trial","abstract");
x.t("provides","instructions");
x.t("completing","validating");
x.t("completing","abstractions");
x.t("validation","completing");
x.t("viewing","abstraction");
x.t("may","occur");
x.t("section","describes");
x.t("section","includes");
x.t("reports","section");
x.t("abstract","contains");
x.t("ensure","current");
x.t("validating","abstractions");
x.t("topics","abstraction");
x.t("correcting","errors");
x.t("following","topics");
x.t("occur","viewing");
x.t("abstractions","completing");
x.t("abstractions","section");
x.t("contains","necessary");
}
