function FileData_Pairs(x)
{
x.t("trials","reporting");
x.t("trials","section");
x.t("describes","look");
x.t("topic","looking");
x.t("program","(ctrp)");
x.t("working","organization");
x.t("look","organizations");
x.t("link","clinical");
x.t("includes","following");
x.t("organization","records");
x.t("looking","registered");
x.t("records","working");
x.t("records","section");
x.t("(ctrp)","link");
x.t("registered","organizations");
x.t("registered","clinical");
x.t("reporting","program");
x.t("section","describes");
x.t("section","includes");
x.t("organizations","registered");
x.t("following","topic");
x.t("clinical","trials");
}
