function FileData_Pairs(x)
{
x.t("searching","trials");
x.t("abstraction","provides");
x.t("trials","navigating");
x.t("trials","reporting");
x.t("trials","inbox");
x.t("trials","using");
x.t("trials","clinical");
x.t("describes","search");
x.t("instructions","working");
x.t("program","searching");
x.t("program","section");
x.t("working","search");
x.t("navigating","search");
x.t("details","processing");
x.t("includes","following");
x.t("list","viewing");
x.t("trial","identification");
x.t("results","list");
x.t("results","section");
x.t("provides","instructions");
x.t("search","results");
x.t("search","clinical");
x.t("viewing","trial");
x.t("processing","updated");
x.t("reporting","program");
x.t("section","describes");
x.t("section","includes");
x.t("identification","details");
x.t("protocol","abstraction");
x.t("topics","searching");
x.t("following","topics");
x.t("using","protocol");
x.t("clinical","trials");
x.t("updated","trials");
}
