function FileData_Pairs(x)
{
x.t("single-masked","study");
x.t("double","blind");
x.t("unaware","intervention");
x.t("blind","party");
x.t("blind","two");
x.t("open","masking");
x.t("party","either");
x.t("single","blind");
x.t("assignment","single");
x.t("assignment","called");
x.t("assignment","masking");
x.t("participant","unaware");
x.t("metadata","definitions");
x.t("ding","knowledge");
x.t("investigator","participant");
x.t("parties","unaware");
x.t("intervention","assignment");
x.t("knowledge","intervention");
x.t("values","definitions");
x.t("called","single-masked");
x.t("two","parties");
x.t("either","investigator");
x.t("masking","double");
x.t("masking","metadata");
x.t("masking","ding");
x.t("masking","values");
x.t("masking","masking");
x.t("definitions","open");
x.t("definitions","masking");
}
