function FileData_Pairs(x)
{
x.t("example","sets");
x.t("events","during");
x.t("once","trial");
x.t("status","submitted");
x.t("status","system");
x.t("trial","processing");
x.t("trial","validated");
x.t("during","process");
x.t("cycle","establish");
x.t("completing","abstractions");
x.t("record","progress");
x.t("sets","trial");
x.t("progress","trail");
x.t("accepted","once");
x.t("life","cycle");
x.t("processing","status");
x.t("processing","life");
x.t("establish","processing");
x.t("specific","events");
x.t("process","example");
x.t("trail","along");
x.t("along","processing");
x.t("milestones","completing");
x.t("milestones","specific");
x.t("milestones","milestones");
x.t("milestones","reviewing");
x.t("milestones","used");
x.t("reviewing","adding");
x.t("submitted","trial");
x.t("used","record");
x.t("system","establishes");
x.t("adding","milestones");
x.t("abstractions","reviewing");
x.t("validated","accepted");
x.t("establishes","milestones");
}
