function  WWHBookData_Files(P)
{
P.fA("NCI Clinical Trials Reporting Program Viewer Online Help","Welcome.1.1.html");
P.fA("Using the Online Help","Welcome.1.2.html");
P.fA("Getting Started","GettingStartedViewer.2.1.html");
P.fA("About the CTRP Viewer","GettingStartedViewer.2.2.html");
P.fA("What\u2019s New in This Release","GettingStartedViewer.2.3.html");
P.fA("Creating CTRP Viewer Accounts","GettingStartedViewer.2.4.html");
P.fA("Creating New CTRP Viewer Accounts","GettingStartedViewer.2.5.html");
P.fA("Creating New CTRP Viewer Accounts Using caGrid or NCI Credentials","GettingStartedViewer.2.6.html");
P.fA("Logging In to the CTRP Viewer","GettingStartedViewer.2.7.html");
P.fA("CTRO Reporting","report.3.1.html");
P.fA("About CTRO Reporting","report.3.2.html");
P.fA("Running CTRO Reports","report.3.3.html");
P.fA("Running Summary of Submission Reports","report.3.4.html");
P.fA("Running Trial Processing Reports","report.3.5.html");
P.fA("Running Portfolio Average Milestone Reports","report.3.6.html");
P.fA("Running Trials Submitted by Date Reports","report.3.7.html");
P.fA("Running Trials Submitted by Institution Reports","report.3.8.html");
P.fA("Running Current Milestone Reports","report.3.9.html");
P.fA("Running Summary 4 Type Reports","report.3.10.html");
P.fA("Running Ad Hoc Reports","report.3.11.html");
P.fA("Accessing Trial Summary Reports","report.3.12.html");
P.fA("Exporting Report Data","report.3.13.html");
P.fA("Managing Your Account","userAccount.4.1.html");
P.fA("Managing Your User Account Profile","userAccount.4.2.html");
P.fA("Changing Your Password","userAccount.4.3.html");
P.fA("Resetting Your Account","userAccount.4.4.html");
P.fA("Ad Hoc Report Criteria Values","validValues.5.1.html");
P.fA("Primary Purpose Values","validValues.5.2.html");
P.fA("Trial Phase Values","validValues.5.3.html");
P.fA("Trial Identifier Types","validValues.5.4.html");
P.fA("Processing Statuses","validValues.5.5.html");
P.fA("Intervention Types","validValues.5.6.html");
P.fA("Trial Statuses","validValues.5.7.html");
P.fA("Trial Categories","validValues.5.8.html");
P.fA("Summary 4 Funding Category","validValues.5.9.html");
P.fA("Milestones","validValues.5.10.html");
P.fA("Looking up Diseases/Conditions","diseaseLookUp.6.1.html");
P.fA("Application Support","appSupport.7.1.html");
}
