
--SCRIPT NAME:  tables.sql 
--PURPOSE:      Create or recreate tables based on Clinical Trial Object Model. 
--AUTHOR:       
--DATE:         May 2008 
--VERSION:      
--NOTE:         This script is a MySql verson of the script 



use ctods;

SET FOREIGN_KEY_CHECKS = 0;


DROP TABLE IF EXISTS HEALTHCARE_SITE_INVESTIGATOR ;
DROP TABLE IF EXISTS HEALTHCARE_SITE_PRTCPNT ;
DROP TABLE IF EXISTS STUDY_INVESTIGATOR ;
DROP TABLE IF EXISTS INVESTIGATOR ;
DROP TABLE IF EXISTS STUDY_SITE ;
DROP TABLE IF EXISTS HEALTHCARE_SITE ;
DROP TABLE IF EXISTS PROTOCOL_STATUS ;
DROP TABLE IF EXISTS PROTOCOL ;

CREATE TABLE HEALTHCARE_SITE ( 
	ID BIGINT NOT NULL AUTO_INCREMENT	COMMENT 'SYSTEM GENERATED PRIMARY KEY.',
	NAME VARCHAR(200),
	DESCRIPTION_TEXT VARCHAR(200),
	STATUS_CODE VARCHAR(200),
	STATUS_DATE DATE,
	STATUS_DATE_ORIG VARCHAR(200)		COMMENT 'ADDED TO HANDLE INVALID VALUES',   
	STREET_ADDRESS VARCHAR(200),
	CITY VARCHAR(200),
	STATE_CODE VARCHAR(200),
	POSTAL_CODE VARCHAR(200),
	COUNTRY_CODE VARCHAR(200),
	TELECOM_ADDRESS VARCHAR(200),
	NCI_INSTITUTE_CODE VARCHAR(200),
	SOURCE VARCHAR(200)			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	SOURCE_EXTRACT_DATE DATE		COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_INSERT_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_UPDATE_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	PRIMARY KEY (ID)
)ENGINE=INNODB 
;

CREATE TABLE HEALTHCARE_SITE_INVESTIGATOR ( 
	ID BIGINT NOT NULL AUTO_INCREMENT	COMMENT 'SYSTEM GENERATED PRIMARY KEY.',
	ROLE_CODE VARCHAR(200),
	INVESTIGATOR_ID BIGINT NOT NULL		COMMENT 'FOREIGN KEY FROM INVESTIGATORS TABLE.',    
	HEALTHCARE_SITE_ID BIGINT NOT NULL	COMMENT 'FOREIGN KEY FROM HEALTHCARE_SITES TABLE.', 
	SECURITY_KEY BIGINT,    		
	SOURCE VARCHAR(200)			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	SOURCE_EXTRACT_DATE DATE		COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_INSERT_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_UPDATE_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	PRIMARY KEY (ID)
)ENGINE=INNODB 
;


CREATE TABLE HEALTHCARE_SITE_PRTCPNT ( 
	ID BIGINT NOT NULL AUTO_INCREMENT	COMMENT 'SYSTEM GENERATED PRIMARY KEY.',
	PARTICIPANT_IDENTIFIER VARCHAR(200),
	HEALTHCARE_SITE_ID BIGINT NOT NULL	COMMENT 'FOREIGN KEY FROM HEALTHCARESITES TABLE.',  
	PARTICIPANT_ID BIGINT NOT NULL		COMMENT 'FOREIGN KEY FROM PARTICIPANTS TABLE.',    
	SECURITY_KEY BIGINT,    		
	SOURCE VARCHAR(200)			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	SOURCE_EXTRACT_DATE DATE		COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_INSERT_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_UPDATE_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	PRIMARY KEY (ID)
)ENGINE=INNODB 
;



CREATE TABLE INVESTIGATOR ( 
	ID BIGINT NOT NULL AUTO_INCREMENT,
	LAST_NAME VARCHAR(200),
	FIRST_NAME VARCHAR(200),
	MIDDLE_NAME VARCHAR(200),
	BIRTH_DATE DATE,
	BIRTH_DATE_ORIG VARCHAR(200)		COMMENT 'ADDED TO HANDLE INVALID VALUES',    	
	TELECOM_ADDRESS VARCHAR(200),
	ADMINISTRATIVE_GENDER_CODE VARCHAR(200)	COMMENT 'VALUES INCLUDE: FEMALE, MALE, UNKNOWN.',
	STREET_ADDRESS VARCHAR(200),
	CITY VARCHAR(200),
	STATE VARCHAR(200),
	ZIP_CODE VARCHAR(200),
	COUNTRY_CODE VARCHAR(200),
	PHONE VARCHAR(200),
	EDUCATION_LEVEL_CODE VARCHAR(200)	COMMENT 'VALUES INCLUDE: LESS THAN HIGH SCHOOL DIPLOMA, HIGH SCHOOL DIPLOMA, SOME COLLEGE, ETC.',   
	ETHNIC_GROUP_CODE VARCHAR(200)		COMMENT 'VALUES INCLUDE: HISPANIC OR LATINO, UNKNOWN, NOT REPORTED, NOT HISPANIC OR LATINO.',    
	HOUSEHOLD_INCOME_CODE VARCHAR(200)	COMMENT 'VALUES INCLUDE: LESS THAN $25,000, $25,000 TO $50,000, ETC.',  
	MARITAL_STATUS_CODE VARCHAR(200)	COMMENT 'VALUES INCLUDE: MARRIED, WIDOWED, SINGLE, SEPARATED, ETC.',    
	RACE_CODE VARCHAR(200)			COMMENT 'VALUES INCLUDE: NOT REPORTED, UNKNOWN, ASIAN, WHITE, ETC.',    		
	EMPLOYMENT_STATUS_CODE VARCHAR(200)	COMMENT 'VALUES INCLUDE: DISABLED, EMPLOYED, HOMEMAKER, RETIRED, ETC.', 
	EMPLOYMENT_STATUS_OTHER_TEXT VARCHAR(200),
	NCI_IDENTIFIER VARCHAR(200),
	INITIALS                                           VARCHAR(200),
	ADM_GNDR_CONCEPT_DESCRIPTOR_ID                     BIGINT,
	RACE_CONCEPT_DESCRIPTOR_ID                         BIGINT,	
	SECURITY_KEY BIGINT,    		
	SOURCE VARCHAR(200)			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	SOURCE_EXTRACT_DATE DATE		COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_INSERT_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_UPDATE_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	PRIMARY KEY (ID)
)ENGINE=INNODB 
;


CREATE TABLE PROTOCOL ( 
	ID BIGINT NOT NULL AUTO_INCREMENT	COMMENT 'SYSTEM GENERATED PRIMARY KEY.',
	NCI_IDENTIFIER VARCHAR(200),
	AMENDMENT_IDENTIFIER DOUBLE,
	AMENDMENT_IDENTIFIER_ORIG VARCHAR(200)	COMMENT 'ADDED TO HANDLE INVALID VALUES', 
	AMENDMENT_DATE DATE,
	AMENDMENT_DATE_ORIG VARCHAR(200)	COMMENT 'ADDED TO HANDLE INVALID VALUES',    	
	NAVY_NCI_IDENTIFIER VARCHAR(200),
	LONG_TITLE_TEXT VARCHAR(500),
	SHORT_TITLE_TEXT VARCHAR(200)		COMMENT '[ADDITIONAL DOCUMENTATION] A NAME OR ABBREVIATED TITLE BY WHICH THE DOCUMENT IS KNOWN. [BRIDG] [END DOCUMENTATION]',    	
	PRECIS_TEXT VARCHAR(200),
	DESCRIPTION_TEXT VARCHAR(200),
	DISEASE_CODE VARCHAR(200)		COMMENT 'VALUES INCLUDE: A-AIDS, B-BENIGN, C-CANCER.',    		
	INTENT_CODE VARCHAR(200)		COMMENT 'VALUES INCLUDE: D-DIAGNOSTIC PROTOCOL, GN-GENETIC NON-THERAPEUTIC PROTOCOL, ETC.',   		
	MONITOR_CODE VARCHAR(200)		COMMENT 'VALUES INCLUDE: CTEP, CTEP-CTMS, CTEP-CDUS COMPLETE, ETC.',  		
	PHASE_CODE VARCHAR(200)			COMMENT 'VALUES INCLUDE: I, I/II, II, III, NA.',   		
	SPONSOR_CODE VARCHAR(200)		COMMENT 'VALUES INCLUDE: AB-ABBOTT LABS, AL-ALKERMES, INC., APH- ANGIOTECH, AM- AMGEN, ETC.',    		
	BLINDED_INDICATOR VARCHAR(200),
	MULTI_INSTITUTION_INDICATOR VARCHAR(200),
	RANDOMIZED_INDICATOR VARCHAR(200),
	TARGET_ACCRUAL_NUMBER DOUBLE,
	IDENTIFIER_ASSIGNING_AUTHORITY VARCHAR(200), 
	TARGET_ACCRUAL_NUMBER_ORIG VARCHAR(200) COMMENT 'ADDED TO HANDLE INVALID VALUES',    	
	DOCUMENT_URI VARCHAR(200),    			
	SPONSOR_MONITOR VARCHAR(200),    		
	SECURITY_KEY BIGINT,    			
	SOURCE VARCHAR(200)			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	SOURCE_EXTRACT_DATE DATE		COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_INSERT_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_UPDATE_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_INSERT_USER VARCHAR(200)		COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_UPDATE_USER VARCHAR(200)		COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	PRIMARY KEY (ID)
)ENGINE=INNODB 
;


CREATE TABLE PROTOCOL_STATUS ( 
	ID BIGINT NOT NULL AUTO_INCREMENT	COMMENT 'SYSTEM GENERATED PRIMARY KEY.',
	STATUS_CODE VARCHAR(200)		COMMENT 'VALUES INCLUDE: C-CLOSED, O-OPEN, S-SUSPENDED, T-TERMINATED. ',   	
	STATUS_DATE DATE,    		
	STATUS_DATE_ORIG VARCHAR(200)		COMMENT 'ADDED TO HANDLE INVALID VALUES',  
	PROTOCOL_ID BIGINT NOT NULL		COMMENT 'FOREIGN KEY FROM PROTOCOLS TABLE.',    
	SECURITY_KEY BIGINT,    	
	SOURCE VARCHAR(200)			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	SOURCE_EXTRACT_DATE DATE		COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_INSERT_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_UPDATE_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	PRIMARY KEY (ID)
)ENGINE=INNODB 
;




CREATE TABLE STUDY_INVESTIGATOR ( 
	ID BIGINT NOT NULL AUTO_INCREMENT	COMMENT 'SYSTEM GENERATED PRIMARY KEY.',
	RESPONSIBILITY_ROLE_CODE VARCHAR(200)	COMMENT 'EXAMPLES INCLUDE: PRIMARY INVESTIGATOR, CO-INVESTIGATOR, ETC.', 
	START_DATE DATE,
	START_DATE_ORIG VARCHAR(200)		COMMENT 'ADDED TO HANDLE INVALID VALUES',    	
	STOP_DATE DATE,
	STOP_DATE_ORIG VARCHAR(200)		COMMENT 'ADDED TO HANDLE INVALID VALUES',    	
	STATUS_CODE VARCHAR(200),
	SIGNATURE_INDICATOR VARCHAR(200)	COMMENT '[ADDITIONAL DOCUMENTATION] A CODE SPECIFYING WHETHER AND HOW THE PARTICIPANT HAS ATTESTED HIS PARTICIPATION THROUGH A SIGNATURE AND OR WHETHER SUCH A SIGNATURE IS NEEDED. [BRIDG] [END DOCUMENTATION]',   	
	SIGNATURE_TEXT VARCHAR(200)		COMMENT '[ADDITIONAL DOCUMENTATION] A TEXTUAL OR MULTIMEDIA DEPICTION OF THE SIGNATURE BY . [BRIDG] [END DOCUMENTATION]',    	
	PROTOCOL_ID BIGINT NOT NULL		COMMENT 'FOREIGN KEY FROM PROTOCOLS TABLE.',    	
	INVESTIGATOR_ID BIGINT NOT NULL		COMMENT 'FOREIGN KEY FROM INVESTIGATORS TABLE.',    	
        STUDY_SITE_ID BIGINT                    COMMENT 'FOREIGN KEY FROM STUDY_SITE_TABLE. PROBABLY A TEMPORARY ADDITION',
	SECURITY_KEY BIGINT,    		
	SOURCE VARCHAR(200)			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	SOURCE_EXTRACT_DATE DATE		COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_INSERT_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_UPDATE_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	PRIMARY KEY (ID)
)ENGINE=INNODB 
;

CREATE TABLE STUDY_SITE ( 
	ID BIGINT NOT NULL AUTO_INCREMENT	COMMENT 'SYSTEM GENERATED PRIMARY KEY.',
	ROLE_CODE VARCHAR(200)			COMMENT 'EXAMPLES INCLUDE: LEAD ORGANIZATION, PARTICIPATING ORGANIZATION, ETC.',    		
	STATUS_CODE VARCHAR(200),
	TARGET_ACCRUAL_NUMBER VARCHAR(200),
	START_DATE DATE,
	START_DATE_ORIG VARCHAR(200)		COMMENT 'ADDED TO HANDLE INVALID VALUES',    	
	STOP_DATE DATE,
	STOP_DATE_ORIG VARCHAR(200)		COMMENT 'ADDED TO HANDLE INVALID VALUES',    	
	IRB_APPROVAL_DATE DATE,
	IRB_APPROVAL_DATE_ORIG VARCHAR(200)	COMMENT 'ADDED TO HANDLE INVALID VALUES',    
	LOCAL_PROTOCOL_IDENTIFIER VARCHAR(200), 
	HEALTHCARE_SITE_ID BIGINT NOT NULL	COMMENT 'FOREIGN KEY FROM HEALTHCARESITES TABLE.',    	
	PROTOCOL_ID BIGINT NOT NULL		COMMENT 'FOREIGN KEY FROM PROTOCOLS TABLE.',    	
	SECURITY_KEY BIGINT,    		
	SOURCE VARCHAR(200)			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	SOURCE_EXTRACT_DATE DATE		COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_INSERT_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	CTOM_UPDATE_DATE DATE			COMMENT 'ADDED AUDIT COLUMN FOR DATA TRACKING.', 
	PRIMARY KEY (ID)
)ENGINE=INNODB 
;


ALTER TABLE HEALTHCARE_SITE_INVESTIGATOR ADD CONSTRAINT FK_INVSTGT_HEALTHCR_ST_INVSTGT 
FOREIGN KEY (INVESTIGATOR_ID) REFERENCES INVESTIGATOR (ID)
ON DELETE CASCADE;

ALTER TABLE HEALTHCARE_SITE_INVESTIGATOR ADD CONSTRAINT FK_HLTHCR_ST_HLTHCR_ST_INVSTGT 
FOREIGN KEY (HEALTHCARE_SITE_ID) REFERENCES HEALTHCARE_SITE (ID)
ON DELETE CASCADE;

ALTER TABLE PROTOCOL_STATUS ADD CONSTRAINT FK_PROTOCOL_PROTOCOL_STATUS 
FOREIGN KEY (PROTOCOL_ID) REFERENCES PROTOCOL (ID)
ON DELETE CASCADE;

ALTER TABLE STUDY_INVESTIGATOR ADD CONSTRAINT FK_PROTOCOL_STUDY_INVESTIGATOR 
FOREIGN KEY (PROTOCOL_ID) REFERENCES PROTOCOL (ID)
ON DELETE CASCADE;

ALTER TABLE STUDY_INVESTIGATOR ADD CONSTRAINT FK_INVESTIGATOR_STUDY_INVSTGTR 
FOREIGN KEY (INVESTIGATOR_ID) REFERENCES INVESTIGATOR (ID)
ON DELETE CASCADE;

ALTER TABLE STUDY_INVESTIGATOR ADD CONSTRAINT FK_STUDY_SITE_STUDY_INVSTGTR 
FOREIGN KEY (STUDY_SITE_ID) REFERENCES STUDY_SITE (ID)
ON DELETE CASCADE;


ALTER TABLE STUDY_SITE ADD CONSTRAINT FK_HEALTHCARE_SITE_STUDY_SITE 
FOREIGN KEY (HEALTHCARE_SITE_ID) REFERENCES HEALTHCARE_SITE (ID)
ON DELETE CASCADE;

ALTER TABLE STUDY_SITE ADD CONSTRAINT FK_PROTOCOL_STUDY_SITE 
FOREIGN KEY (PROTOCOL_ID) REFERENCES PROTOCOL (ID)
ON DELETE CASCADE;


SET FOREIGN_KEY_CHECKS = 1;
