DROP TABLE IF EXISTS STUDY_CONDITIONS ;
DROP TABLE IF EXISTS CONDITIONS ;

DROP TABLE IF EXISTS DOCUMENT_IDENTIFICATION ;
DROP TABLE IF EXISTS STUDY_PROTOCOL ;


-- using conditions becasue condtion is a key word
CREATE TABLE CONDITIONS (
	ID  SERIAL NOT NULL,
	NAME VARCHAR(200),
	CODE VARCHAR(200),
	PARENT_CODE VARCHAR(200) ,
	CREATED_BY VARCHAR(200) ,
	CREATED_DATE DATE ,
	UPDATED_BY VARCHAR(200) ,
	UPDATED_DATE DATE ,
	PRIMARY KEY (ID)
);

CREATE TABLE STUDY_CONDITIONS (
	ID  SERIAL NOT NULL,
	LEAD_INDICATOR VARCHAR(200),
	CODE VARCHAR(200),
	CONDITIONS_ID BIGINT NOT NULL	,    	
	STUDY_PROTOCOL_ID BIGINT NOT NULL		,    	
	PRIMARY KEY (ID)
);



CREATE TABLE DOCUMENT_IDENTIFICATION ( 
	ID BIGINT NOT NULL	,
	ASSIGNING_AUTHORITY_CODE VARCHAR(200) ,
        PRIMARY_IDENTIFIER VARCHAR(200) ,
	IDENTIFIER VARCHAR(200) , 
	STUDY_PROTOCOL_ID BIGINT NOT NULL		,   
	PRIMARY KEY (ID)
) ;

CREATE TABLE STUDY_PROTOCOL (
        ID BIGINT NOT NULL	,
        NCI_ACCESSION_NUMBER VARCHAR(200) ,
        OFFICIAL_TITLE VARCHAR(500) ,
        ACRONYM VARCHAR(200) ,
        MONITOR_CODE VARCHAR(200) ,
        PHASE_CODE VARCHAR(200) ,
        BIOSPECIMEN_DESCRIPTION VARCHAR(200) ,
        BIOSPECIMEN_RETENTION_CODE VARCHAR(200) ,
        GROUP_NUMBER INTEGER ,
        STUDY_MODEL_CODE VARCHAR(200) ,
        TIME_PRESPECTIVE_CODE VARCHAR(200) ,
        ALLOCATION_CODE VARCHAR(200) ,
        CONTROL_CONCURRENCY_TYPE_CODE  VARCHAR(200) ,
        CONTROL_TYPE_CODE  VARCHAR(200) ,
        DELAYED_POSTING_INDICATOR  BOOLEAN ,
        DESIGN_CONFIGURATION_CODE VARCHAR(200) ,
        FDA_REGULATED_INDICATOR BOOLEAN , 
        INTERVENTION_TYPE_CODE VARCHAR(200) ,
        NUMBER_OF_INTERVENTION_GROUPS INTEGER ,
        TYPE VARCHAR(200)  , 
        SECTION801_INDICATOR BOOLEAN ,
        PRIMARY KEY (ID)
);

ALTER TABLE DOCUMENT_IDENTIFICATION ADD CONSTRAINT FK_DOCUMENT_IDENTIFICATION
FOREIGN KEY (STUDY_PROTOCOL_ID) REFERENCES STUDY_PROTOCOL (ID)
ON DELETE CASCADE;

ALTER TABLE STUDY_CONDITIONS ADD CONSTRAINT FK_CONDITIONS_STUDY_CONDITIONS 
FOREIGN KEY (CONDITIONS_ID) REFERENCES CONDITIONS (ID)
ON DELETE CASCADE;

ALTER TABLE STUDY_CONDITIONS ADD CONSTRAINT FK_STUDY_PROTOCOL_STUDY_CONDITIONS 
FOREIGN KEY (STUDY_PROTOCOL_ID) REFERENCES STUDY_PROTOCOL (ID)
ON DELETE CASCADE;



