
--SCRIPT NAME:  PGtables.sql 
--PURPOSE:      Create or recreate tables based on Clinical Trial Object Model. 
--AUTHOR:       
--DATE:         May 2008 
--VERSION:      
--NOTE:         This script is a Postgresql verson of the script 

--Commands to create database and use database prior to running the DDL scripts.
---createdb ctods;
---psql ctods;


DROP TABLE IF EXISTS SESSIONENTRY;
DROP TABLE IF EXISTS HEALTHCARE_SITE_INVESTIGATOR ;
DROP TABLE IF EXISTS HEALTHCARE_SITE_PRTCPNT ;
DROP TABLE IF EXISTS STUDY_INVESTIGATOR ;
DROP TABLE IF EXISTS INVESTIGATOR ;
DROP TABLE IF EXISTS STUDY_SITE ;
DROP TABLE IF EXISTS HEALTHCARE_SITE ;
DROP TABLE IF EXISTS PROTOCOL_STATUS ;
DROP TABLE IF EXISTS PROTOCOL ;

CREATE SEQUENCE hibernate_sequence
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 27425
  CACHE 1;

CREATE TABLE sessionentry
(
  id bigint NOT NULL,
  accesstime bigint NOT NULL,
  createdtime bigint NOT NULL,
  refererapp character varying(256) NOT NULL,
  remoteuser character varying(256) NOT NULL,
  returnurl character varying(2048) NOT NULL,
  secret bigint NOT NULL,
  CONSTRAINT sessionentry_pkey PRIMARY KEY (id),
  CONSTRAINT sessionentry_secret_key UNIQUE (secret)
);

CREATE TABLE HEALTHCARE_SITE ( 	
	ID  SERIAL NOT NULL,
	NAME VARCHAR(200),
	DESCRIPTION_TEXT VARCHAR(200),
	STATUS_CODE VARCHAR(200),
	STATUS_DATE DATE,
	STATUS_DATE_ORIG VARCHAR(200),   
	STREET_ADDRESS VARCHAR(200),
	CITY VARCHAR(200),
	STATE_CODE VARCHAR(200),
	POSTAL_CODE VARCHAR(200),
	COUNTRY_CODE VARCHAR(200),
	TELECOM_ADDRESS VARCHAR(200),
	NCI_INSTITUTE_CODE VARCHAR(200),
	SOURCE VARCHAR(200)			, 
	SOURCE_EXTRACT_DATE DATE		, 
	CTOM_INSERT_DATE DATE			, 
	CTOM_UPDATE_DATE DATE			, 
	PRIMARY KEY (ID)
);

CREATE TABLE HEALTHCARE_SITE_INVESTIGATOR ( 
	ID SERIAL NOT NULL	,
	ROLE_CODE VARCHAR(200),
	INVESTIGATOR_ID BIGINT NOT NULL		,    
	HEALTHCARE_SITE_ID BIGINT NOT NULL	, 
	SECURITY_KEY BIGINT,    		
	SOURCE VARCHAR(200)			, 
	SOURCE_EXTRACT_DATE DATE		, 
	CTOM_INSERT_DATE DATE			, 
	CTOM_UPDATE_DATE DATE			, 
	PRIMARY KEY (ID)
) 
;


CREATE TABLE HEALTHCARE_SITE_PRTCPNT ( 
	ID SERIAL NOT NULL	,
	PARTICIPANT_IDENTIFIER VARCHAR(200),
	HEALTHCARE_SITE_ID BIGINT NOT NULL	,  
	PARTICIPANT_ID BIGINT NOT NULL		,    
	SECURITY_KEY BIGINT,    		
	SOURCE VARCHAR(200)			, 
	SOURCE_EXTRACT_DATE DATE		, 
	CTOM_INSERT_DATE DATE			, 
	CTOM_UPDATE_DATE DATE			, 
	PRIMARY KEY (ID)
) 
;



CREATE TABLE INVESTIGATOR ( 
	ID SERIAL NOT NULL,
	LAST_NAME VARCHAR(200),
	FIRST_NAME VARCHAR(200),
	MIDDLE_NAME VARCHAR(200),
	BIRTH_DATE DATE,
	BIRTH_DATE_ORIG VARCHAR(200)		,    	
	TELECOM_ADDRESS VARCHAR(200),
	ADMINISTRATIVE_GENDER_CODE VARCHAR(200)	,
	STREET_ADDRESS VARCHAR(200),
	CITY VARCHAR(200),
	STATE VARCHAR(200),
	ZIP_CODE VARCHAR(200),
	COUNTRY_CODE VARCHAR(200),
	PHONE VARCHAR(200),
	EDUCATION_LEVEL_CODE VARCHAR(200)	,   
	ETHNIC_GROUP_CODE VARCHAR(200)		,    
	HOUSEHOLD_INCOME_CODE VARCHAR(200)	,  
	MARITAL_STATUS_CODE VARCHAR(200)	,    
	RACE_CODE VARCHAR(200)			,    		
	EMPLOYMENT_STATUS_CODE VARCHAR(200)	, 
	EMPLOYMENT_STATUS_OTHER_TEXT VARCHAR(200),
	NCI_IDENTIFIER VARCHAR(200),
	INITIALS                                           VARCHAR(200),
	ADM_GNDR_CONCEPT_DESCRIPTOR_ID                     BIGINT,
	RACE_CONCEPT_DESCRIPTOR_ID                         BIGINT,	
	SECURITY_KEY BIGINT,    		
	SOURCE VARCHAR(200)			, 
	SOURCE_EXTRACT_DATE DATE		, 
	CTOM_INSERT_DATE DATE			, 
	CTOM_UPDATE_DATE DATE			, 
	PRIMARY KEY (ID)
) 
;


CREATE TABLE PROTOCOL ( 
	ID SERIAL NOT NULL	,
	NCI_IDENTIFIER VARCHAR(200),
	AMENDMENT_IDENTIFIER FLOAT,
	AMENDMENT_IDENTIFIER_ORIG VARCHAR(200)	, 
	AMENDMENT_DATE DATE,
	AMENDMENT_DATE_ORIG VARCHAR(200)	,    	
	NAVY_NCI_IDENTIFIER VARCHAR(200),
	LONG_TITLE_TEXT VARCHAR(500),
	SHORT_TITLE_TEXT VARCHAR(200)		,    	
	PRECIS_TEXT VARCHAR(200),
	DESCRIPTION_TEXT VARCHAR(200),
	DISEASE_CODE VARCHAR(200)		,    		
	INTENT_CODE VARCHAR(200)		,   		
	MONITOR_CODE VARCHAR(200)		,  		
	PHASE_CODE VARCHAR(200)			,   		
	SPONSOR_CODE VARCHAR(200)		,    		
	BLINDED_INDICATOR VARCHAR(200),
	MULTI_INSTITUTION_INDICATOR VARCHAR(200),
	RANDOMIZED_INDICATOR VARCHAR(200),
	TARGET_ACCRUAL_NUMBER FLOAT,
	IDENTIFIER_ASSIGNING_AUTHORITY VARCHAR(200), 
	TARGET_ACCRUAL_NUMBER_ORIG VARCHAR(200) ,    	
	DOCUMENT_URI VARCHAR(200),    			
	SPONSOR_MONITOR VARCHAR(200),    		
	SECURITY_KEY BIGINT,    			
	SOURCE VARCHAR(200)			, 
	SOURCE_EXTRACT_DATE DATE		, 
	CTOM_INSERT_DATE DATE			, 
	CTOM_UPDATE_DATE DATE			, 
	CTOM_INSERT_USER VARCHAR(200)		, 
	CTOM_UPDATE_USER VARCHAR(200)		, 
	PRIMARY KEY (ID)
) 
;


CREATE TABLE PROTOCOL_STATUS ( 
	ID SERIAL NOT NULL	,
	STATUS_CODE VARCHAR(200)		,   	
	STATUS_DATE DATE,    		
	STATUS_DATE_ORIG VARCHAR(200)		,  
	PROTOCOL_ID BIGINT NOT NULL		,    
	SECURITY_KEY BIGINT,    	
	SOURCE VARCHAR(200)			, 
	SOURCE_EXTRACT_DATE DATE		, 
	CTOM_INSERT_DATE DATE			, 
	CTOM_UPDATE_DATE DATE			, 
	PRIMARY KEY (ID)
) 
;




CREATE TABLE STUDY_INVESTIGATOR ( 
	ID SERIAL NOT NULL	,
	RESPONSIBILITY_ROLE_CODE VARCHAR(200)	, 
	START_DATE DATE,
	START_DATE_ORIG VARCHAR(200)		,    	
	STOP_DATE DATE,
	STOP_DATE_ORIG VARCHAR(200)		,    	
	STATUS_CODE VARCHAR(200),
	SIGNATURE_INDICATOR VARCHAR(200)	,   	
	SIGNATURE_TEXT VARCHAR(200)		,    	
	PROTOCOL_ID BIGINT NOT NULL		,    	
	INVESTIGATOR_ID BIGINT NOT NULL		,    	
        STUDY_SITE_ID BIGINT                    ,
	SECURITY_KEY BIGINT,    		
	SOURCE VARCHAR(200)			, 
	SOURCE_EXTRACT_DATE DATE		, 
	CTOM_INSERT_DATE DATE			, 
	CTOM_UPDATE_DATE DATE			, 
	PRIMARY KEY (ID)
) 
;

CREATE TABLE STUDY_SITE ( 
	ID SERIAL NOT NULL	,
	ROLE_CODE VARCHAR(200)			,    		
	STATUS_CODE VARCHAR(200),
	TARGET_ACCRUAL_NUMBER VARCHAR(200),
	START_DATE DATE,
	START_DATE_ORIG VARCHAR(200)		,    	
	STOP_DATE DATE,
	STOP_DATE_ORIG VARCHAR(200)		,    	
	IRB_APPROVAL_DATE DATE,
	IRB_APPROVAL_DATE_ORIG VARCHAR(200)	,    
	LOCAL_PROTOCOL_IDENTIFIER VARCHAR(200), 
	HEALTHCARE_SITE_ID BIGINT NOT NULL	,    	
	PROTOCOL_ID BIGINT NOT NULL		,    	
	SECURITY_KEY BIGINT,    		
	SOURCE VARCHAR(200)			, 
	SOURCE_EXTRACT_DATE DATE		, 
	CTOM_INSERT_DATE DATE			, 
	CTOM_UPDATE_DATE DATE			, 
	PRIMARY KEY (ID)
) 
;


ALTER TABLE HEALTHCARE_SITE_INVESTIGATOR ADD CONSTRAINT FK_INVSTGT_HEALTHCR_ST_INVSTGT 
FOREIGN KEY (INVESTIGATOR_ID) REFERENCES INVESTIGATOR (ID)
ON DELETE CASCADE;

ALTER TABLE HEALTHCARE_SITE_INVESTIGATOR ADD CONSTRAINT FK_HLTHCR_ST_HLTHCR_ST_INVSTGT 
FOREIGN KEY (HEALTHCARE_SITE_ID) REFERENCES HEALTHCARE_SITE (ID)
ON DELETE CASCADE;

ALTER TABLE PROTOCOL_STATUS ADD CONSTRAINT FK_PROTOCOL_PROTOCOL_STATUS 
FOREIGN KEY (PROTOCOL_ID) REFERENCES PROTOCOL (ID)
ON DELETE CASCADE;

ALTER TABLE STUDY_INVESTIGATOR ADD CONSTRAINT FK_PROTOCOL_STUDY_INVESTIGATOR 
FOREIGN KEY (PROTOCOL_ID) REFERENCES PROTOCOL (ID)
ON DELETE CASCADE;

ALTER TABLE STUDY_INVESTIGATOR ADD CONSTRAINT FK_INVESTIGATOR_STUDY_INVSTGTR 
FOREIGN KEY (INVESTIGATOR_ID) REFERENCES INVESTIGATOR (ID)
ON DELETE CASCADE;

ALTER TABLE STUDY_INVESTIGATOR ADD CONSTRAINT FK_STUDY_SITE_STUDY_INVSTGTR 
FOREIGN KEY (STUDY_SITE_ID) REFERENCES STUDY_SITE (ID)
ON DELETE CASCADE;


ALTER TABLE STUDY_SITE ADD CONSTRAINT FK_HEALTHCARE_SITE_STUDY_SITE 
FOREIGN KEY (HEALTHCARE_SITE_ID) REFERENCES HEALTHCARE_SITE (ID)
ON DELETE CASCADE;

ALTER TABLE STUDY_SITE ADD CONSTRAINT FK_PROTOCOL_STUDY_SITE 
FOREIGN KEY (PROTOCOL_ID) REFERENCES PROTOCOL (ID)
ON DELETE CASCADE;

