package gov.nih.nci.coppa.services.pa.interventionservice.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface InterventionServiceI {

  public gov.nih.nci.coppa.services.pa.Intervention get(gov.nih.nci.coppa.services.pa.Id id) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault ;

  public gov.nih.nci.coppa.services.pa.Intervention create(gov.nih.nci.coppa.services.pa.Intervention intervention) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault ;

  public gov.nih.nci.coppa.services.pa.Intervention update(gov.nih.nci.coppa.services.pa.Intervention intervention) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault ;

  public void delete(gov.nih.nci.coppa.services.pa.Id id) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault ;

  public gov.nih.nci.coppa.services.pa.Intervention[] search(gov.nih.nci.coppa.services.pa.Intervention searchCriteria) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault ;

}

