function FileData_Pairs(x)
{
x.t("example","pilot");
x.t("study","chemotherapy");
x.t("study","principal");
x.t("provided","study");
x.t("name","protocol");
x.t("plus","radiotherapy");
x.t("official","name");
x.t("cell","lung");
x.t("metadata","definitions");
x.t("selected","stage");
x.t("pilot","study");
x.t("radiotherapy","selected");
x.t("investigator","sponsor");
x.t("malignant","effusion");
x.t("chemotherapy","plus");
x.t("sponsor","example");
x.t("stage","iiib");
x.t("principal","investigator");
x.t("title","official");
x.t("title","metadata");
x.t("title","title");
x.t("iiib","malignant");
x.t("protocol","provided");
x.t("lung","cancer");
x.t("effusion","non-small");
x.t("definitions","title");
x.t("non-small","cell");
}
