function FileData_Pairs(x)
{
x.t("persons","registering");
x.t("trials","batch");
x.t("trials","registering");
x.t("trials","section");
x.t("trials","ctrp");
x.t("trials","using");
x.t("describes","register");
x.t("register","proprietary");
x.t("multiple","trials");
x.t("non-proprietary","trials");
x.t("new","trials");
x.t("details","section");
x.t("includes","following");
x.t("trial","details");
x.t("registering","persons");
x.t("registering","multiple");
x.t("registering","non-proprietary");
x.t("registering","new");
x.t("registering","organizations");
x.t("registering","proprietary");
x.t("completing","trial");
x.t("section","describes");
x.t("section","includes");
x.t("section","registering");
x.t("registration","site");
x.t("organizations","registering");
x.t("proprietary","trials");
x.t("proprietary","non-proprietary");
x.t("site","registering");
x.t("site","completing");
x.t("site","section");
x.t("ctrp","registration");
x.t("topics","registering");
x.t("following","topics");
x.t("using","ctrp");
}
