function FileData_Pairs(x)
{
x.t("searching","principal");
x.t("persons","register");
x.t("persons","registering");
x.t("investigators","search");
x.t("investigators","ensure");
x.t("trials","registering");
x.t("create","duplicate");
x.t("register","new");
x.t("register","investigator");
x.t("listed","system");
x.t("new","trials");
x.t("new","adding");
x.t("results","contain");
x.t("registering","persons");
x.t("registering","new");
x.t("sure","search");
x.t("duplicate","record");
x.t("name","investigator");
x.t("find","person");
x.t("search","results");
x.t("search","system\u2019s");
x.t("record","searching");
x.t("contain","name");
x.t("registered","investigators");
x.t("system\u2019s","registered");
x.t("investigator","register");
x.t("investigator","sure");
x.t("investigator","unable");
x.t("person","listed");
x.t("ensure","create");
x.t("principal","investigators");
x.t("unable","find");
x.t("system","register");
x.t("adding","principal");
}
