function FileData_Pairs(x)
{
x.t("trials","enables");
x.t("trials","registered");
x.t("trials","reporting");
x.t("trials","submitted");
x.t("community","view");
x.t("getting","started");
x.t("access","cancer");
x.t("details","existing");
x.t("new","clinical");
x.t("trial","protocols");
x.t("enables","users");
x.t("cabig","community");
x.t("researchers","access");
x.t("provides","researchers");
x.t("search","clinical");
x.t("started","nci");
x.t("cancer","clinical");
x.t("portal","getting");
x.t("portal","provides");
x.t("portal","nci");
x.t("registered","users");
x.t("members","cabig");
x.t("reporting","portal");
x.t("existing","trials");
x.t("view","details");
x.t("submit","new");
x.t("submitted","members");
x.t("nci","clinical");
x.t("users","search");
x.t("users","submit");
x.t("clinical","trials");
x.t("clinical","trial");
}
