function FileData_Pairs(x)
{
x.t("lists","trial");
x.t("required","participating");
x.t("sites","document");
x.t("element","specifications");
x.t("access","template");
x.t("document","specifications");
x.t("file","lists");
x.t("trial","registration");
x.t("trial","data");
x.t("specifications","ctrp_participating_sites_template.xls");
x.t("specifications","participating");
x.t("ctrp_participating_sites_template.xls","file");
x.t("documents","including");
x.t("participating","sites");
x.t("participating","site");
x.t("registration","templates");
x.t("collaborating","site");
x.t("template","downloading");
x.t("site","documents");
x.t("site","data");
x.t("site","information");
x.t("data","required");
x.t("data","element");
x.t("information","access");
x.t("downloading","trial");
x.t("including","collaborating");
}
