function FileData_Pairs(x)
{
x.t("trials","enables");
x.t("trials","reporting");
x.t("trials","submitted");
x.t("trials","additionally");
x.t("community","view");
x.t("program","getting");
x.t("program","provides");
x.t("program","nci");
x.t("getting","started");
x.t("access","cancer");
x.t("details","existing");
x.t("new","clinical");
x.t("trial","protocol");
x.t("enables","users");
x.t("researchers","access");
x.t("provides","researchers");
x.t("search","clinical");
x.t("started","nci");
x.t("cancer","research");
x.t("cancer","clinical");
x.t("registered","users");
x.t("members","cancer");
x.t("reporting","program");
x.t("existing","trials");
x.t("view","details");
x.t("research","community");
x.t("submit","new");
x.t("submitted","members");
x.t("nci","clinical");
x.t("users","search");
x.t("users","submit");
x.t("protocol","details");
x.t("additionally","registered");
x.t("clinical","trials");
x.t("clinical","trial");
}
