function FileData_Pairs(x)
{
x.t("trials","instructions");
x.t("trials","registering");
x.t("trials","completing");
x.t("trials","ctrp");
x.t("instructions","completing");
x.t("non-proprietary","trials");
x.t("new","trials");
x.t("trial","status/dates");
x.t("registering","new");
x.t("registering","proprietary");
x.t("completing","trial");
x.t("completing","status/dates");
x.t("section","proprietary");
x.t("registration","site");
x.t("status/dates","section");
x.t("proprietary","trials");
x.t("proprietary","non-proprietary");
x.t("site","completing");
x.t("ctrp","registration");
}
