function FileData_Pairs(x)
{
x.t("trials","instructions");
x.t("trials","registering");
x.t("trials","completing");
x.t("trials","ctrp");
x.t("instructions","completing");
x.t("summary","information");
x.t("non-proprietary","trials");
x.t("new","trials");
x.t("registering","new");
x.t("registering","proprietary");
x.t("completing","summary");
x.t("section","proprietary");
x.t("registration","site");
x.t("proprietary","trials");
x.t("proprietary","non-proprietary");
x.t("site","completing");
x.t("information","section");
x.t("information","proprietary");
x.t("ctrp","registration");
}
