function FileData_Pairs(x)
{
x.t("searching","trials");
x.t("trials","searching");
x.t("trials","working");
x.t("trials","reporting");
x.t("trials","section");
x.t("trials","nci");
x.t("describes","search");
x.t("working","search");
x.t("includes","following");
x.t("trial","details");
x.t("trial","metadata");
x.t("results","viewing");
x.t("search","results");
x.t("search","submit");
x.t("metadata","searching");
x.t("portal","section");
x.t("viewing","trial");
x.t("reporting","portal");
x.t("section","describes");
x.t("section","includes");
x.t("submit","manage");
x.t("nci","clinical");
x.t("topics","clinical");
x.t("manage","trials");
x.t("following","topics");
x.t("clinical","trials");
x.t("clinical","trial");
}
