function FileData_Pairs(x)
{
x.t("trials","reporting");
x.t("instructions","registering");
x.t("program","trial");
x.t("getting","started");
x.t("includes","following");
x.t("trial","registration");
x.t("registering","account");
x.t("account","logging");
x.t("creating","account");
x.t("logging","ctrp");
x.t("logging","system");
x.t("introduces","nci");
x.t("provides","instructions");
x.t("started","getting");
x.t("started","section");
x.t("reporting","program");
x.t("templates","resources");
x.t("section","includes");
x.t("section","introduces");
x.t("registration","templates");
x.t("registration","site");
x.t("site","creating");
x.t("site","provides");
x.t("site","ctrp");
x.t("site","using");
x.t("ctrp","trial");
x.t("ctrp","registration");
x.t("nci","clinical");
x.t("topics","ctrp");
x.t("system","section");
x.t("following","topics");
x.t("using","ctrp");
x.t("clinical","trials");
}
