function FileData_Pairs(x)
{
x.t("trials","recording");
x.t("instructions","registering");
x.t("details","complete");
x.t("details","registering");
x.t("details","recording");
x.t("details","section");
x.t("new","industrial");
x.t("trial","details");
x.t("complete","trials");
x.t("complete","trial");
x.t("registering","new");
x.t("registering","complete");
x.t("recording","trial");
x.t("section","follow");
x.t("follow","instructions");
x.t("industrial","trials");
}
