function FileData_Pairs(x)
{
x.t("trials","currently");
x.t("trials","trial");
x.t("trials","updating");
x.t("trials","section");
x.t("trials","reviewing");
x.t("describes","update");
x.t("currently","registered");
x.t("verified","trials");
x.t("verified","ctrp");
x.t("updates","updating");
x.t("includes","following");
x.t("trial","updates");
x.t("trial","amendments");
x.t("updating","accepted");
x.t("updating","amending");
x.t("accepted","trials");
x.t("registered","trials");
x.t("registered","verified");
x.t("section","describes");
x.t("section","includes");
x.t("submitting","trial");
x.t("amendments","trials");
x.t("amendments","updates");
x.t("amendments","amending");
x.t("reviewing","submitting");
x.t("ctrp","section");
x.t("topics","trial");
x.t("following","topics");
x.t("amending","verified");
x.t("amending","registered");
x.t("update","amendments");
}
