function FileData_Pairs(x)
{
x.t("trials","reporting");
x.t("instructions","registering");
x.t("user","logging");
x.t("program","registering");
x.t("program","provides");
x.t("getting","started");
x.t("new","user");
x.t("includes","following");
x.t("registering","new");
x.t("registering","account");
x.t("account","logging");
x.t("logging","nci");
x.t("logging","system");
x.t("introduces","nci");
x.t("provides","instructions");
x.t("started","getting");
x.t("started","section");
x.t("reporting","program");
x.t("section","includes");
x.t("section","introduces");
x.t("nci","clinical");
x.t("topics","nci");
x.t("system","section");
x.t("following","topics");
x.t("clinical","trials");
}
