function FileData_Pairs(x)
{
x.t("searching","trials");
x.t("trials","searching");
x.t("trials","working");
x.t("trials","section");
x.t("trials","ctrp");
x.t("describes","search");
x.t("working","search");
x.t("includes","following");
x.t("trial","details");
x.t("trial","metadata");
x.t("results","viewing");
x.t("search","results");
x.t("search","existing");
x.t("metadata","searching");
x.t("viewing","trial");
x.t("section","describes");
x.t("section","includes");
x.t("registration","site");
x.t("existing","trials");
x.t("site","section");
x.t("ctrp","registration");
x.t("topics","clinical");
x.t("following","topics");
x.t("clinical","trial");
}
