function FileData_Pairs(x)
{
x.t("sites","document");
x.t("sites","documents");
x.t("formats","requirements");
x.t("document","specifications");
x.t("document","rules");
x.t("includes","following");
x.t("requirements","participating");
x.t("provides","specifications");
x.t("specifications","section");
x.t("specifications","participating");
x.t("specifications","rules");
x.t("documents","section");
x.t("section","includes");
x.t("section","provides");
x.t("participating","sites");
x.t("participating","site");
x.t("rules","formats");
x.t("rules","treating");
x.t("collaborating","site");
x.t("site","document");
x.t("site","information");
x.t("treating","site");
x.t("information","collaborating");
x.t("topics","participating");
x.t("following","topics");
}
