function FileData_Pairs(x)
{
x.t("amendingregistered","trials");
x.t("trials","amending");
x.t("instructions","values");
x.t("submissions","completing");
x.t("verified","trials");
x.t("change","nci");
x.t("original","amended");
x.t("details","instructions");
x.t("details","updating");
x.t("details","section");
x.t("details","amending");
x.t("trial","details");
x.t("trial","identifiers");
x.t("trial","identifier");
x.t("trial","amendments");
x.t("identifiers","section");
x.t("updating","amendingregistered");
x.t("completing","trial");
x.t("number","reviewing");
x.t("cannot","change");
x.t("section","original");
x.t("section","cannot");
x.t("amended","submissions");
x.t("submitting","trial");
x.t("identifier","number");
x.t("amendments","updates");
x.t("values","completing");
x.t("reviewing","submitting");
x.t("nci","trial");
x.t("amending","verified");
x.t("amending","trial");
}
