function FileData_Pairs(x)
{
x.t("example","merck-023");
x.t("merck-023","note");
x.t("lead","organization");
x.t("lead","groups");
x.t("trials","lead");
x.t("multiple","studies");
x.t("usually","accession");
x.t("trial","number");
x.t("trial","identifier");
x.t("accession","number");
x.t("organization","usually");
x.t("organization","trial");
x.t("studies","conducted");
x.t("metadata","definitions");
x.t("inter-group","trials");
x.t("number","example");
x.t("number","multiple");
x.t("number","variation");
x.t("unique","number");
x.t("unique","identification");
x.t("conducted","grant");
x.t("(id)","lead");
x.t("(id)","metadata");
x.t("(id)","unique");
x.t("assigned","protocol");
x.t("identifier","(id)");
x.t("groups","trial");
x.t("identification","assigned");
x.t("variation","grant");
x.t("grant","number");
x.t("grant","unique");
x.t("protocol","lead");
x.t("note","inter-group");
x.t("definitions","lead");
}
