function FileData_Pairs(x)
{
x.t("managing","account");
x.t("managing","password");
x.t("instructions","modifying");
x.t("user","information");
x.t("editing","user");
x.t("resetting","password");
x.t("includes","following");
x.t("account","managing");
x.t("account","resetting");
x.t("account","section");
x.t("provides","instructions");
x.t("modifying","ctrp");
x.t("section","includes");
x.t("section","provides");
x.t("registration","site");
x.t("site","account");
x.t("information","managing");
x.t("ctrp","registration");
x.t("topics","editing");
x.t("following","topics");
x.t("password","section");
}
