function FileData_Pairs(x)
{
x.t("searching","trials");
x.t("appendix","metadata");
x.t("trials","viewing");
x.t("submitter","refer");
x.t("refer","appendix");
x.t("description","metadata");
x.t("displays","metadata");
x.t("listed","search");
x.t("details","searching");
x.t("details","viewing");
x.t("details","given");
x.t("details","view");
x.t("details","page");
x.t("link","trial");
x.t("trial","submitter");
x.t("trial","listed");
x.t("trial","details");
x.t("trial","identifier");
x.t("results","page");
x.t("entered","trial");
x.t("search","results");
x.t("metadata","entered");
x.t("metadata","definitions");
x.t("viewing","trial");
x.t("hypertext","link");
x.t("identifier","hypertext");
x.t("given","clinical");
x.t("click","associated");
x.t("view","details");
x.t("page","displays");
x.t("page","click");
x.t("nci","trial");
x.t("associated","nci");
x.t("definitions","description");
x.t("clinical","trial");
}
