function FileData_Pairs(x)
{
x.t("searching","trials");
x.t("trials","working");
x.t("trials","accessing");
x.t("trials","section");
x.t("trials","ctrp");
x.t("describes","search");
x.t("working","search");
x.t("includes","following");
x.t("trial","details");
x.t("results","viewing");
x.t("conducting","searches");
x.t("searches","ctrp");
x.t("search","results");
x.t("search","existing");
x.t("registered","trials");
x.t("viewing","trial");
x.t("accessing","registered");
x.t("section","describes");
x.t("section","includes");
x.t("registration","site");
x.t("existing","trials");
x.t("site","searching");
x.t("site","section");
x.t("ctrp","registration");
x.t("topics","conducting");
x.t("following","topics");
}
