function FileData_Pairs(x)
{
x.t("persons","registering");
x.t("trials","registering");
x.t("trials","reporting");
x.t("trials","section");
x.t("trials","nci");
x.t("trials","concurrently");
x.t("trials","using");
x.t("describes","register");
x.t("program","registering");
x.t("program","section");
x.t("register","trials");
x.t("multiple","trials");
x.t("new","trials");
x.t("includes","following");
x.t("registering","persons");
x.t("registering","trials");
x.t("registering","multiple");
x.t("registering","new");
x.t("registering","organizations");
x.t("reporting","program");
x.t("section","describes");
x.t("section","includes");
x.t("organizations","registering");
x.t("nci","clinical");
x.t("topics","registering");
x.t("following","topics");
x.t("using","nci");
x.t("clinical","trials");
}
