function FileData_Pairs(x)
{
x.t("managing","user");
x.t("managing","account");
x.t("managing","password");
x.t("instructions","modifying");
x.t("user","account");
x.t("resetting","password");
x.t("includes","following");
x.t("trial","ownership");
x.t("account","managing");
x.t("account","resetting");
x.t("account","profile");
x.t("account","section");
x.t("provides","instructions");
x.t("transferring","trial");
x.t("profile","managing");
x.t("modifying","ctrp");
x.t("ownership","section");
x.t("section","includes");
x.t("section","provides");
x.t("registration","site");
x.t("site","account");
x.t("ctrp","registration");
x.t("topics","managing");
x.t("following","topics");
x.t("password","transferring");
}
