function FileData_Pairs(x)
{
x.t("trials","printing");
x.t("keep","records");
x.t("register","trial");
x.t("new","trials");
x.t("details","page");
x.t("details","facilitate");
x.t("access","print");
x.t("printing","trial");
x.t("trial","details");
x.t("trial","scroll");
x.t("trial","page");
x.t("trial","information");
x.t("trial","order");
x.t("registering","new");
x.t("records","review");
x.t("review","trial");
x.t("review","and/or");
x.t("feature","print");
x.t("click","review");
x.t("click","print");
x.t("and/or","keep");
x.t("scroll","bottom");
x.t("page","click");
x.t("information","printing");
x.t("information","registering");
x.t("information","scroll");
x.t("information","print");
x.t("facilitate","review");
x.t("print","trial");
x.t("print","feature");
x.t("print","copy");
x.t("copy","trial");
x.t("order","access");
x.t("bottom","register");
x.t("bottom","review");
}
