function FileData_Pairs(x)
{
x.t("trials","reporting");
x.t("captures","trial");
x.t("submitter","section");
x.t("program","trial");
x.t("details","metadata");
x.t("trial","submitter");
x.t("trial","details");
x.t("trial","registration");
x.t("entered","trial");
x.t("provides","values");
x.t("metadata","entered");
x.t("metadata","definitions");
x.t("metadata","associated");
x.t("reporting","program");
x.t("section","provides");
x.t("registration","site");
x.t("site","captures");
x.t("values","definitions");
x.t("nci","clinical");
x.t("definitions","metadata");
x.t("definitions","nci");
x.t("associated","clinical");
x.t("clinical","trials");
}
