function FileData_Pairs(x)
{
x.t("trials","amending");
x.t("instructions","completing");
x.t("submissions","completing");
x.t("ind/ide","details");
x.t("ind/ide","serial");
x.t("ind/ide","section");
x.t("ind/ide","information");
x.t("verified","trials");
x.t("change","existing");
x.t("original","amended");
x.t("details","instructions");
x.t("details","amending");
x.t("completing","ind/ide");
x.t("registered","trials");
x.t("serial","number");
x.t("cannot","change");
x.t("section","original");
x.t("section","cannot");
x.t("amended","submissions");
x.t("existing","ind/ide");
x.t("information","section");
x.t("amending","ind/ide");
x.t("amending","verified");
x.t("amending","registered");
}
