function FileData_Pairs(x)
{
x.t("searching","registered");
x.t("trials","registering");
x.t("create","duplicate");
x.t("register","new");
x.t("register","organization");
x.t("listed","system");
x.t("new","trials");
x.t("new","adding");
x.t("organization","register");
x.t("organization","listed");
x.t("organization","sure");
x.t("organization","unable");
x.t("results","contain");
x.t("registering","new");
x.t("registering","organizations");
x.t("sure","search");
x.t("duplicate","record");
x.t("name","organization");
x.t("find","organization");
x.t("search","results");
x.t("search","system\u2019s");
x.t("record","searching");
x.t("contain","name");
x.t("registered","organizations");
x.t("system\u2019s","registered");
x.t("organizations","register");
x.t("organizations","registering");
x.t("organizations","search");
x.t("organizations","ensure");
x.t("organizations","egistering");
x.t("ensure","create");
x.t("egistering","organizations");
x.t("unable","find");
x.t("system","register");
x.t("adding","organizations");
}
