function FileData_Pairs(x)
{
x.t("managing","account");
x.t("managing","password");
x.t("reset","reset");
x.t("reset","password");
x.t("left","side");
x.t("resetting","password");
x.t("link","continue");
x.t("remember","password");
x.t("account","managing");
x.t("forgot","password");
x.t("creating","account");
x.t("continue","step");
x.t("request","password");
x.t("side","page");
x.t("step","creating");
x.t("login","page");
x.t("event","remember");
x.t("click","forgot");
x.t("click","log");
x.t("page","click");
x.t("pane","left");
x.t("navigation","pane");
x.t("password","managing");
x.t("password","reset");
x.t("password","resetting");
x.t("password","link");
x.t("password","request");
x.t("password","event");
x.t("password","navigation");
x.t("log","login");
}
