function FileData_Pairs(x)
{
x.t("managing","trial");
x.t("managing","organizational");
x.t("managing","site");
x.t("within","organization");
x.t("instructions","managing");
x.t("access","managing");
x.t("access","trial");
x.t("access","section");
x.t("includes","following");
x.t("trial","ownership");
x.t("organization","section");
x.t("organization","granting");
x.t("provides","instructions");
x.t("organizational","access");
x.t("ownership","managing");
x.t("ownership","administrative");
x.t("section","includes");
x.t("section","provides");
x.t("administrative","organization");
x.t("administrative","authority");
x.t("site","administration");
x.t("revoking","administrative");
x.t("granting","revoking");
x.t("removing","trial");
x.t("displaying","removing");
x.t("authority","displaying");
x.t("topics","managing");
x.t("administration","within");
x.t("following","topics");
}
