function FileData_Pairs(x)
{
x.t("trials","currently");
x.t("trials","section");
x.t("trials","reviewing");
x.t("trials","using");
x.t("trials","amending");
x.t("describes","amendments");
x.t("currently","registered");
x.t("verified","trials");
x.t("verified","ctrp");
x.t("includes","following");
x.t("trial","amendments");
x.t("registered","trials");
x.t("registered","verified");
x.t("section","describes");
x.t("section","includes");
x.t("amended","trials");
x.t("submitting","amended");
x.t("registration","site");
x.t("amendments","trials");
x.t("amendments","amending");
x.t("site","section");
x.t("submit","amended");
x.t("reviewing","submitting");
x.t("ctrp","registration");
x.t("ctrp","submit");
x.t("topics","trial");
x.t("following","topics");
x.t("using","ctrp");
x.t("amending","verified");
x.t("amending","registered");
}
