function FileData_Pairs(x)
{
x.t("trials","currently");
x.t("trials","updating");
x.t("trials","section");
x.t("trials","reviewing");
x.t("describes","update");
x.t("currently","registered");
x.t("verified","ctrp");
x.t("updates","updating");
x.t("includes","following");
x.t("trial","updates");
x.t("updating","trials");
x.t("registered","verified");
x.t("section","describes");
x.t("section","includes");
x.t("submitting","trial");
x.t("reviewing","submitting");
x.t("ctrp","section");
x.t("topics","trial");
x.t("following","topics");
x.t("update","trials");
}
