function FileData_Pairs(x)
{
x.t("email","field");
x.t("managing","account");
x.t("managing","password");
x.t("field","type");
x.t("type","e-mail");
x.t("reset","reset");
x.t("reset","password");
x.t("left","side");
x.t("resetting","password");
x.t("e-mail","address");
x.t("remember","password");
x.t("account","managing");
x.t("account","click");
x.t("forgot","password");
x.t("address","used");
x.t("request","password");
x.t("registered","account");
x.t("side","page");
x.t("event","remember");
x.t("click","forgot");
x.t("click","log");
x.t("page","click");
x.t("pane","left");
x.t("navigation","pane");
x.t("used","registered");
x.t("password","managing");
x.t("password","reset");
x.t("password","resetting");
x.t("password","link");
x.t("password","request");
x.t("password","event");
x.t("password","navigation");
x.t("log","email");
}
