function FileData_Pairs(x)
{
x.t("managing","account");
x.t("managing","password");
x.t("trials","reporting");
x.t("instructions","changing");
x.t("program","password");
x.t("change","nci");
x.t("time","logged");
x.t("reset","instructions");
x.t("resetting","password");
x.t("logged","forget");
x.t("account","managing");
x.t("reporting","program");
x.t("forget","password");
x.t("changing","password");
x.t("nci","clinical");
x.t("password","managing");
x.t("password","change");
x.t("password","time");
x.t("password","reset");
x.t("password","resetting");
x.t("clinical","trials");
}
