function FileData_Pairs(x)
{
x.t("preparing","trial");
x.t("preparing","trial-related");
x.t("trials","batch");
x.t("describes","prepare");
x.t("upload","data");
x.t("batch","upload");
x.t("batch","provides");
x.t("multiple","trials");
x.t("element","specifications");
x.t("includes","following");
x.t("trial","documents");
x.t("trial","data");
x.t("file","preparing");
x.t("registering","multiple");
x.t("provides","data");
x.t("specifications","batch");
x.t("specifications","trial");
x.t("specifications","section");
x.t("documents","trial");
x.t("documents","registering");
x.t("trial-related","documents");
x.t("section","describes");
x.t("section","includes");
x.t("prepare","trial");
x.t("data","element");
x.t("data","trial");
x.t("data","file");
x.t("data","specifications");
x.t("data","section");
x.t("topics","preparing");
x.t("following","topics");
}
