function FileData_Pairs(x)
{
x.t("trials","currently");
x.t("trials","section");
x.t("trials","reviewing");
x.t("trials","amending");
x.t("describes","amend");
x.t("currently","registered");
x.t("verified","ctrp");
x.t("includes","following");
x.t("trial","amendments");
x.t("amend","complete");
x.t("complete","trials");
x.t("registered","verified");
x.t("section","describes");
x.t("section","includes");
x.t("submitting","trial");
x.t("amendments","amending");
x.t("reviewing","submitting");
x.t("ctrp","section");
x.t("topics","trial");
x.t("following","topics");
x.t("amending","trials");
}
