function FileData_Pairs(x)
{
x.t("amendingregistered","trials");
x.t("trials","amending");
x.t("instructions","completing");
x.t("submissions","completing");
x.t("verified","trials");
x.t("original","amended");
x.t("updating","amendingregistered");
x.t("completing","regulatory");
x.t("section","original");
x.t("amended","submissions");
x.t("formation","instructions");
x.t("regulatory","section");
x.t("regulatory","formation");
x.t("regulatory","information");
x.t("information","updating");
x.t("information","amending");
x.t("amending","verified");
x.t("amending","regulatory");
}
