package gov.nih.nci.coppa.services.pa.documentworkflowstatusservice.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface DocumentWorkflowStatusServiceConstantsBase {
	public static final String SERVICE_NS = "http://enterpriseservices.nci.nih.gov/PAServices/DocumentWorkflowStatusService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "DocumentWorkflowStatusServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "DocumentWorkflowStatusServiceResourceProperties");
	
}
