DROP TABLE CSM_FILTER_CLAUSE CASCADE
/
DROP TABLE CSM_APPLICATION CASCADE
/
DROP TABLE CSM_GROUP CASCADE
/
DROP TABLE CSM_PRIVILEGE CASCADE
/
DROP TABLE CSM_PROTECTION_ELEMENT CASCADE
/
DROP TABLE CSM_PROTECTION_GROUP CASCADE
/
DROP TABLE CSM_PG_PE CASCADE
/
DROP TABLE CSM_ROLE CASCADE
/
DROP TABLE  CSM_ROLE_PRIVILEGE CASCADE
/
DROP TABLE  CSM_USER CASCADE
/
DROP TABLE  CSM_USER_GROUP CASCADE
/
DROP TABLE  CSM_USER_GROUP_ROLE_PG CASCADE
/
DROP TABLE  CSM_USER_PE CASCADE
/
DROP SEQUENCE  CSM_FILTER_CLAUSE_SEQ
/
DROP SEQUENCE  CSM_APPLICATI_APPLICATION__SEQ
/
DROP SEQUENCE  CSM_GROUP_GROUP_ID_SEQ
/
DROP SEQUENCE  CSM_PG_PE_PG_PE_ID_SEQ
/
DROP SEQUENCE  CSM_PRIVILEGE_PRIVILEGE_ID_SEQ
/
DROP SEQUENCE  CSM_PROTECTIO_PROTECTION_E_SEQ
/
DROP SEQUENCE  CSM_PROTECTIO_PROTECTION_G_SEQ
/
DROP SEQUENCE  CSM_ROLE_ROLE_ID_SEQ
/
DROP SEQUENCE  CSM_ROLE_PRIV_ROLE_PRIVILE_SEQ
/
DROP SEQUENCE  CSM_USER_USER_ID_SEQ
/
DROP SEQUENCE  CSM_USER_GROU_USER_GROUP_I_SEQ
/
DROP SEQUENCE  CSM_USER_GROU_USER_GROUP_R_SEQ
/
DROP SEQUENCE  CSM_USER_PE_USER_PROTECTIO_SEQ
/
