INSERT INTO DISEASE (IDENTIFIER, DISEASE_CODE, NT_TERM_IDENTIFIER, PREFERRED_NAME, MENU_DISPLAY_NAME, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (1, 'DCODE 001', 'TERMID 001', 'Leg Cancer', 'LEG', 'ACTIVE', '2008-01-01');

INSERT INTO DISEASE (IDENTIFIER, DISEASE_CODE, NT_TERM_IDENTIFIER, PREFERRED_NAME, MENU_DISPLAY_NAME, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (2, 'DCODE 002', 'TERMID 002', 'Knee Cancer', 'KNEE', 'ACTIVE', '2008-01-01');
INSERT INTO DISEASE_ALTERNAME (DISEASE_IDENTIFIER, ALTERNATE_NAME, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (2, 'Patella Cancer', 'ACTIVE', '2008-01-01');
INSERT INTO DISEASE_PARENT (DISEASE_IDENTIFIER, PARENT_DISEASE_IDENTIFIER, PARENT_DISEASE_CODE, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (2, 1, 'PCODE 002', 'ACTIVE', '2008-01-01');

INSERT INTO DISEASE (IDENTIFIER, DISEASE_CODE, NT_TERM_IDENTIFIER, PREFERRED_NAME, MENU_DISPLAY_NAME, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (3, 'DCODE 003', 'TERMID 003', 'Foot Cancer', 'FOOT', 'ACTIVE', '2008-01-01');
INSERT INTO DISEASE_PARENT (DISEASE_IDENTIFIER, PARENT_DISEASE_IDENTIFIER, PARENT_DISEASE_CODE, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (3, 1, 'PCODE 003', 'ACTIVE', '2008-01-01');

INSERT INTO DISEASE (IDENTIFIER, DISEASE_CODE, NT_TERM_IDENTIFIER, PREFERRED_NAME, MENU_DISPLAY_NAME, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (4, 'DCODE 004', 'TERMID 004', 'Heel Cancer', 'HEEL', 'ACTIVE', '2008-01-01');
INSERT INTO DISEASE_PARENT (DISEASE_IDENTIFIER, PARENT_DISEASE_IDENTIFIER, PARENT_DISEASE_CODE, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (4, 3, 'PCODE 004', 'ACTIVE', '2008-01-01');

INSERT INTO DISEASE (IDENTIFIER, DISEASE_CODE, NT_TERM_IDENTIFIER, PREFERRED_NAME, MENU_DISPLAY_NAME, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (5, 'DCODE 005', 'TERMID 005', 'Toe Cancer', 'TOE', 'ACTIVE', '2008-01-01');
INSERT INTO DISEASE_ALTERNAME (DISEASE_IDENTIFIER, ALTERNATE_NAME, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (5, 'Digit Cancer', 'ACTIVE', '2008-01-01');
INSERT INTO DISEASE_ALTERNAME (DISEASE_IDENTIFIER, ALTERNATE_NAME, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (5, 'Phalanx Cancer', 'ACTIVE', '2008-01-01');
INSERT INTO DISEASE_PARENT (DISEASE_IDENTIFIER, PARENT_DISEASE_IDENTIFIER, PARENT_DISEASE_CODE, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (5, 3, 'PCODE 005', 'ACTIVE', '2008-01-01');

