DELETE FROM INTERVENTION_ALTERNATE_NAME;
DELETE FROM INTERVENTION;

INSERT INTO INTERVENTION (ID, NAME, TYPE_CODE, DESCRIPTION_TEXT, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (1, 'docetaxel/erlotinib', 'DRUG', 'NCI Thesaurus Vocabulary', 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (1, 'OSI774/TXT', 1, 'ACTIVE', '2008-01-01');

INSERT INTO INTERVENTION (ID, NAME, TYPE_CODE, DESCRIPTION_TEXT, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (2, 'fluorouracilleucovorin calcium/UCN-01', 'DRUG', 'NCI Thesaurus Vocabulary', 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (2, 'CF/5-FU/UCN 01', 2, 'ACTIVE', '2008-01-01');

INSERT INTO INTERVENTION (ID, NAME, TYPE_CODE, DESCRIPTION_TEXT, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (3, '18F-fluoromisonidazole', 'DRUG', 'Protocol: MDA-CCC-0327', 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (3, '18F-Fluoromisonidazole', 3, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (4, '18F-MISO', 3, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (5, '18F-misonidazole', 3, 'ACTIVE', '2008-01-01');

INSERT INTO INTERVENTION (ID, NAME, TYPE_CODE, DESCRIPTION_TEXT, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (4, 'proteomic profiling', 'GENETIC', 'molecular genetic technique', 'ACTIVE', '2008-01-01');

INSERT INTO INTERVENTION (ID, NAME, TYPE_CODE, DESCRIPTION_TEXT, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (5, 'melastatin gene', 'GENETIC', NULL, 'ACTIVE', '2008-01-01');

INSERT INTO INTERVENTION (ID, NAME, TYPE_CODE, DESCRIPTION_TEXT, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (6, 'IGFBP3', 'GENETIC', NULL, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (6, 'insulin-like growth factor binding protein 3', 6, 'ACTIVE', '2008-01-01');

INSERT INTO INTERVENTION (ID, NAME, TYPE_CODE, DESCRIPTION_TEXT, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (7, 'Therapeutic_Touch', 'OTHER', NULL, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (7, 'Healing Touch', 7, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (8, 'Therapeutic Touch', 7, 'ACTIVE', '2008-01-01');

INSERT INTO INTERVENTION (ID, NAME, TYPE_CODE, DESCRIPTION_TEXT, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (8, 'Behavioral Dietary Intervention', 'BEHAVIORAL', NULL, 'ACTIVE', '2008-01-01');

INSERT INTO INTERVENTION (ID, NAME, TYPE_CODE, DESCRIPTION_TEXT, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (9, 'American_Stop_Smoking_Intervention_for_Cancer_Prevention', 'BEHAVIORAL', NULL, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (9, 'American Stop Smoking Intervention for Cancer Prevention', 9, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (10, 'Smoking, Tobacco, and Cancer-ASSIST', 9, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (11, 'ASSIST', 9, 'ACTIVE', '2008-01-01');

INSERT INTO INTERVENTION (ID, NAME, TYPE_CODE, DESCRIPTION_TEXT, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (10, 'Gamma_Knife', 'PROCEDURE_SURGERY', NULL, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (12, 'Gamma Knife Radiosurgery', 10, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (13, 'gamma knife', 10, 'ACTIVE', '2008-01-01');

INSERT INTO INTERVENTION (ID, NAME, TYPE_CODE, DESCRIPTION_TEXT, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (11, 'Human_Papilloma_Virus_Vaccine', 'BIOLOGICAL_VACCINE', NULL, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (14, 'HPV Vaccine', 11, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (15, 'Human Papilloma Virus Vaccine', 11, 'ACTIVE', '2008-01-01');

INSERT INTO INTERVENTION (ID, NAME, TYPE_CODE, DESCRIPTION_TEXT, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (12, 'Gastroscope', 'DEVICE', NULL, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (16, 'gastroscope', 12, 'ACTIVE', '2008-01-01');

INSERT INTO INTERVENTION (ID, NAME, TYPE_CODE, DESCRIPTION_TEXT, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (13, 'Oligosaccharide', 'DIETARY_SUPPLEMENT', 'NCI|Diagnostic or therapeutic use of non-ionizing radiation', 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (17, 'Oligosaccharide', 13, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (18, 'Oligosaccharides', 13, 'ACTIVE', '2008-01-01');

INSERT INTO INTERVENTION (ID, NAME, TYPE_CODE, DESCRIPTION_TEXT, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (14, 'Non-Ionizing_Radiation_DX_or_RX', 'RADIATION', NULL, 'ACTIVE', '2008-01-01');
INSERT INTO INTERVENTION_ALTERNATE_NAME (ID, NAME, INTERVENTION_ID, STATUS_CODE, STATUS_DATE_RANGE_LOW)
    VALUES (19, 'Radiation, Non-Ionizing DX or RX', 14, 'ACTIVE', '2008-01-01');


