package gov.nih.nci.coppa.services.pa.interventionservice.service;

import gov.nih.nci.coppa.services.pa.Intervention;
import gov.nih.nci.coppa.services.pa.grid.GenericPaGridServiceImpl;
import gov.nih.nci.coppa.services.pa.grid.dto.pa.InterventionTransformer;
import gov.nih.nci.coppa.services.pa.grid.dto.pa.faults.FaultUtil;
import gov.nih.nci.coppa.services.pa.grid.remote.InvokeInterventionEjb;
import gov.nih.nci.pa.iso.dto.InterventionDTO;

import java.rmi.RemoteException;
import java.util.List;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

/**
 * Intervention service implementation.  Translates XML-level objects to DTOs to call EJBs.
 *
 * @created by Introduce Toolkit version 1.3
 *
 */
public class InterventionServiceImpl extends InterventionServiceImplBase {
    private static final Logger logger = LogManager.getLogger(InterventionServiceImpl.class);
    private final InvokeInterventionEjb interventionService = new InvokeInterventionEjb();
    private GenericPaGridServiceImpl<InterventionDTO, Intervention> impl =
            new GenericPaGridServiceImpl<InterventionDTO, Intervention>(Intervention.class, InterventionDTO.class);

	public InterventionServiceImpl() throws RemoteException {
		super();
	}

  public gov.nih.nci.coppa.services.pa.Intervention get(gov.nih.nci.iso21090.extensions.Id id) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
      return impl.get(id);
  }

  public gov.nih.nci.coppa.services.pa.Intervention create(gov.nih.nci.coppa.services.pa.Intervention intervention) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.pa.Intervention update(gov.nih.nci.coppa.services.pa.Intervention intervention) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void delete(gov.nih.nci.iso21090.extensions.Id id) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.pa.Intervention[] search(gov.nih.nci.coppa.services.pa.Intervention searchCriteria) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
      try {
          InterventionDTO interventionDto = InterventionTransformer.INSTANCE.toDto(searchCriteria);
          List<InterventionDTO> results = interventionService.search(interventionDto);
          return InterventionTransformer.INSTANCE.convert(results);
      } catch (Exception e) {
          logger.error(e.getMessage(), e);
          throw FaultUtil.reThrowRemote(e);
      }
  }

}

