function FileData_Pairs(x)
{
x.t("treatment","regimen");
x.t("treatment","data");
x.t("create","new");
x.t("refer","adding");
x.t("instructions","surgery");
x.t("surgical","procedure");
x.t("working","treatment");
x.t("new","treatment");
x.t("includes","surgical");
x.t("regimen","records");
x.t("regimen","select");
x.t("cycle","records");
x.t("name","date");
x.t("records","instructions");
x.t("records","adding");
x.t("select","existing");
x.t("submitting","surgery");
x.t("existing","submit");
x.t("surgery","data");
x.t("surgery","information");
x.t("data","create");
x.t("data","refer");
x.t("data","working");
x.t("data","submitting");
x.t("information","includes");
x.t("submit","surgery");
x.t("procedure","name");
x.t("date","surgery");
x.t("adding","treatment");
x.t("adding","cycle");
}
