function FileData_Pairs(x)
{
x.t("deleting","lesion");
x.t("permanently","deleted");
x.t("working","outcome");
x.t("icon","record");
x.t("delete","icon");
x.t("delete","record");
x.t("delete","existing");
x.t("enables","delete");
x.t("records","deleting");
x.t("records","working");
x.t("records","delete");
x.t("records","nci");
x.t("record","permanently");
x.t("record","click");
x.t("assessment","records");
x.t("assessment","data");
x.t("portal","enables");
x.t("submitting","lesion");
x.t("outcome","data");
x.t("click","delete");
x.t("existing","lesion");
x.t("lesion","records");
x.t("lesion","assessment");
x.t("data","deleting");
x.t("data","submitting");
x.t("nci","outcomes");
x.t("outcomes","portal");
}
