function FileData_Pairs(x)
{
x.t("treatment","regimen");
x.t("treatment","data");
x.t("create","new");
x.t("refer","adding");
x.t("instructions","drug/biologics");
x.t("dosing","details");
x.t("working","treatment");
x.t("new","treatment");
x.t("includes","intervention");
x.t("drug/biologic","data");
x.t("regimen","records");
x.t("regimen","select");
x.t("cycle","records");
x.t("name","dosing");
x.t("records","instructions");
x.t("records","adding");
x.t("select","existing");
x.t("submitting","drug/biologics");
x.t("drug/biologics","data");
x.t("existing","submit");
x.t("intervention","name");
x.t("data","create");
x.t("data","refer");
x.t("data","working");
x.t("data","includes");
x.t("data","submitting");
x.t("submit","drug/biologic");
x.t("adding","treatment");
x.t("adding","cycle");
}
