function FileData_Pairs(x)
{
x.t("treatment","record");
x.t("course","treatment");
x.t("current","evaluation");
x.t("working","outcome");
x.t("new","disease");
x.t("disease","evaluation");
x.t("creating","new");
x.t("record","throughout");
x.t("record","adding");
x.t("record","contains");
x.t("may","disease");
x.t("submitting","disease");
x.t("outcome","data");
x.t("throughout","course");
x.t("evaluation","records");
x.t("evaluation","record");
x.t("evaluation","data");
x.t("evaluation","information");
x.t("data","working");
x.t("data","submitting");
x.t("data","patient");
x.t("data","update");
x.t("information","creating");
x.t("patient","may");
x.t("adding","disease");
x.t("contains","current");
x.t("update","evaluation");
}
