function FileData_Pairs(x)
{
x.t("deleting","existing");
x.t("instructions","working");
x.t("working","baseline");
x.t("working","patient");
x.t("status","data");
x.t("diagnosis","data");
x.t("performance","status");
x.t("provides","instructions");
x.t("updating","deleting");
x.t("prior","therapies");
x.t("staging","data");
x.t("section","provides");
x.t("section","include");
x.t("submitting","diagnosis");
x.t("submitting","performance");
x.t("submitting","updating");
x.t("submitting","prior");
x.t("submitting","staging");
x.t("submitting","pathology");
x.t("pathology","data");
x.t("existing","patient");
x.t("include","baseline");
x.t("baseline","data");
x.t("baseline","information");
x.t("therapies","data");
x.t("data","working");
x.t("data","section");
x.t("data","submitting");
x.t("data","topics");
x.t("information","including");
x.t("patient","baseline");
x.t("topics","section");
x.t("including","submitting");
}
