function FileData_Pairs(x)
{
x.t("\u03b7\u03bf\u03c9","reset");
x.t("reset","\u03b7\u03bf\u03c9");
x.t("reset","password");
x.t("left","side");
x.t("resetting","password");
x.t("getting","started");
x.t("link","continue");
x.t("remember","password");
x.t("forgot","password");
x.t("creating","account");
x.t("logging","nci");
x.t("continue","step");
x.t("started","logging");
x.t("request","password");
x.t("portal","resetting");
x.t("side","page");
x.t("step","creating");
x.t("login","page");
x.t("event","remember");
x.t("click","forgot");
x.t("click","log");
x.t("page","click");
x.t("pane","left");
x.t("nci","outcomes");
x.t("navigation","pane");
x.t("password","reset");
x.t("password","resetting");
x.t("password","getting");
x.t("password","link");
x.t("password","request");
x.t("password","event");
x.t("password","navigation");
x.t("outcomes","portal");
x.t("log","login");
}
