function FileData_Pairs(x)
{
x.t("working","outcome");
x.t("icon","follow");
x.t("enables","update");
x.t("edit","icon");
x.t("updating","lesion");
x.t("records","working");
x.t("records","updating");
x.t("records","nci");
x.t("records","modify");
x.t("record","click");
x.t("assessment","records");
x.t("assessment","data");
x.t("portal","enables");
x.t("submitting","lesion");
x.t("follow","steps");
x.t("steps","adding");
x.t("outcome","data");
x.t("click","edit");
x.t("existing","record");
x.t("existing","lesion");
x.t("lesion","records");
x.t("lesion","assessment");
x.t("data","updating");
x.t("data","submitting");
x.t("nci","outcomes");
x.t("outcomes","portal");
x.t("adding","lesion");
x.t("modify","existing");
x.t("update","existing");
}
