function FileData_Pairs(x)
{
x.t("deleting","existing");
x.t("instructions","working");
x.t("working","outcome");
x.t("working","patient");
x.t("disease","evaluation");
x.t("provides","instructions");
x.t("updating","deleting");
x.t("assessment","data");
x.t("section","provides");
x.t("section","include");
x.t("submitting","disease");
x.t("submitting","updating");
x.t("submitting","lesion");
x.t("submitting","death");
x.t("outcome","data");
x.t("outcome","information");
x.t("existing","patient");
x.t("include","outcome");
x.t("evaluation","data");
x.t("data","working");
x.t("data","section");
x.t("data","submitting");
x.t("data","topics");
x.t("information","including");
x.t("lesion","assessment");
x.t("patient","outcome");
x.t("topics","section");
x.t("death","information");
x.t("including","submitting");
}
