function FileData_Pairs(x)
{
x.t("trials","reporting");
x.t("treatment","sites");
x.t("treatment","site");
x.t("describes","look");
x.t("program","(ctrp)");
x.t("sites","adding");
x.t("working","treatment");
x.t("look","organizations");
x.t("add","treatment");
x.t("looking","treatment");
x.t("records","working");
x.t("records","section");
x.t("records","topics");
x.t("(ctrp)","add");
x.t("registered","clinical");
x.t("reporting","program");
x.t("section","describes");
x.t("section","include");
x.t("organizations","registered");
x.t("include","looking");
x.t("site","records");
x.t("topics","section");
x.t("adding","treatment");
x.t("clinical","trials");
}
