function FileData_Pairs(x)
{
x.t("trials","reporting");
x.t("describes","look");
x.t("topic","looking");
x.t("program","(ctrp)");
x.t("working","physician");
x.t("look","physicians");
x.t("physicians","registered");
x.t("physicians","adding");
x.t("includes","following");
x.t("add","physician");
x.t("looking","registered");
x.t("records","working");
x.t("records","section");
x.t("(ctrp)","add");
x.t("registered","physicians");
x.t("registered","clinical");
x.t("reporting","program");
x.t("section","describes");
x.t("section","includes");
x.t("physician","records");
x.t("following","topic");
x.t("adding","physician");
x.t("clinical","trials");
}
