function FileData_Pairs(x)
{
x.t("example","clinicians");
x.t("measure","tumor");
x.t("treatment","course");
x.t("treatment","during");
x.t("treatment","order");
x.t("course","treatment");
x.t("working","outcome");
x.t("obtained","end");
x.t("times","throughout");
x.t("response","measurement");
x.t("during","post-treatment");
x.t("clinicians","may");
x.t("tumor","times");
x.t("records","typically");
x.t("formal","assessment");
x.t("assessment","response");
x.t("may","measure");
x.t("added","patient\u2019s");
x.t("end","treatment");
x.t("outcome","records");
x.t("outcome","data");
x.t("follow-up","example");
x.t("throughout","course");
x.t("post-treatment","phase");
x.t("data","working");
x.t("data","outcome");
x.t("measurement","added");
x.t("phase","follow-up");
x.t("typically","obtained");
x.t("order","formal");
x.t("patient\u2019s","record");
}
