function FileData_Pairs(x)
{
x.t("treatment","regimen");
x.t("treatment","data");
x.t("create","new");
x.t("refer","adding");
x.t("instructions","radiation");
x.t("dosing","details");
x.t("working","treatment");
x.t("type","dosing");
x.t("new","treatment");
x.t("details","refer");
x.t("includes","radiation");
x.t("regimen","records");
x.t("regimen","select");
x.t("cycle","records");
x.t("records","instructions");
x.t("records","adding");
x.t("select","existing");
x.t("submitting","radiation");
x.t("existing","submit");
x.t("radiation","type");
x.t("radiation","details");
x.t("radiation","data");
x.t("data","create");
x.t("data","working");
x.t("data","includes");
x.t("data","submitting");
x.t("submit","radiation");
x.t("adding","treatment");
x.t("adding","cycle");
}
