function FileData_Pairs(x)
{
x.t("searching","study");
x.t("study","subject");
x.t("study","subjects");
x.t("trials","currently");
x.t("trials","using");
x.t("accrual","section");
x.t("describes","amendments");
x.t("currently","registered");
x.t("deleting","study");
x.t("subject","records");
x.t("working","study");
x.t("verified","ctrp");
x.t("includes","following");
x.t("updating","study");
x.t("records","deleting");
x.t("subjects","working");
x.t("subjects","updating");
x.t("subjects","section");
x.t("subjects","adding");
x.t("registered","verified");
x.t("section","describes");
x.t("section","includes");
x.t("amended","trials");
x.t("amendments","trials");
x.t("submit","amended");
x.t("ctrp","accrual");
x.t("ctrp","submit");
x.t("topics","searching");
x.t("following","topics");
x.t("using","ctrp");
x.t("adding","study");
}
