package gov.nih.nci.coppa.services.structuralroles.healthcareprovider.service.globus;

import gov.nih.nci.coppa.services.structuralroles.healthcareprovider.service.HealthCareProviderImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the CoreServicesImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class HealthCareProviderProviderImpl{
	
	HealthCareProviderImpl impl;
	
	public HealthCareProviderProviderImpl() throws RemoteException {
		impl = new HealthCareProviderImpl();
	}
	

    public gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.CreateResponse create(gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.CreateRequest params) throws RemoteException, gov.nih.nci.coppa.po.faults.EntityValidationFault {
    gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.CreateResponse boxedResult = new gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.CreateResponse();
    boxedResult.setId(impl.create(params.getHealthCareProvider().getHealthCareProvider()));
    return boxedResult;
  }

    public gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.GetByIdResponse getById(gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.GetByIdRequest params) throws RemoteException, gov.nih.nci.coppa.po.faults.NullifiedRoleFault {
    gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.GetByIdResponse boxedResult = new gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.GetByIdResponse();
    boxedResult.setHealthCareProvider(impl.getById(params.getId().getId()));
    return boxedResult;
  }

    public gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.GetByIdsResponse getByIds(gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.GetByIdsRequest params) throws RemoteException, gov.nih.nci.coppa.po.faults.NullifiedRoleFault {
    gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.GetByIdsResponse boxedResult = new gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.GetByIdsResponse();
    boxedResult.setHealthCareProvider(impl.getByIds(params.getId().getId()));
    return boxedResult;
  }

    public gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.SearchResponse search(gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.SearchRequest params) throws RemoteException, gov.nih.nci.coppa.po.faults.TooManyResultsFault {
    gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.SearchResponse boxedResult = new gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.SearchResponse();
    boxedResult.setHealthCareProvider(impl.search(params.getHealthCareProvider().getHealthCareProvider()));
    return boxedResult;
  }

    public gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.UpdateResponse update(gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.UpdateRequest params) throws RemoteException, gov.nih.nci.coppa.po.faults.EntityValidationFault {
    gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.UpdateResponse boxedResult = new gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.UpdateResponse();
    impl.update(params.getHealthCareProvider().getHealthCareProvider());
    return boxedResult;
  }

    public gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.UpdateStatusResponse updateStatus(gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.UpdateStatusRequest params) throws RemoteException, gov.nih.nci.coppa.po.faults.EntityValidationFault {
    gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.UpdateStatusResponse boxedResult = new gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.UpdateStatusResponse();
    impl.updateStatus(params.getTargetId().getId(),params.getStatusCode().getCd());
    return boxedResult;
  }

    public gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.ValidateResponse validate(gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.ValidateRequest params) throws RemoteException {
    gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.ValidateResponse boxedResult = new gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.ValidateResponse();
    boxedResult.setStringMap(impl.validate(params.getHealthCareProvider().getHealthCareProvider()));
    return boxedResult;
  }

    public gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.QueryResponse query(gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.QueryRequest params) throws RemoteException, gov.nih.nci.coppa.po.faults.TooManyResultsFault {
    gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.QueryResponse boxedResult = new gov.nih.nci.coppa.services.structuralroles.healthcareprovider.stubs.QueryResponse();
    boxedResult.setHealthCareProvider(impl.query(params.getHealthCareProvider().getHealthCareProvider(),params.getLimitOffset().getLimitOffset()));
    return boxedResult;
  }

}
