package gov.nih.nci.coppa.services.outcomes.performedobservationresult.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class PerformedObservationResultImpl extends PerformedObservationResultImplBase {

	
	public PerformedObservationResultImpl() throws RemoteException {
		super();
	}
	
  public gov.nih.nci.coppa.services.outcomes.PerformedObservationResult get(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedObservationResult create(gov.nih.nci.coppa.services.outcomes.PerformedObservationResult performedObservationResult) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedObservationResult update(gov.nih.nci.coppa.services.outcomes.PerformedObservationResult performedObservationResult) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void delete(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedObservationResult[] getPerformedObservationResultByPerformedActivity(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedHistopathology[] getPerformedHistopathologyByPerformedActivity(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedHistopathology getPerformedHistopathology(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedHistopathology createPerformedHistopathology(gov.nih.nci.coppa.services.outcomes.PerformedHistopathology performedHistopathology) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedHistopathology updatePerformedHistopathology(gov.nih.nci.coppa.services.outcomes.PerformedHistopathology performedHistopathology) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedDiagnosis[] getPerformedDiagnosisByPerformedActivity(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedDiagnosis getPerformedDiagnosis(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedDiagnosis createPerformedDiagnosis(gov.nih.nci.coppa.services.outcomes.PerformedDiagnosis performedDiagnosis) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedDiagnosis updatePerformedDiagnosis(gov.nih.nci.coppa.services.outcomes.PerformedDiagnosis performedDiagnosis) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedImage[] getPerformedImageByPerformedActivity(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedImage getPerformedImage(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedImage createPerformedImage(gov.nih.nci.coppa.services.outcomes.PerformedImage performedImage) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedImage updatePerformedImage(gov.nih.nci.coppa.services.outcomes.PerformedImage performedImage) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedClinicalResult[] getPerformedClinicalResultByPerformedActivity(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedClinicalResult getPerformedClinicalResult(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedClinicalResult createPerformedClinicalResult(gov.nih.nci.coppa.services.outcomes.PerformedClinicalResult performedClinicalResult) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedClinicalResult updatePerformedClinicalResult(gov.nih.nci.coppa.services.outcomes.PerformedClinicalResult performedClinicalResult) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedMedicalHistoryResult[] getPerformedMedicalHistoryResultByPerformedActivity(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedMedicalHistoryResult getPerformedMedicalHistoryResult(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedMedicalHistoryResult createPerformedMedicalHistoryResult(gov.nih.nci.coppa.services.outcomes.PerformedMedicalHistoryResult performedMedicalHistoryResult) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedMedicalHistoryResult updatePerformedMedicalHistoryResult(gov.nih.nci.coppa.services.outcomes.PerformedMedicalHistoryResult performedMedicalHistoryResult) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedLesionDescription[] getPerformedLesionDescriptionByPerformedActivity(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedLesionDescription getPerformedLesionDescription(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedLesionDescription createPerformedLesionDescription(gov.nih.nci.coppa.services.outcomes.PerformedLesionDescription performedLesionDescription) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.outcomes.PerformedLesionDescription updatePerformedLesionDescription(gov.nih.nci.coppa.services.outcomes.PerformedLesionDescription performedLesionDescription) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

