function FileData_Pairs(x)
{
x.t("trials","reporting");
x.t("accrual","site");
x.t("accrual","ctrp");
x.t("instructions","creating");
x.t("program","accrual");
x.t("getting","started");
x.t("includes","following");
x.t("creating","account");
x.t("account","logging");
x.t("logging","ctrp");
x.t("logging","system");
x.t("requesting","accrual");
x.t("introduces","nci");
x.t("provides","instructions");
x.t("started","getting");
x.t("started","section");
x.t("reporting","program");
x.t("section","includes");
x.t("section","introduces");
x.t("site","account");
x.t("site","requesting");
x.t("site","provides");
x.t("ctrp","accrual");
x.t("nci","clinical");
x.t("topics","ctrp");
x.t("system","section");
x.t("following","topics");
x.t("clinical","trials");
}
