function FileData_Pairs(x)
{
x.t("searching","trials");
x.t("provide","new");
x.t("trials","searching");
x.t("trials","navigating");
x.t("trials","accessing");
x.t("trials","section");
x.t("trials","ctrp");
x.t("accrual","site");
x.t("accrual","data");
x.t("lists","viewing");
x.t("describes","ctrp");
x.t("navigating","trial");
x.t("listed","trials");
x.t("want","provide");
x.t("new","updated");
x.t("includes","following");
x.t("trial","lists");
x.t("trial","details");
x.t("search","select");
x.t("select","trials");
x.t("viewing","trial");
x.t("accessing","trials");
x.t("section","describes");
x.t("section","includes");
x.t("selecting","listed");
x.t("site","search");
x.t("data","section");
x.t("ctrp","accrual");
x.t("ctrp","want");
x.t("topics","selecting");
x.t("following","topics");
x.t("updated","accrual");
}
