function FileData_Pairs(x)
{
x.t("trials","viewing");
x.t("listed","search");
x.t("details","viewing");
x.t("details","accessing");
x.t("details","given");
x.t("details","view");
x.t("trial","listed");
x.t("trial","details");
x.t("trial","identifier");
x.t("results","page");
x.t("search","results");
x.t("viewing","trial");
x.t("accessing","trials");
x.t("hypertext","link");
x.t("identifier","hypertext");
x.t("given","clinical");
x.t("click","associated");
x.t("view","details");
x.t("page","click");
x.t("nci","trial");
x.t("associated","nci");
x.t("clinical","trial");
}
