function FileData_Pairs(x)
{
x.t("searching","study");
x.t("study","subject");
x.t("study","subjects");
x.t("trials","section");
x.t("describes","search");
x.t("deleting","study");
x.t("subject","records");
x.t("working","study");
x.t("delete","study");
x.t("includes","following");
x.t("add","update");
x.t("updating","study");
x.t("search","add");
x.t("records","searching");
x.t("records","deleting");
x.t("records","associated");
x.t("subjects","working");
x.t("subjects","updating");
x.t("subjects","section");
x.t("subjects","adding");
x.t("section","describes");
x.t("section","includes");
x.t("specific","clinical");
x.t("reviewing","study");
x.t("topics","reviewing");
x.t("following","topics");
x.t("adding","study");
x.t("associated","specific");
x.t("update","delete");
x.t("clinical","trials");
}
