function FileData_Pairs(x)
{
x.t("accrual","submission");
x.t("accrual","submissions");
x.t("accrual","records");
x.t("accrual","information");
x.t("trials","registered");
x.t("describes","review");
x.t("submission","records");
x.t("submissions","working");
x.t("submissions","section");
x.t("working","accrual");
x.t("new","accrual");
x.t("includes","following");
x.t("complete","accrual");
x.t("creating","submitting");
x.t("records","creating");
x.t("records","completing");
x.t("completing","accrual");
x.t("review","submit");
x.t("registered","ctrp");
x.t("section","describes");
x.t("section","includes");
x.t("submitting","new");
x.t("information","trials");
x.t("submit","update");
x.t("reviewing","accrual");
x.t("ctrp","section");
x.t("topics","reviewing");
x.t("following","topics");
x.t("update","complete");
}
