package gov.nih.nci.coppa.services.pa.studyindideservice.service;

import gov.nih.nci.coppa.iso.Ii;
import gov.nih.nci.coppa.services.grid.dto.transform.DtoTransformException;
import gov.nih.nci.coppa.services.grid.dto.transform.iso.IITransformer;
import gov.nih.nci.coppa.services.pa.StudyIndlde;
import gov.nih.nci.coppa.services.pa.grid.dto.pa.StudyIndldeTransformer;
import gov.nih.nci.coppa.services.pa.grid.dto.pa.faults.FaultUtil;
import gov.nih.nci.coppa.services.pa.grid.remote.InvokeStudyIndldeEjb;
import gov.nih.nci.pa.iso.dto.StudyIndldeDTO;

import java.rmi.RemoteException;
import java.util.List;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

/**
 * Implementation of the StudyIndIdeService. Dispatches to the remote EJBs and the Transformers.
 *
 * @author mshestopalov
 */
public class StudyIndIdeServiceImpl extends StudyIndIdeServiceImplBase {

    private static final Logger logger = LogManager.getLogger(StudyIndIdeServiceImpl.class);
    private final InvokeStudyIndldeEjb studyIndIdeService = new InvokeStudyIndldeEjb();
    public StudyIndIdeServiceImpl() throws RemoteException {
        super();
    }

    private StudyIndlde[] convert(List<StudyIndldeDTO> dtosList) throws DtoTransformException {
        if (dtosList == null) {
            return null;
        }
        StudyIndlde[] result = null;
        result = new StudyIndlde[dtosList.size()];
        int i = 0;
        for (StudyIndldeDTO tEmp : dtosList) {
            result[i] = StudyIndldeTransformer.INSTANCE.toXml(tEmp);
            i++;
        }
        return result;
  }

  public gov.nih.nci.coppa.services.pa.StudyIndlde[] getByStudyProtocol(gov.nih.nci.coppa.services.pa.Id studyProtocolId) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
      StudyIndlde[] result = null;
      try {
          Ii iiDto = IITransformer.INSTANCE.toDto(studyProtocolId);
          List<StudyIndldeDTO> dtosList = studyIndIdeService.getByStudyProtocol(iiDto);

          result = convert(dtosList);
          return result;
      } catch (Exception e) {
          logger.error(e.getMessage(), e);
          throw FaultUtil.reThrowRemote(e);
      }
  }

  public void copy(gov.nih.nci.coppa.services.pa.Id fromStudyProtocolId,gov.nih.nci.coppa.services.pa.Id toStudyProtocolId) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.pa.StudyIndlde[] getCurrentByStudyProtocol(gov.nih.nci.coppa.services.pa.Id studyProtocolId) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
      StudyIndlde[] result = null;
      try {
          Ii iiDto = IITransformer.INSTANCE.toDto(studyProtocolId);
          List<StudyIndldeDTO> dtosList = studyIndIdeService.getCurrentByStudyProtocol(iiDto);

          result = convert(dtosList);
          return result;
      } catch (Exception e) {
          logger.error(e.getMessage(), e);
          throw FaultUtil.reThrowRemote(e);
      }
  }

  public gov.nih.nci.coppa.services.pa.StudyIndlde get(gov.nih.nci.coppa.services.pa.Id id) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
      StudyIndldeDTO result = null;
      try {
          Ii iiDto = IITransformer.INSTANCE.toDto(id);
          result = studyIndIdeService.get(iiDto);
          return StudyIndldeTransformer.INSTANCE.toXml(result);
      } catch (Exception e) {
          logger.error(e.getMessage(), e);
          throw FaultUtil.reThrowRemote(e);
      }
  }

  public gov.nih.nci.coppa.services.pa.StudyIndlde create(gov.nih.nci.coppa.services.pa.StudyIndlde studyIndlde) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.pa.StudyIndlde update(gov.nih.nci.coppa.services.pa.StudyIndlde studyIndlde) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void delete(gov.nih.nci.coppa.services.pa.Id id) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

