DROP TABLE IF EXISTS DW_STUDY_AMENDMENT;

CREATE TABLE DW_STUDY_AMENDMENT (
	AMENDMENT_DATE date, 
	INTERNAL_SYSTEM_ID INTEGER,
    NCI_ID character varying(255),
	NUMBER character varying(200),
	SUBMISSION_NUMBER INTEGER,
    SUBMITTER_NAME character varying(501)
);

CREATE INDEX DW_STUDY_AMEND_DATE       on DW_STUDY_AMENDMENT(amendment_date);
CREATE INDEX DW_STUDY_AMEND_ID         on DW_STUDY_AMENDMENT(internal_system_id);
CREATE INDEX DW_STUDY_AMEND_NCI_ID     on DW_STUDY_AMENDMENT(nci_id);
CREATE INDEX DW_STUDY_AMEND_SUB_NUMBER on DW_STUDY_AMENDMENT(submission_number);
CREATE INDEX DW_STUDY_AMEND_NUMBER     on DW_STUDY_AMENDMENT(number);
CREATE INDEX DW_STUDY_AMEND_SUB_NAME   on DW_STUDY_AMENDMENT(submitter_name);

