DROP TABLE IF EXISTS DW_STUDY_ANATOMIC_SITE;
CREATE TABLE DW_STUDY_ANATOMIC_SITE (
    ANATOMIC_SITE_NAME character varying(1000),
    NCI_ID character varying(255)
);

CREATE INDEX DW_STUDY_ANATOMIC_SITE_ANATOMIC_SITE_NAME_IDX on dw_study_anatomic_site(anatomic_site_name);
CREATE INDEX DW_STUDY_ANATOMIC_SITE_NCI_ID_IDX on dw_study_anatomic_site(nci_id);