DROP TABLE IF EXISTS DW_STUDY_ARM_AND_INTERVENTION;
CREATE TABLE DW_STUDY_ARM_AND_INTERVENTION ( 
    ARM_DESCRIPTION character varying(1000),
    ARM_NAME character varying(200),
    ARM_TYPE character varying(50),
    DATE_CREATED_ARM timestamp,
    DATE_UPDATED_ARM timestamp,
    DATE_CREATED_INTERVENTION timestamp,
    DATE_UPDATED_INTERVENTION timestamp,
    INTERVENTION_DESCRIPTION character varying(1000),
    INTERVENTION_NAME character varying(200),
    INTERVENTION_OTHER_NAME character varying(2000),
    INTERVENTION_ID integer,
    INTERVENTION_TYPE character varying(200),
    NCI_ID character varying(255),
	USER_NAME_CREATED_ARM character(255),
	USER_NAME_UPDATED_ARM character(255),
	USER_NAME_CREATED_INTERVENTION character(255),
	USER_NAME_UPDATED_INTERVENTION character(255)
    );

CREATE INDEX DW_STUDY_ARM_CI_ID_IDX on DW_STUDY_ARM_AND_INTERVENTION(NCI_ID);
CREATE INDEX DW_STUDY_ARM_DESC_IDX on DW_STUDY_ARM_AND_INTERVENTION(ARM_DESCRIPTION);
CREATE INDEX DW_STUDY_ARM_NAME_IDX on DW_STUDY_ARM_AND_INTERVENTION(ARM_NAME);
CREATE INDEX DW_STUDY_ARM_TYPE_IDX on DW_STUDY_ARM_AND_INTERVENTION(ARM_TYPE);
CREATE INDEX DW_STUDY_INT_DESC_IDX on DW_STUDY_ARM_AND_INTERVENTION(INTERVENTION_DESCRIPTION);
CREATE INDEX DW_STUDY_INT_NAME_IDX on DW_STUDY_ARM_AND_INTERVENTION(INTERVENTION_NAME);
CREATE INDEX DW_STUDY_INT_ID_IDX on DW_STUDY_ARM_AND_INTERVENTION(INTERVENTION_ID);
CREATE INDEX DW_STUDY_INT_TYPE_IDX on DW_STUDY_ARM_AND_INTERVENTION(INTERVENTION_TYPE);
CREATE INDEX DW_STUDY_INT_OTHERNAME_IDX on DW_STUDY_ARM_AND_INTERVENTION(INTERVENTION_OTHER_NAME);

