DROP TABLE IF EXISTS DW_STUDY_COLLABORATOR;
CREATE TABLE DW_STUDY_COLLABORATOR ( 
    FUNCTIONAL_ROLE character varying(50),
    NAME character varying(200),
    NCI_ID character varying(255),
	STATUS character(20)
    );

CREATE INDEX DW_STUDY_COLLABORATOR_ROLE_IDX on DW_STUDY_COLLABORATOR(functional_role);
CREATE INDEX DW_STUDY_COLLABORATOR_NAME_IDX on DW_STUDY_COLLABORATOR(name);
CREATE INDEX DW_STUDY_COLLABORATOR_STATUS_IDX on DW_STUDY_COLLABORATOR(nci_id);
CREATE INDEX DW_STUDY_COLLABORATOR_NCI_ID_IDX on DW_STUDY_COLLABORATOR(status);

