DROP TABLE IF EXISTS DW_STUDY_OVERALL_STATUS;
CREATE TABLE DW_STUDY_OVERALL_STATUS ( 
    STATUS character varying(50),
    STATUS_DATE date,
    DATE_CREATED date,
    DATE_LAST_UPDATED date,
    SYSTEM_CREATED boolean,
    WHY_STUDY_STOPPED character varying(2000),
    INTERNAL_SYSTEM_ID INTEGER,
    NCI_ID character varying(255),
    USER_CREATED character varying(500),
    USER_LAST_UPDATED character varying(500),
    PRIMARY KEY (INTERNAL_SYSTEM_ID)
);

CREATE INDEX DW_STUDY_OVERALL_STATUS_STATUS_IDX on DW_STUDY_OVERALL_STATUS(status);
CREATE INDEX DW_STUDY_OVERALL_STATUS_STATUS_DATE_IDX on DW_STUDY_OVERALL_STATUS(status_date);
CREATE INDEX DW_STUDY_OVERALL_STATUS_DATE_CREATED_IDX on DW_STUDY_OVERALL_STATUS(date_created);
CREATE INDEX DW_STUDY_OVERALL_STATUS_DATE_UPDATED_IDX on DW_STUDY_OVERALL_STATUS(date_last_updated);
CREATE INDEX DW_STUDY_OVERALL_STATUS_SYSTEM_CREATED_IDX on DW_STUDY_OVERALL_STATUS using hash(system_created);
CREATE INDEX DW_STUDY_OVERALL_STATUS_WHY_IDX on DW_STUDY_OVERALL_STATUS(why_study_stopped);
CREATE INDEX DW_STUDY_OVERALL_STATUS_INT_ID_IDX on DW_STUDY_OVERALL_STATUS(internal_system_id);
CREATE INDEX DW_STUDY_OVERALL_STATUS_NCI_ID_IDX on DW_STUDY_OVERALL_STATUS(nci_id);
CREATE INDEX DW_STUDY_OVERALL_STATUS_USER_CREATED_IDX on DW_STUDY_OVERALL_STATUS(user_Created);
CREATE INDEX DW_STUDY_OVERALL_STATUS_USER_UPDATED_IDX on DW_STUDY_OVERALL_STATUS(user_last_updated);

