DROP TABLE IF EXISTS DW_STUDY_PROCESSING_STATUS;

CREATE TABLE DW_STUDY_PROCESSING_STATUS (
    COMMENTS character varying(200),
    DATE date,
    DATE_CREATED date,
    DATE_LAST_UPDATED date,
    INTERNAL_SYSTEM_ID INTEGER not null,
	NAME character varying (50),
    NCI_ID character varying(255),
    STATUS character varying(50),
    USER_NAME_CREATED character varying(500),
    USER_NAME_LAST_UPDATED character varying(500)
);

CREATE INDEX DW_STUDY_PROC_STATUS_COMMENTS_IDX on dw_study_PROCESSING_STATUS(comments);
CREATE INDEX DW_STUDY_PROCESSING_STATUS_DATE_IDX on dw_study_PROCESSING_STATUS(date);
CREATE INDEX DW_STUDY_PROCESSING_STATUS_DATE_CREATED_IDX on dw_study_PROCESSING_STATUS(date_created);
CREATE INDEX DW_STUDY_PROCESSING_STATUS_DATE_UPDATED_IDX on dw_study_PROCESSING_STATUS(date_last_updated);
CREATE INDEX DW_STUDY_PROCESSING_STATUS_ID_IDX on dw_study_PROCESSING_STATUS(internal_system_id);
CREATE INDEX DW_STUDY_PROCESSING_STATUS_NAME_IDX on dw_study_PROCESSING_STATUS(name);
CREATE INDEX DW_STUDY_PROCESSING_STATUS_NCI_ID_IDX on dw_study_PROCESSING_STATUS(nci_id);
CREATE INDEX DW_STUDY_PROCESSING_STATUS_STATUS_IDX on dw_study_PROCESSING_STATUS(status);
CREATE INDEX DW_STUDY_PROCESSING_STATUS_USER_CREATED_IDX on dw_study_PROCESSING_STATUS(user_name_created);
CREATE INDEX DW_STUDY_PROCESSING_STATUS_USER_UPDATED_IDX on dw_study_PROCESSING_STATUS(user_name_last_updated);

