DROP TABLE IF EXISTS DW_STUDY_AMENDMENT;
ALTER TABLE STG_DW_STUDY_AMENDMENT RENAME TO DW_STUDY_AMENDMENT;

DROP TABLE IF EXISTS DW_STUDY_ANATOMIC_SITE;
ALTER TABLE STG_DW_STUDY_ANATOMIC_SITE RENAME TO DW_STUDY_ANATOMIC_SITE;

DROP TABLE IF EXISTS DW_STUDY_ARM_AND_INTERVENTION;
ALTER TABLE STG_DW_STUDY_ARM_AND_INTERVENTION RENAME TO DW_STUDY_ARM_AND_INTERVENTION;

DROP TABLE IF EXISTS DW_STUDY_BIOMARKER;
ALTER TABLE STG_DW_STUDY_BIOMARKER RENAME TO DW_STUDY_BIOMARKER;

DROP TABLE IF EXISTS DW_STUDY_COLLABORATOR;
ALTER TABLE STG_DW_STUDY_COLLABORATOR RENAME TO DW_STUDY_COLLABORATOR;

DROP TABLE IF EXISTS DW_STUDY_DISEASE;
ALTER TABLE STG_DW_STUDY_DISEASE RENAME TO DW_STUDY_DISEASE;

DROP TABLE IF EXISTS DW_STUDY_ELIGIBILITY_CRITERIA;
ALTER TABLE STG_DW_STUDY_ELIGIBILITY_CRITERIA RENAME TO DW_STUDY_ELIGIBILITY_CRITERIA;

DROP TABLE IF EXISTS DW_FAMILY_ORGANIZATION;
ALTER TABLE STG_DW_FAMILY_ORGANIZATION RENAME TO DW_FAMILY_ORGANIZATION;

DROP TABLE IF EXISTS DW_GENERIC_CONTACT;
ALTER TABLE STG_DW_GENERIC_CONTACT RENAME TO DW_GENERIC_CONTACT;

DROP TABLE IF EXISTS DW_STUDY_GRANT;
ALTER TABLE STG_DW_STUDY_GRANT RENAME TO DW_STUDY_GRANT;

DROP TABLE IF EXISTS DW_STUDY_IND_IDE;
ALTER TABLE STG_DW_STUDY_IND_IDE RENAME TO DW_STUDY_IND_IDE;

DROP TABLE IF EXISTS DW_STUDY_MILESTONE;
ALTER TABLE STG_DW_STUDY_MILESTONE RENAME TO DW_STUDY_MILESTONE;

DROP TABLE IF EXISTS DW_STUDY_ON_HOLD_STATUS;
ALTER TABLE STG_DW_STUDY_ON_HOLD_STATUS RENAME TO DW_STUDY_ON_HOLD_STATUS;

DROP TABLE IF EXISTS DW_ORGANIZATION_AUDIT;
ALTER TABLE STG_DW_ORGANIZATION_AUDIT RENAME TO DW_ORGANIZATION_AUDIT;

DROP TABLE IF EXISTS DW_STUDY_OTHER_IDENTIFIER;
ALTER TABLE STG_DW_STUDY_OTHER_IDENTIFIER RENAME TO DW_STUDY_OTHER_IDENTIFIER;

DROP TABLE IF EXISTS DW_STUDY_OUTCOME_MEASURE;
ALTER TABLE STG_DW_STUDY_OUTCOME_MEASURE RENAME TO DW_STUDY_OUTCOME_MEASURE;

DROP TABLE IF EXISTS DW_STUDY_OVERALL_STATUS;
ALTER TABLE STG_DW_STUDY_OVERALL_STATUS RENAME TO DW_STUDY_OVERALL_STATUS;

DROP TABLE IF EXISTS DW_STUDY_PARTICIPATING_SITE CASCADE;
ALTER TABLE STG_DW_STUDY_PARTICIPATING_SITE RENAME TO DW_STUDY_PARTICIPATING_SITE;

DROP TABLE IF EXISTS DW_STUDY_PARTICIPATING_SITE_INVESTIGATORS CASCADE;
ALTER TABLE STG_DW_STUDY_PARTICIPATING_SITE_INVESTIGATORS RENAME TO DW_STUDY_PARTICIPATING_SITE_INVESTIGATORS;

DROP TABLE IF EXISTS DW_PERSON_AUDIT;
ALTER TABLE STG_DW_PERSON_AUDIT RENAME TO DW_PERSON_AUDIT;

DROP TABLE IF EXISTS DW_PERSON_ROLE;
ALTER TABLE STG_DW_PERSON_ROLE RENAME TO DW_PERSON_ROLE;

DROP TABLE IF EXISTS DW_PERSON;
ALTER TABLE STG_DW_PERSON RENAME TO DW_PERSON;

DROP TABLE IF EXISTS DW_STUDY_PROCESSING_STATUS;
ALTER TABLE STG_DW_STUDY_PROCESSING_STATUS RENAME TO DW_STUDY_PROCESSING_STATUS;

DROP TABLE IF EXISTS DW_STUDY_RECORD_OWNER;
ALTER TABLE STG_DW_STUDY_RECORD_OWNER RENAME TO DW_STUDY_RECORD_OWNER;

DROP TABLE IF EXISTS DW_STUDY_AUDIT;
ALTER TABLE STG_DW_STUDY_AUDIT RENAME TO DW_STUDY_AUDIT;

DROP TABLE IF EXISTS DW_STUDY;
ALTER TABLE STG_DW_STUDY RENAME TO DW_STUDY;

DROP TABLE IF EXISTS DW_STUDY_SUBGROUP;
ALTER TABLE STG_DW_STUDY_SUBGROUP RENAME TO DW_STUDY_SUBGROUP;

DROP TABLE IF EXISTS DW_ORGANIZATION;
ALTER TABLE STG_DW_ORGANIZATION RENAME TO DW_ORGANIZATION;

DROP TABLE IF EXISTS DW_ORGANIZATION_ROLE;
ALTER TABLE STG_DW_ORGANIZATION_ROLE RENAME TO DW_ORGANIZATION_ROLE;

DROP TABLE IF EXISTS DW_AFFILIATE_ORG;
ALTER TABLE STG_DW_AFFILIATE_ORG RENAME TO DW_AFFILIATE_ORG;

DROP TABLE IF EXISTS DW_USER;
ALTER TABLE STG_DW_USER RENAME TO DW_USER;
