package gov.nih.nci.coppa.services.pa.studysiteservice.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface StudySiteServiceConstantsBase {
	public static final String SERVICE_NS = "http://enterpriseservices.nci.nih.gov/PAServices/StudySiteService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "StudySiteServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "StudySiteServiceResourceProperties");
	
}
