function  WWHBookData_Files(P)
{
P.fA("Protocol Abstraction Online Help","Welcome.1.1.html");
P.fA("Using the Online Help","Welcome.1.2.html");
P.fA("Getting Started","GettingStarted.2.1.html");
P.fA("Overview of Protocol Abstraction","GettingStarted.2.2.html");
P.fA("Logging In to Protocol Abstraction","GettingStarted.2.3.html");
P.fA("Logging Out of Protocol Abstraction","GettingStarted.2.4.html");
P.fA("Searching for Trials in the Clinical Trials Reporting Program","searchTrials.3.1.html");
P.fA("Searching for Trials","searchTrials.3.2.html");
P.fA("Navigating the Search Results List","searchTrials.3.3.html");
P.fA("Viewing Trial Identification Details","searchTrials.3.4.html");
P.fA("Checking In and Checking Out Trials","searchTrials.3.5.html");
P.fA("Processing Updated Trials and Requests for Admin Rights","searchTrials.3.6.html");
P.fA("Accessing Trials in the Inbox","searchTrials.3.7.html");
P.fA("Removing Trials From the Inbox","searchTrials.3.8.html");
P.fA("Granting Admin Rights to NCI CTRP Registration Site Users","searchTrials.3.9.html");
P.fA("Validating Trials","validate.4.1.html");
P.fA("About Trial Validation","validate.4.2.html");
P.fA("Selecting Trials that Require Validation","validate.4.3.html");
P.fA("Main Steps for Validating Submitted Trials","validate.4.4.html");
P.fA("Reviewing Trial Overview Details","validate.4.5.html");
P.fA("Validating Trial Documents","validate.4.6.html");
P.fA("Accessing Trial Summary Reports","validate.4.7.html");
P.fA("Validating Participating Sites for Proprietary Trials","validate.4.8.html");
P.fA("Validating Trial Status Details","validate.4.9.html");
P.fA("Validating Funding Details","validate.4.10.html");
P.fA("Validating IND/IDE Details","validate.4.11.html");
P.fA("Validating Regulatory Information","validate.4.12.html");
P.fA("Validating Trial Details","validate.4.13.html");
P.fA("Validating the Trial Identifiers Section","validate.4.14.html");
P.fA("Validating the Other Identifiers Section","validate.4.15.html");
P.fA("Validating the Lead Organization/Principal Investigator Section","validate.4.16.html");
P.fA("Validating the Sponsor/Responsible Party Section","validate.4.17.html");
P.fA("Validating the Summary 4 Information Section","validate.4.18.html");
P.fA("Validating Amended Trial Submissions","validate.4.19.html");
P.fA("Accepting and Rejecting Trials","validate.4.20.html");
P.fA("Abstracting Trial Overview Data","overviewData.5.1.html");
P.fA("About Trial Overview Data","overviewData.5.2.html");
P.fA("Abstracting Trial History Information","overviewData.5.3.html");
P.fA("Abstracting Trial Milestones","overviewData.5.4.html");
P.fA("Trial Summary Report Life Cycle","overviewData.5.5.html");
P.fA("Milestone and Processing Status Rules","overviewData.5.6.html");
P.fA("Viewing and Adding Milestones","overviewData.5.7.html");
P.fA("Abstracting On-hold Information","overviewData.5.8.html");
P.fA("Adding On-hold Records","overviewData.5.9.html");
P.fA("Editing On-hold Records","overviewData.5.10.html");
P.fA("Abstracting Administrative Data","Admin.6.1.html");
P.fA("About Administrative Data","Admin.6.2.html");
P.fA("Abstracting General Trial Details","Admin.6.3.html");
P.fA("Abstracting Trial Titles","Admin.6.4.html");
P.fA("Abstracting Trial Descriptions","Admin.6.5.html");
P.fA("Abstracting Lead Organizations and Principal Investigators","Admin.6.6.html");
P.fA("Abstracting Sponsors and Responsible Parties","Admin.6.7.html");
P.fA("Abstracting Central Contacts","Admin.6.8.html");
P.fA("Abstracting NCI-Specific Information","Admin.6.9.html");
P.fA("Abstracting Regulatory Information","Admin.6.10.html");
P.fA("Abstracting Human Subject Safety Information","Admin.6.11.html");
P.fA("Abstracting Trial IND/IDE Information","Admin.6.12.html");
P.fA("Abstracting Trial Status Information","Admin.6.13.html");
P.fA("Abstracting Trial Funding Information","Admin.6.14.html");
P.fA("Abstracting Participating Site Information","Admin.6.15.html");
P.fA("Linking Organizations to Non-Proprietary Trials","Admin.6.16.html");
P.fA("Linking Organizations to Proprietary Trials","Admin.6.17.html");
P.fA("Linking Investigators to a Trial","Admin.6.18.html");
P.fA("Linking Contacts to a Trial","Admin.6.19.html");
P.fA("Deleting Participating Sites From a Trial","Admin.6.20.html");
P.fA("Editing Participating Site Information","Admin.6.21.html");
P.fA("Abstracting Collaborator Information","Admin.6.22.html");
P.fA("Deleting Collaborators From a Trial","Admin.6.23.html");
P.fA("Editing Collaborator Roles","Admin.6.24.html");
P.fA("Abstracting Trial-Related Documents","Admin.6.25.html");
P.fA("Adding Trial-Related Documents","Admin.6.26.html");
P.fA("Deleting Trial-Related Documents","Admin.6.27.html");
P.fA("Editing and Replacing Documents","Admin.6.28.html");
P.fA("Abstracting Scientific Data","science.7.1.html");
P.fA("Abstracting Trial Descriptions","science.7.2.html");
P.fA("Abstracting Trial Design","science.7.3.html");
P.fA("Abstracting Interventional Trial Design Details","science.7.4.html");
P.fA("Abstracting Trial Outcome Measures","science.7.5.html");
P.fA("Adding Outcome Measures","science.7.6.html");
P.fA("Editing Outcome Measures","science.7.7.html");
P.fA("Deleting Outcome Measures","science.7.8.html");
P.fA("Abstracting Trial Eligibility Criteria","science.7.9.html");
P.fA("Adding Other Eligibility Criteria","science.7.10.html");
P.fA("Adding Eligibility Criteria in Free-Form Text","science.7.11.html");
P.fA("Building Eligibility Criteria","science.7.12.html");
P.fA("Re-Ordering Other Eligibility Criteria","science.7.13.html");
P.fA("Editing Other Eligibility Criteria","science.7.14.html");
P.fA("Deleting Eligibility Criteria","science.7.15.html");
P.fA("Abstracting Diseases/Conditions","science.7.16.html");
P.fA("Viewing Disease/Condition Details","science.7.17.html");
P.fA("Adding Diseases/Conditions to a Trial","science.7.18.html");
P.fA("Editing Disease/Condition Indicators","science.7.19.html");
P.fA("Deleting Diseases/Conditions from a Trial","science.7.20.html");
P.fA("Abstracting Interventions","science.7.21.html");
P.fA("Adding Interventions to a Trial","science.7.22.html");
P.fA("Abstracting Drug, Radiation, and Procedure/Surgery Information","science.7.23.html");
P.fA("Editing Intervention Records","science.7.24.html");
P.fA("Deleting Interventions from a Trial","science.7.25.html");
P.fA("Abstracting Arm Information","science.7.26.html");
P.fA("Adding Arms to a Trial","science.7.27.html");
P.fA("Editing Arm Records","science.7.28.html");
P.fA("Deleting Arms","science.7.29.html");
P.fA("Abstracting Sub-Groups","science.7.30.html");
P.fA("Adding Sub-groups to a Trial","science.7.31.html");
P.fA("Editing Sub-group Records","science.7.32.html");
P.fA("Deleting Sub-groups","science.7.33.html");
P.fA("Completing Abstractions","complete.8.1.html");
P.fA("About Abstraction Validation","complete.8.2.html");
P.fA("Trial Completion Criteria","complete.8.3.html");
P.fA("Trial Reporting","complete.8.4.html");
P.fA("Validating Abstractions","complete.8.5.html");
P.fA("Granting Access to the Accrual Application","accrualAccess.9.1.html");
P.fA("Managing Accrual Access","accrualAccess.9.2.html");
P.fA("Setting Up Accrual Access","accrualAccess.9.3.html");
P.fA("Activating and Inactivating Accrual Access","accrualAccess.9.4.html");
P.fA("Assigning Trial Ownership","assignOwnership.10.1.html");
P.fA("Managing Trial Ownership","assignOwnership.10.2.html");
P.fA("Working With Organization Records","orgs.11.1.html");
P.fA("Looking Up Registered Organizations","orgs.11.2.html");
P.fA("Working With Person Records","persons.12.1.html");
P.fA("Looking Up Registered Persons","persons.12.2.html");
P.fA("Application Support","appSupport.13.1.html");
}
