function  WWHBookData_Files(P)
{
P.fA("Protocol Abstraction Online Help","Welcome.1.1.html");
P.fA("Using the Online Help","Welcome.1.2.html");
P.fA("Getting Started","GettingStarted.2.1.html");
P.fA("Overview of Protocol Abstraction","GettingStarted.2.2.html");
P.fA("About Trial Categories","GettingStarted.2.3.html");
P.fA("Logging In to Protocol Abstraction","GettingStarted.2.4.html");
P.fA("Logging Out of Protocol Abstraction","GettingStarted.2.5.html");
P.fA("Searching for Registered Trials","searchTrials.3.1.html");
P.fA("Searching for Trials","searchTrials.3.2.html");
P.fA("Viewing Trial Identification Details","searchTrials.3.3.html");
P.fA("Validating Trials","validate.4.1.html");
P.fA("About Trial Validation","validate.4.2.html");
P.fA("Selecting Trials that Require Validation","validate.4.3.html");
P.fA("Main Steps for Validating Submitted Trials","validate.4.4.html");
P.fA("Validating Trial-Related Documents","validate.4.5.html");
P.fA("Validating Trial Status Details","validate.4.6.html");
P.fA("Validating Funding Details","validate.4.7.html");
P.fA("Validating IND/IDE Details","validate.4.8.html");
P.fA("Validating Regulatory Information","validate.4.9.html");
P.fA("Validating Trial Details","validate.4.10.html");
P.fA("Validating Amended Trial Submissions","validate.4.11.html");
P.fA("Accepting and Rejecting Trials","validate.4.12.html");
P.fA("Validating Industrial Trials","validate_abbreviated.5.1.html");
P.fA("About Trial Validation","validate_abbreviated.5.2.html");
P.fA("Selecting Abbreviated Trials that Require Validation","validate_abbreviated.5.3.html");
P.fA("Main Steps for Validating Submitted Trials","validate_abbreviated.5.4.html");
P.fA("Validating Trial-Related Documents","validate_abbreviated.5.5.html");
P.fA("Validating Participating Sites","validate_abbreviated.5.6.html");
P.fA("Validating Trial Details","validate_abbreviated.5.7.html");
P.fA("Abstracting Trial Overview Data","overviewData.6.1.html");
P.fA("About Trial Overview Data","overviewData.6.2.html");
P.fA("Abstracting Trial History Information","overviewData.6.3.html");
P.fA("Abstracting Trial Milestones","overviewData.6.4.html");
P.fA("Trial Summary Report Life Cycle","overviewData.6.5.html");
P.fA("Milestone and Processing Status Rules","overviewData.6.6.html");
P.fA("Viewing and Adding Milestones","overviewData.6.7.html");
P.fA("Abstracting On-hold Information","overviewData.6.8.html");
P.fA("Adding On-hold Records","overviewData.6.9.html");
P.fA("Editing On-hold Records","overviewData.6.10.html");
P.fA("Abstracting Administrative Data","Admin.7.1.html");
P.fA("About Administrative Data","Admin.7.2.html");
P.fA("Abstracting General Trial Details","Admin.7.3.html");
P.fA("Abstracting NCI-Specific Information","Admin.7.4.html");
P.fA("Abstracting Regulatory Information","Admin.7.5.html");
P.fA("Abstracting Human Subject Safety Information","Admin.7.6.html");
P.fA("Abstracting Trial IND/IDE Information","Admin.7.7.html");
P.fA("Abstracting Trial Status Information","Admin.7.8.html");
P.fA("Abstracting Trial Funding Information","Admin.7.9.html");
P.fA("Abstracting Participating Site Information","Admin.7.10.html");
P.fA("Editing and Deleting Participating Site Records","Admin.7.11.html");
P.fA("Click Save.Abstracting Collaborator Information","Admin.7.12.html");
P.fA("Deleting Collaborators From a Trial","Admin.7.13.html");
P.fA("Editing Collaborator Roles","Admin.7.14.html");
P.fA("Abstracting Trial-Related Documents","Admin.7.15.html");
P.fA("Adding Trial-Related Documents","Admin.7.16.html");
P.fA("Deleting Trial-Related Documents","Admin.7.17.html");
P.fA("Editing and Replacing Documents","Admin.7.18.html");
P.fA("Abstracting Scientific Data","science.8.1.html");
P.fA("Abstracting Trial Descriptions","science.8.2.html");
P.fA("Abstracting Trial Design","science.8.3.html");
P.fA("Abstracting Trial Outcome Measures","science.8.4.html");
P.fA("Adding Outcome Measures","science.8.5.html");
P.fA("Editing Outcome Measures","science.8.6.html");
P.fA("Deleting Outcome Measures","science.8.7.html");
P.fA("Abstracting Trial Eligibility Criteria","science.8.8.html");
P.fA("Adding Other Eligibility Criteria","science.8.9.html");
P.fA("Adding Eligibility Criteria in Free-Form Text","science.8.10.html");
P.fA("Building Eligibility Criteria","science.8.11.html");
P.fA("Re-Ordering Other Eligibility Criteria","science.8.12.html");
P.fA("Editing Other Eligibility Criteria","science.8.13.html");
P.fA("Deleting Eligibility Criteria","science.8.14.html");
P.fA("Abstracting Diseases/Conditions","science.8.15.html");
P.fA("Viewing Disease/Condition Details","science.8.16.html");
P.fA("Adding Diseases/Conditions to a Trial","science.8.17.html");
P.fA("Editing Disease/Condition Indicators","science.8.18.html");
P.fA("Deleting Diseases/Conditions from a Trial","science.8.19.html");
P.fA("Abstracting Interventions","science.8.20.html");
P.fA("Adding Interventions to a Trial","science.8.21.html");
P.fA("Generating Drug, Radiation, and Procedure/Surgery Descriptions","science.8.22.html");
P.fA("Editing Intervention Records","science.8.23.html");
P.fA("Deleting Interventions from a Trial","science.8.24.html");
P.fA("Abstracting Arm Information","science.8.25.html");
P.fA("Adding Arms to a Trial","science.8.26.html");
P.fA("Editing Arm Records","science.8.27.html");
P.fA("Deleting Arms","science.8.28.html");
P.fA("Abstracting Sub-Groups","science.8.29.html");
P.fA("Adding Sub-groups to a Trial","science.8.30.html");
P.fA("Editing Sub-group Records","science.8.31.html");
P.fA("Deleting Sub-groups","science.8.32.html");
P.fA("Completing Abstractions","complete.9.1.html");
P.fA("About Abstraction Validation","complete.9.2.html");
P.fA("Trial Completion Criteria","complete.9.3.html");
P.fA("Trial Reporting","complete.9.4.html");
P.fA("Validating Abstractions","complete.9.5.html");
P.fA("Processing Requests in the Inbox","inbox.10.1.html");
P.fA("Processing Requests for Admin Rights","inbox.10.2.html");
P.fA("Granting Access to the Accrual Application","accrualAccess.11.1.html");
P.fA("Managing Accrual Access","accrualAccess.11.2.html");
P.fA("Setting Up Accrual Access","accrualAccess.11.3.html");
P.fA("Activating and Inactivating Accrual Access","accrualAccess.11.4.html");
P.fA("Assigning Trial Ownership","assignOwnership.12.1.html");
P.fA("Managing Trial Ownership","assignOwnership.12.2.html");
P.fA("Common Tasks","commonTasks.13.1.html");
P.fA("CTRP Protocol Abstraction Icons","commonTasks.13.2.html");
P.fA("Checking In and Checking Out Trials","commonTasks.13.3.html");
P.fA("Looking Up Registered Persons","commonTasks.13.4.html");
P.fA("Looking Up Registered Organizations","commonTasks.13.5.html");
P.fA("Looking Up Generic Contacts","commonTasks.13.6.html");
P.fA("Entering Phone and Fax Numbers","commonTasks.13.7.html");
P.fA("Selecting and Entering Dates","commonTasks.13.8.html");
P.fA("Navigating Search Results Lists","commonTasks.13.9.html");
P.fA("Accessing Trial Summary Reports","commonTasks.13.10.html");
P.fA("Uploading Documents","commonTasks.13.11.html");
P.fA("Institute Codes","instituteCode.14.1.html");
P.fA("NCI Codes","instituteCode.14.2.html");
P.fA("IND/IDE NIH Institute/NCI Division Program Code Values","instituteCode.14.3.html");
P.fA("Funding Mechanism Codes","instituteCode.14.4.html");
P.fA("Trial Processing Statuses","processStatus.15.1.html");
P.fA("Application Support","appSupport.16.1.html");
}
