function  WWHBookData_Files(P)
{
P.fA("Protocol Abstraction Online Help","Welcome.1.1.html");
P.fA("Using the Online Help","Welcome.1.2.html");
P.fA("Using Navigation Tools","Welcome.1.3.html");
P.fA("Getting Started","GettingStarted.2.1.html");
P.fA("Overview of Protocol Abstraction","GettingStarted.2.2.html");
P.fA("Logging In to Protocol Abstraction","GettingStarted.2.3.html");
P.fA("Logging Out of Protocol Abstraction","GettingStarted.2.4.html");
P.fA("Validating Trials","validate.3.1.html");
P.fA("About Trial Validation","validate.3.2.html");
P.fA("Selecting Trials that Require Validation","validate.3.3.html");
P.fA("Navigating the Validation Workspace","validate.3.4.html");
P.fA("Saving Trial Information","validate.3.5.html");
P.fA("Reviewing Recorded Trial Details","validate.3.6.html");
P.fA("Reviewing Trial Documents","validate.3.7.html");
P.fA("Reviewing Trial Status Details","validate.3.8.html");
P.fA("Reviewing Funding Details","validate.3.9.html");
P.fA("Reviewing IND/IDE Details","validate.3.10.html");
P.fA("Validating Amended Trial Submissions","validate.3.11.html");
P.fA("Accepting and Rejecting Trials","validate.3.12.html");
P.fA("Abstracting Trial Overview Data","overviewData.4.1.html");
P.fA("About Trial Overview Data","overviewData.4.2.html");
P.fA("Abstracting Trial History Information","overviewData.4.3.html");
P.fA("Abstracting Trial Milestones","overviewData.4.4.html");
P.fA("Trial Summary Report Life Cycle","overviewData.4.5.html");
P.fA("Milestone and Processing Status Rules","overviewData.4.6.html");
P.fA("Viewing and Adding Milestones","overviewData.4.7.html");
P.fA("Abstracting On-hold Information","overviewData.4.8.html");
P.fA("Adding On-hold Records","overviewData.4.9.html");
P.fA("Editing On-hold Records","overviewData.4.10.html");
P.fA("Abstracting Administrative Data","Admin.5.1.html");
P.fA("About Administrative Data","Admin.5.2.html");
P.fA("Abstracting General Trial Details","Admin.5.3.html");
P.fA("Abstracting Trial Titles","Admin.5.4.html");
P.fA("Abstracting Trial Descriptions","Admin.5.5.html");
P.fA("Abstracting Lead Organizations and Principle Investigators","Admin.5.6.html");
P.fA("Abstracting Sponsors and Responsible Parties","Admin.5.7.html");
P.fA("Abstracting Central Contacts","Admin.5.8.html");
P.fA("Abstracting NCI-Specific Information","Admin.5.9.html");
P.fA("Abstracting Regulatory Information","Admin.5.10.html");
P.fA("Abstracting Human Subject Safety Information","Admin.5.11.html");
P.fA("Abstracting Trial IND/IDE Information","Admin.5.12.html");
P.fA("Abstracting Trial Status Information","Admin.5.13.html");
P.fA("Abstracting Trial Funding Information","Admin.5.14.html");
P.fA("Abstracting Participating Site Information","Admin.5.15.html");
P.fA("Linking Organizations to a Trial","Admin.5.16.html");
P.fA("Linking Investigators to a Trial","Admin.5.17.html");
P.fA("Abstracting Contacts","Admin.5.18.html");
P.fA("Unlinking Participating Sites From a Trial","Admin.5.19.html");
P.fA("Editing Participating Site Information","Admin.5.20.html");
P.fA("Abstracting Collaborator Information","Admin.5.21.html");
P.fA("Unlinking Collaborators From a Trial","Admin.5.22.html");
P.fA("Abstracting Trial-Related Documents","Admin.5.23.html");
P.fA("Adding Trial-Related Documents","Admin.5.24.html");
P.fA("Deleting Trial-Related Documents","Admin.5.25.html");
P.fA("Editing and Replacing Documents","Admin.5.26.html");
P.fA("Abstracting Scientific Data","science.6.1.html");
P.fA("Abstracting Trial Descriptions","science.6.2.html");
P.fA("Abstracting Interventional Trial Design","science.6.3.html");
P.fA("Abstracting Interventional Trial Design Details","science.6.4.html");
P.fA("Abstracting Interventional Trial Outcome Measures","science.6.5.html");
P.fA("Adding Outcome Measures","science.6.6.html");
P.fA("Editing Outcome Measures","science.6.7.html");
P.fA("Deleting Outcome Measures","science.6.8.html");
P.fA("Abstracting Interventional Trial Eligibility Criteria","science.6.9.html");
P.fA("Adding Other Eligibility Criteria","science.6.10.html");
P.fA("Editing Other Eligibility Criteria","science.6.11.html");
P.fA("Deleting Eligibility Criteria","science.6.12.html");
P.fA("Abstracting Diseases/Conditions","science.6.13.html");
P.fA("Viewing Disease/Condition Details","science.6.14.html");
P.fA("Adding Diseases/Conditions to a Trial","science.6.15.html");
P.fA("Unlinking Diseases/Conditions from a Trial","science.6.16.html");
P.fA("Abstracting Interventions","science.6.17.html");
P.fA("Adding Interventions to a Trial","science.6.18.html");
P.fA("Editing Intervention Records","science.6.19.html");
P.fA("Unlinking Interventions from a Trial","science.6.20.html");
P.fA("Abstracting Arm Information","science.6.21.html");
P.fA("Adding Arms to a Trial","science.6.22.html");
P.fA("Editing Arm Records","science.6.23.html");
P.fA("Deleting Arms","science.6.24.html");
P.fA("Abstracting Sub-Groups","science.6.25.html");
P.fA("Adding Sub-groups to a Trial","science.6.26.html");
P.fA("Editing Sub-group Records","science.6.27.html");
P.fA("Deleting Sub-groups","science.6.28.html");
P.fA("Completing Abstractions","complete.7.1.html");
P.fA("About Abstraction Validation","complete.7.2.html");
P.fA("Trial Completion Criteria","complete.7.3.html");
P.fA("Trial Reporting","complete.7.4.html");
P.fA("Completing and Validating Abstractions","complete.7.5.html");
P.fA("Working With Person Records","persons.8.1.html");
P.fA("Looking Up Registered Persons","persons.8.2.html");
P.fA("Working With Organization Records","orgs.9.1.html");
P.fA("Looking Up Registered Organizations","orgs.9.2.html");
P.fA("Metadata Definitions","metadata.10.1.html");
P.fA("Glossary","Glossary.11.1.html");
P.fA("Application Support","appSupport.12.1.html");
}
