package gov.nih.nci.coppa.services.pa.studyrecruitmentstatusservice.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface StudyRecruitmentStatusServiceConstantsBase {
	public static final String SERVICE_NS = "http://enterpriseservices.nci.nih.gov/PAServices/StudyRecruitmentStatusService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "StudyRecruitmentStatusServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "StudyRecruitmentStatusServiceResourceProperties");
	
}
