function  WWHBookData_Files(P)
{
P.fA("Online Help","welcome.1.1.html");
P.fA("Using the Online Help","welcome.1.2.html");
P.fA("Using Navigation Tools","welcome.1.3.html");
P.fA("Getting Started","getStartedOutcomes.2.1.html");
P.fA("Overview of the","getStartedOutcomes.2.2.html");
P.fA("Creating an Account","getStartedOutcomes.2.3.html");
P.fA("Logging In to the","getStartedOutcomes.2.4.html");
P.fA("Resetting Your Password","getStartedOutcomes.2.5.html");
P.fA("Logging Out of the","getStartedOutcomes.2.6.html");
P.fA("Searching for and Adding Patients","search.3.1.html");
P.fA("About Patient Data","search.3.2.html");
P.fA("Searching For Patients","search.3.3.html");
P.fA("Adding New Patients","search.3.4.html");
P.fA("Viewing Existing Patient Data","search.3.5.html");
P.fA("Updating Patient Records","search.3.6.html");
P.fA("Deleting Patient Records","search.3.7.html");
P.fA("Working With Outcomes","outcomes.4.1.html");
P.fA("About Baseline Data","outcomes.4.2.html");
P.fA("Working With Diagnosis Data","outcomes.4.3.html");
P.fA("Working With Staging Data","outcomes.4.4.html");
P.fA("Adding Tumor Markers","outcomes.4.5.html");
P.fA("Working With Pathology Data","outcomes.4.6.html");
P.fA("Working With Prior Therapies Data","outcomes.4.7.html");
P.fA("Adding Prior Therapies","outcomes.4.8.html");
P.fA("Working With Performance Status Data","outcomes.4.9.html");
P.fA("Working With Treatment Plan Data","outcomes.4.10.html");
P.fA("Adding Treatment Plans","outcomes.4.11.html");
P.fA("Updating Treatment Plans","outcomes.4.12.html");
P.fA("Working With Course Data","outcomes.4.13.html");
P.fA("Adding Course Data","outcomes.4.14.html");
P.fA("Updating Course Data","outcomes.4.15.html");
P.fA("Working With Drug/Biologics Data","outcomes.4.16.html");
P.fA("Adding Drug Biologic Data","outcomes.4.17.html");
P.fA("Working With Surgery Data","outcomes.4.18.html");
P.fA("Adding Surgery Data","outcomes.4.19.html");
P.fA("Working With Radiation Data","outcomes.4.20.html");
P.fA("Adding Radiation Data","outcomes.4.21.html");
P.fA("Working With Off-Treatment Data","outcomes.4.22.html");
P.fA("Working With Patient Outcomes","outcomes.4.23.html");
P.fA("Working With Disease Evaluation Data","outcomes.4.24.html");
P.fA("Adding Disease Evaluation Data","outcomes.4.25.html");
P.fA("Working With Lesion Assessment Data","outcomes.4.26.html");
P.fA("Adding Lesion Assesment Data","outcomes.4.27.html");
P.fA("Working With Death Information","outcomes.4.28.html");
P.fA("Updating Patient Records","outcomes.4.29.html");
P.fA("Deleting Patient Records","outcomes.4.30.html");
P.fA("Working With Organization Records","lookUp.5.1.html");
P.fA("Looking Up Registered Organizations","lookUp.5.2.html");
P.fA("Application Support","appSupport.6.1.html");
}
