function  WWHBookData_Files(P)
{
P.fA("Outcomes Online Help","welcome.1.1.html");
P.fA("Using the Online Help","welcome.1.2.html");
P.fA("Using Navigation Tools","welcome.1.3.html");
P.fA("Getting Started","getStartedOutcomes.2.1.html");
P.fA("Overview of the NCI Outcomes Portal","getStartedOutcomes.2.2.html");
P.fA("Creating an Account","getStartedOutcomes.2.3.html");
P.fA("Logging In to the NCI Outcomes Portal","getStartedOutcomes.2.4.html");
P.fA("Resetting Your Password","getStartedOutcomes.2.5.html");
P.fA("Logging Out of the NCI Outcomes Portal","getStartedOutcomes.2.6.html");
P.fA("Working With Treatment Data","treatment.3.1.html");
P.fA("About Treatment Data","treatment.3.2.html");
P.fA("Submitting Treatment Regimen Data","treatment.3.3.html");
P.fA("Adding Treatment Regimens","treatment.3.4.html");
P.fA("Updating Treatment Regimen REcords","treatment.3.5.html");
P.fA("Submitting Cycle Data","treatment.3.6.html");
P.fA("Adding Cycles","treatment.3.7.html");
P.fA("Updating Cycle Data","treatment.3.8.html");
P.fA("Submitting Drug/Biologics Data","treatment.3.9.html");
P.fA("Adding Drug/Biologic Data","treatment.3.10.html");
P.fA("Updating Drug/Biologic Data","treatment.3.11.html");
P.fA("Submitting Surgery Data","treatment.3.12.html");
P.fA("Adding Surgery Data","treatment.3.13.html");
P.fA("Updating Surgery Data","treatment.3.14.html");
P.fA("Submitting Radiation Data","treatment.3.15.html");
P.fA("Adding Radiation Data","treatment.3.16.html");
P.fA("Updating Radiation Data","treatment.3.17.html");
P.fA("Submitting Off-Treatment Data","treatment.3.18.html");
P.fA("Working With Baseline Data","baseline.4.1.html");
P.fA("About Baseline Data","baseline.4.2.html");
P.fA("Submitting Diagnosis Data","baseline.4.3.html");
P.fA("Submitting Staging Data","baseline.4.4.html");
P.fA("Adding Tumor Markers","baseline.4.5.html");
P.fA("Submitting Pathology Data","baseline.4.6.html");
P.fA("Submitting Prior Therapies Data","baseline.4.7.html");
P.fA("Adding Prior Therapies","baseline.4.8.html");
P.fA("Submitting Performance Status Data","baseline.4.9.html");
P.fA("Searching for and Adding Patients","search.5.1.html");
P.fA("About Patient Data","search.5.2.html");
P.fA("Searching For Patients","search.5.3.html");
P.fA("Viewing Existing Patient Details","search.5.4.html");
P.fA("Updating Patient Records","search.5.5.html");
P.fA("Adding New Patients","search.5.6.html");
P.fA("Deleting Patient Records","search.5.7.html");
P.fA("Working With Outcome Data","outcomes.6.1.html");
P.fA("About Outcome Data","outcomes.6.2.html");
P.fA("For example, clinicians may measure a tumor many times throughout the course of treatment in order to make a formal assessment of response. Each measurement must be added to the patient\u2019s record. Submitting Disease Evaluation Data","outcomes.6.3.html");
P.fA("Adding Disease Evaluation Records","outcomes.6.4.html");
P.fA("Submitting Lesion Assessment Data","outcomes.6.5.html");
P.fA("Adding Lesion Assesment Records","outcomes.6.6.html");
P.fA("Modifying Lesion Assesment Records","outcomes.6.7.html");
P.fA("Deleting Lesion Assement Records","outcomes.6.8.html");
P.fA("Submitting Death Information","outcomes.6.9.html");
P.fA("Application Support","appSupport.7.1.html");
}
