function  WWHBookData_Files(P)
{
P.fA("NCI Outcomes Portal Online Help","welcome.1.1.html");
P.fA("Using the Online Help","welcome.1.2.html");
P.fA("Using Navigation Tools","welcome.1.3.html");
P.fA("Getting Started","getStartedOutcomes.2.1.html");
P.fA("Overview of the NCI Outcomes Portal","getStartedOutcomes.2.2.html");
P.fA("Creating an Account","getStartedOutcomes.2.3.html");
P.fA("Logging In to the NCI Outcomes Portal","getStartedOutcomes.2.4.html");
P.fA("Resetting Your Password","getStartedOutcomes.2.5.html");
P.fA("Logging Out of the NCI Outcomes Portal","getStartedOutcomes.2.6.html");
P.fA("Working With Patient Records","search.3.1.html");
P.fA("About Patient Data","search.3.2.html");
P.fA("Searching For Patient Records","search.3.3.html");
P.fA("Viewing Existing Patient Details","search.3.4.html");
P.fA("Updating Patient Records","search.3.5.html");
P.fA("Adding New Patient Records","search.3.6.html");
P.fA("Deleting Patient Records","search.3.7.html");
P.fA("Working With Baseline Data","baseline.4.1.html");
P.fA("About Baseline Data","baseline.4.2.html");
P.fA("Submitting Diagnosis Data","baseline.4.3.html");
P.fA("Submitting Staging Data","baseline.4.4.html");
P.fA("Adding Tumor Markers to the Staging Record","baseline.4.5.html");
P.fA("Submitting Pathology Data","baseline.4.6.html");
P.fA("Submitting Prior Therapies Data","baseline.4.7.html");
P.fA("Adding Prior Therapy Records","baseline.4.8.html");
P.fA("Submitting Performance Status Data","baseline.4.9.html");
P.fA("Working With Treatment Data","treatment.5.1.html");
P.fA("About Treatment Data","treatment.5.2.html");
P.fA("Submitting Treatment Regimen Data","treatment.5.3.html");
P.fA("Adding Treatment Regimen Records","treatment.5.4.html");
P.fA("Updating Treatment Regimen Records","treatment.5.5.html");
P.fA("Submitting Cycle Data","treatment.5.6.html");
P.fA("Adding Cycle Records","treatment.5.7.html");
P.fA("Updating Cycle Records","treatment.5.8.html");
P.fA("Submitting Drug/Biologics Data","treatment.5.9.html");
P.fA("Adding Drug/Biologic Records","treatment.5.10.html");
P.fA("Updating Drug/Biologic Data","treatment.5.11.html");
P.fA("Submitting Surgery Data","treatment.5.12.html");
P.fA("Adding Surgery Records","treatment.5.13.html");
P.fA("Updating Surgery Records","treatment.5.14.html");
P.fA("Submitting Radiation Data","treatment.5.15.html");
P.fA("Adding Radiation Records","treatment.5.16.html");
P.fA("Updating Radiation Records","treatment.5.17.html");
P.fA("Submitting Off-Treatment Data","treatment.5.18.html");
P.fA("Working With Outcome Data","outcomes.6.1.html");
P.fA("About Outcome Data","outcomes.6.2.html");
P.fA("Submitting Disease Evaluation Data","outcomes.6.3.html");
P.fA("Adding Disease Evaluation Records","outcomes.6.4.html");
P.fA("Submitting Lesion Assessment Data","outcomes.6.5.html");
P.fA("Adding Lesion Assessment Records","outcomes.6.6.html");
P.fA("Updating Lesion Assessment Records","outcomes.6.7.html");
P.fA("Deleting Lesion Assessment Records","outcomes.6.8.html");
P.fA("Submitting Death Information","outcomes.6.9.html");
P.fA("Application Support","appSupport.7.1.html");
}
