package gov.nih.nci.coppa.services.pa.trialregistrationservice.service.globus;

import gov.nih.nci.coppa.services.pa.trialregistrationservice.service.TrialRegistrationServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the PAServicesImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class TrialRegistrationServiceProviderImpl{
	
	TrialRegistrationServiceImpl impl;
	
	public TrialRegistrationServiceProviderImpl() throws RemoteException {
		impl = new TrialRegistrationServiceImpl();
	}
	

    public gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.CreateInterventionalStudyProtocolResponse createInterventionalStudyProtocol(gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.CreateInterventionalStudyProtocolRequest params) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.CreateInterventionalStudyProtocolResponse boxedResult = new gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.CreateInterventionalStudyProtocolResponse();
    boxedResult.setId(impl.createInterventionalStudyProtocol(params.getStudyProtocol().getStudyProtocol(),params.getStudyOverallStatus().getStudyOverallStatus(),params.getStudyIndlde().getStudyIndlde(),params.getStudyResourcing().getStudyResourcing(),params.getDocument().getDocument(),params.getLeadOrganization().getOrganization(),params.getPrincipalInvestigator().getPerson(),params.getSponsorOrganization().getOrganization(),params.getLeadOrganizationSiteIdentifier().getStudySite(),params.getNctIdentifierSiteIdentifier().getStudySite(),params.getStudyContact().getStudyContact(),params.getStudySiteContact().getStudySiteContact(),params.getSummaryForOrganization().getOrganization(),params.getSummaryForStudyResourcing().getStudyResourcing(),params.getResponsiblePartyContact().getId()));
    return boxedResult;
  }

    public gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.AmendResponse amend(gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.AmendRequest params) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.AmendResponse boxedResult = new gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.AmendResponse();
    boxedResult.setId(impl.amend(params.getStudyProtocol().getStudyProtocol(),params.getStudyOverallStatus().getStudyOverallStatus(),params.getStudyIndlde().getStudyIndlde(),params.getStudyResourcing().getStudyResourcing(),params.getDocument().getDocument(),params.getLeadOrganization().getOrganization(),params.getPrincipalInvestigator().getPerson(),params.getSponsorOrganization().getOrganization(),params.getLeadOrganizationSiteIdentifier().getStudySite(),params.getNctIdentifierSiteIdentifier().getStudySite(),params.getStudyContact().getStudyContact(),params.getStudySiteContact().getStudySiteContact(),params.getSummaryForOrganization().getOrganization(),params.getSummaryForStudyResourcing().getStudyResourcing(),params.getResponsiblePartyContact().getId()));
    return boxedResult;
  }

    public gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.UpdateResponse update(gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.UpdateRequest params) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.UpdateResponse boxedResult = new gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.UpdateResponse();
    impl.update(params.getStudyProtocol().getStudyProtocol(),params.getStudyOverallStatus().getStudyOverallStatus(),params.getStudySite().getStudySite(),params.getStudyIndlde().getStudyIndlde(),params.getStudyResourcing().getStudyResourcing(),params.getDocument().getDocument(),params.getLeadOrganization().getOrganization(),params.getPrincipalInvestigator().getPerson(),params.getSponsorOrganization().getOrganization(),params.getStudyContact().getStudyContact(),params.getStudySiteContact().getStudySiteContact(),params.getSummaryForOrganization().getOrganization(),params.getSummaryForStudyResourcing().getStudyResourcing(),params.getResponsiblePartyContact().getId(),params.getStudyRegulatoryAuthority().getStudyRegulatoryAuthority(),params.getCollaborators().getStudySite(),params.getParticipatingSites().getStudySiteAccrualStatus(),params.getPgCdUpdatedList().getStudySite());
    return boxedResult;
  }

    public gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.RejectResponse reject(gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.RejectRequest params) throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.RejectResponse boxedResult = new gov.nih.nci.coppa.services.pa.trialregistrationservice.stubs.RejectResponse();
    impl.reject(params.getStudyProtocol().getId());
    return boxedResult;
  }

}
