package gov.nih.nci.coppa.services.outcomes.activityrelationship.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface ActivityRelationshipI {

  /**
   * Gets the ActivityRelationship by target performed activity.
   *
   * @param id
   * @param typeCode
   */
  public gov.nih.nci.coppa.services.outcomes.ActivityRelationship[] getByTargetPerformedActivity(gov.nih.nci.coppa.services.outcomes.Id id,gov.nih.nci.coppa.services.outcomes.CD typeCode) throws RemoteException ;

  /**
   * Gets the ActivityRelationship by source performed activity.
   *
   * @param id
   * @param typeCode
   */
  public gov.nih.nci.coppa.services.outcomes.ActivityRelationship[] getBySourcePerformedActivity(gov.nih.nci.coppa.services.outcomes.Id id,gov.nih.nci.coppa.services.outcomes.CD typeCode) throws RemoteException ;

  public gov.nih.nci.coppa.services.outcomes.ActivityRelationship get(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException ;

  public gov.nih.nci.coppa.services.outcomes.ActivityRelationship create(gov.nih.nci.coppa.services.outcomes.ActivityRelationship activityRelationship) throws RemoteException ;

  public gov.nih.nci.coppa.services.outcomes.ActivityRelationship update(gov.nih.nci.coppa.services.outcomes.ActivityRelationship activityRelationship) throws RemoteException ;

  public void delete(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException ;

}

