package gov.nih.nci.coppa.services.pa.studyoutcomemeasureservice.service;

import gov.nih.nci.coppa.iso.Ii;
import gov.nih.nci.coppa.services.grid.dto.transform.DtoTransformException;
import gov.nih.nci.coppa.services.grid.dto.transform.iso.IITransformer;
import gov.nih.nci.coppa.services.pa.StudyOutcomeMeasure;
import gov.nih.nci.coppa.services.pa.grid.dto.pa.StudyOutcomeMeasureTransformer;
import gov.nih.nci.coppa.services.pa.grid.dto.pa.faults.FaultUtil;
import gov.nih.nci.coppa.services.pa.grid.remote.InvokeStudyOutcomeMeasureEjb;
import gov.nih.nci.pa.iso.dto.StudyOutcomeMeasureDTO;

import java.rmi.RemoteException;
import java.util.List;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

/**
 * Implementation of the StudyOutcomeMeasureService. Dispatches to the remote EJBs and the Transformers.
 * @author mshestopalov
 */
public class StudyOutcomeMeasureServiceImpl extends StudyOutcomeMeasureServiceImplBase {

    private static final Logger logger = LogManager.getLogger(StudyOutcomeMeasureServiceImpl.class);
    private final InvokeStudyOutcomeMeasureEjb studyOutMeasureService = new InvokeStudyOutcomeMeasureEjb();
    public StudyOutcomeMeasureServiceImpl() throws RemoteException {
        super();
    }

  private StudyOutcomeMeasure[] convert(List<StudyOutcomeMeasureDTO> dtosList) throws DtoTransformException {
      StudyOutcomeMeasure[] result = null;
      result = new StudyOutcomeMeasure[dtosList.size()];
      int i = 0;
      for (StudyOutcomeMeasureDTO tEmp : dtosList) {
          result[i] = StudyOutcomeMeasureTransformer.INSTANCE.toXml(tEmp);
          i++;
      }
      return result;
  }

  public gov.nih.nci.coppa.services.pa.StudyOutcomeMeasure[] getByStudyProtocol(gov.nih.nci.coppa.services.pa.Id id)
  throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
      try {
          Ii iiDto = IITransformer.INSTANCE.toDto(id);
          List<StudyOutcomeMeasureDTO> dtosList = studyOutMeasureService.getByStudyProtocol(iiDto);
          return convert(dtosList);
      } catch (Exception e) {
          logger.error(e.getMessage(), e);
          throw FaultUtil.reThrowRemote(e);
      }
  }

  public void copy(gov.nih.nci.coppa.services.pa.Id fromStudyProtocolId,gov.nih.nci.coppa.services.pa.Id toStudyProtocolId)
  throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.pa.StudyOutcomeMeasure[] getCurrentByStudyProtocol(gov.nih.nci.coppa.services.pa.Id studyProtocolId)
  throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
      try {
          Ii iiDto = IITransformer.INSTANCE.toDto(studyProtocolId);
          List<StudyOutcomeMeasureDTO> dtosList = studyOutMeasureService.getCurrentByStudyProtocol(iiDto);
          return convert(dtosList);
      } catch (Exception e) {
          logger.error(e.getMessage(), e);
          throw FaultUtil.reThrowRemote(e);
      }
  }

  public gov.nih.nci.coppa.services.pa.StudyOutcomeMeasure get(gov.nih.nci.coppa.services.pa.Id id)
  throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {

      StudyOutcomeMeasureDTO result = null;
      try {
          Ii iiDto = IITransformer.INSTANCE.toDto(id);
          result = studyOutMeasureService.get(iiDto);

          return StudyOutcomeMeasureTransformer.INSTANCE.toXml(result);
      } catch (Exception e) {
          logger.error(e.getMessage(), e);
          throw FaultUtil.reThrowRemote(e);
      }
  }

  public gov.nih.nci.coppa.services.pa.StudyOutcomeMeasure create(gov.nih.nci.coppa.services.pa.StudyOutcomeMeasure studyOutcomeMeasure)
  throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.coppa.services.pa.StudyOutcomeMeasure update(gov.nih.nci.coppa.services.pa.StudyOutcomeMeasure studyOutcomeMeasure)
  throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void delete(gov.nih.nci.coppa.services.pa.Id id)
  throws RemoteException, gov.nih.nci.coppa.services.pa.faults.PAFault {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

