package gov.nih.nci.coppa.services.outcomes.business.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface BusinessI {

  public gov.nih.nci.coppa.services.outcomes.business.Patient[] get(gov.nih.nci.coppa.services.outcomes.business.Patient patient) throws RemoteException ;

  public gov.nih.nci.coppa.services.outcomes.business.Patient getById(gov.nih.nci.iso21090.extensions.Id id) throws RemoteException ;

  public gov.nih.nci.coppa.services.outcomes.business.Patient write(gov.nih.nci.coppa.services.outcomes.business.Patient patient) throws RemoteException ;

}

