package gov.nih.nci.coppa.services.outcomes.submission.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface SubmissionI {

  public gov.nih.nci.coppa.services.outcomes.Submission[] getByStudyProtocol(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException ;

  public gov.nih.nci.coppa.services.outcomes.Submission get(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException ;

  public gov.nih.nci.coppa.services.outcomes.Submission create(gov.nih.nci.coppa.services.outcomes.Submission submission) throws RemoteException ;

  public gov.nih.nci.coppa.services.outcomes.Submission update(gov.nih.nci.coppa.services.outcomes.Submission submission) throws RemoteException ;

  public void delete(gov.nih.nci.coppa.services.outcomes.Id id) throws RemoteException ;

}

